// gen-tool-counts generates tool_counts_generated.go in the mcpserver package.
// It instantiates the MCP server, calls ToolGroups(), and writes the per-group
// and total tool counts so tests can reference them without hard-coded literals.
//
// Usage (via go generate):
//
//	go run github.com/hairglasses-studio/ralphglasses/internal/mcpserver/cmd/gen-tool-counts \
//	    -output internal/mcpserver/tool_counts_generated.go
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
	"text/template"

	"github.com/hairglasses-studio/ralphglasses/internal/mcpserver"
)

var outputFlag = flag.String("output", "tool_counts_generated.go", "path to write generated file")

const fileTmpl = `// Code generated by gen-tool-counts; DO NOT EDIT.
package mcpserver

// GeneratedToolCounts maps each tool group name to its current tool count.
// Re-generate with: go generate ./internal/mcpserver/...
var GeneratedToolCounts = map[string]int{
{{- range .Entries}}
	"{{.Name}}": {{.Count}},
{{- end}}
}

// GeneratedTotalTools is the sum of all tool counts across all groups.
var GeneratedTotalTools = {{.Total}}
`

type entry struct {
	Name  string
	Count int
}

type tmplData struct {
	Entries []entry
	Total   int
}

func main() {
	flag.Parse()

	srv := mcpserver.NewServer("/tmp")
	groups := srv.ToolGroups()

	// Collect entries sorted by the canonical ToolGroupNames order.
	nameIndex := make(map[string]int, len(mcpserver.ToolGroupNames))
	for i, n := range mcpserver.ToolGroupNames {
		nameIndex[n] = i
	}

	entries := make([]entry, 0, len(groups))
	total := 0
	for _, g := range groups {
		entries = append(entries, entry{Name: g.Name, Count: len(g.Tools)})
		total += len(g.Tools)
	}

	// Sort by canonical order; fall back to alphabetical for any extra groups.
	sort.SliceStable(entries, func(i, j int) bool {
		ii, iok := nameIndex[entries[i].Name]
		jj, jok := nameIndex[entries[j].Name]
		if iok && jok {
			return ii < jj
		}
		if iok {
			return true
		}
		if jok {
			return false
		}
		return entries[i].Name < entries[j].Name
	})

	data := tmplData{Entries: entries, Total: total}

	t, err := template.New("counts").Parse(fileTmpl)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-tool-counts: template parse: %v\n", err)
		os.Exit(1)
	}

	var sb strings.Builder
	if err := t.Execute(&sb, data); err != nil {
		fmt.Fprintf(os.Stderr, "gen-tool-counts: template execute: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(*outputFlag, []byte(sb.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gen-tool-counts: write %s: %v\n", *outputFlag, err)
		os.Exit(1)
	}

	fmt.Printf("gen-tool-counts: wrote %s (%d groups, %d total tools)\n", *outputFlag, len(entries), total)
}
