{ config, lib, pkgs, ... }:

let
  cfg = config.services.ralphglasses;

  # Generate .ralphrc content from provider enables and extraConfig.
  providerLines =
    lib.optional cfg.providers.claude.enable ''PROVIDER="claude"''
    ++ lib.optional cfg.providers.gemini.enable ''CASCADE_CHEAP_PROVIDER="gemini"''
    ++ lib.optional cfg.providers.openai.enable ''CASCADE_EXPENSIVE_PROVIDER="openai"'';

  extraLines = lib.mapAttrsToList (k: v: ''${k}="${toString v}"'') cfg.extraConfig;

  ralphrcContent = lib.concatStringsSep "\n" (
    [ "# Generated by NixOS module — do not edit manually" ]
    ++ providerLines
    ++ extraLines
  ) + "\n";

  ralphrcFile = pkgs.writeText "ralphrc" ralphrcContent;

  scanPathArgs = lib.concatMapStringsSep " " (p: "--scan-path ${lib.escapeShellArg p}") cfg.scanPaths;

in {
  options.services.ralphglasses = {

    enable = lib.mkEnableOption "ralphglasses multi-LLM agent fleet controller";

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.ralphglasses or (throw "ralphglasses package not found; pass it via an overlay or set services.ralphglasses.package");
      defaultText = lib.literalExpression "pkgs.ralphglasses";
      description = "The ralphglasses package to use.";
    };

    scanPaths = lib.mkOption {
      type = lib.types.listOf lib.types.path;
      default = [ ];
      example = [ "/home/dev/projects" "/srv/repos" ];
      description = "List of paths to scan for repositories.";
    };

    user = lib.mkOption {
      type = lib.types.str;
      default = "ralphglasses";
      description = "User account under which ralphglasses runs.";
    };

    group = lib.mkOption {
      type = lib.types.str;
      default = "ralphglasses";
      description = "Group under which ralphglasses runs.";
    };

    extraConfig = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      example = {
        MAX_CALLS_PER_HOUR = "80";
        BUDGET = "50.00";
        PRIMARY_MODEL = "sonnet";
      };
      description = ''
        Additional .ralphrc settings as key-value pairs.
        Keys must be uppercase with underscores (e.g. MAX_CALLS_PER_HOUR).
        Values are always strings.
      '';
    };

    providers = {
      claude = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = "Enable the Claude provider.";
        };
      };
      gemini = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = false;
          description = "Enable the Gemini provider.";
        };
      };
      openai = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = false;
          description = "Enable the OpenAI provider.";
        };
      };
    };
  };

  config = lib.mkIf cfg.enable {

    users.users = lib.mkIf (cfg.user == "ralphglasses") {
      ralphglasses = {
        isSystemUser = true;
        group = cfg.group;
        home = "/var/lib/ralphglasses";
        description = "ralphglasses service user";
      };
    };

    users.groups = lib.mkIf (cfg.group == "ralphglasses") {
      ralphglasses = { };
    };

    systemd.services.ralphglasses = {
      description = "ralphglasses — multi-LLM agent fleet controller";
      wantedBy = [ "multi-user.target" ];
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];

      serviceConfig = {
        Type = "simple";
        User = cfg.user;
        Group = cfg.group;
        ExecStart = "${cfg.package}/bin/ralphglasses ${scanPathArgs}";
        Restart = "on-failure";
        RestartSec = 10;

        # State and config directories
        StateDirectory = "ralphglasses";
        StateDirectoryMode = "0750";
        ConfigurationDirectory = "ralphglasses";
        ConfigurationDirectoryMode = "0750";

        # Place .ralphrc in the config directory
        ExecStartPre = "${pkgs.coreutils}/bin/install -m 0640 -o ${cfg.user} -g ${cfg.group} ${ralphrcFile} /etc/ralphglasses/.ralphrc";

        # Hardening
        NoNewPrivileges = true;
        ProtectSystem = "strict";
        ProtectHome = "read-only";
        PrivateTmp = true;
        ReadWritePaths = [ "/var/lib/ralphglasses" ] ++ cfg.scanPaths;
      };

      environment = {
        HOME = "/var/lib/ralphglasses";
        RALPHRC = "/etc/ralphglasses/.ralphrc";
      };
    };
  };
}
