# GENERATED BY tools/genskillsurface; DO NOT EDIT
#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
extension_root="$(cd "${script_dir}/.." && pwd)"
repo_root="$(cd "${extension_root}/../../.." && pwd)"

find "${repo_root}/.gemini/commands" -maxdepth 1 -type f -name 'jit-*.toml' -delete 2>/dev/null || true
find "${repo_root}/.codex/agents" -maxdepth 1 -type f -name 'jit-*.toml' -delete 2>/dev/null || true

echo "cleaned stale JIT agent surfaces"
