# GENERATED BY tools/genskillsurface; DO NOT EDIT
#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
extension_root="$(cd "${script_dir}/.." && pwd)"
repo_root="$(cd "${extension_root}/../../.." && pwd)"

cd "${repo_root}"
exec bash "${repo_root}/scripts/dev/run-mcp.sh" --scan-path "~/hairglasses-studio"
