# GENERATED BY tools/genskillsurface; DO NOT EDIT
#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
extension_root="$(cd "${script_dir}/.." && pwd)"

echo "Validate the Ralphglasses Antigravity extension bundle before linking:"
bash "${script_dir}/validate.sh"
echo
echo "Link it into Gemini or Antigravity with:"
echo "  gemini extensions link \"${extension_root}\""
