# GENERATED BY tools/genskillsurface; DO NOT EDIT
#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
extension_root="$(cd "${script_dir}/.." && pwd)"
repo_root="$(cd "${extension_root}/../../.." && pwd)"

required=(
  "${repo_root}/AGENTS.md"
  "${repo_root}/.mcp.json"
  "${repo_root}/.agents/rules/ralphglasses.md"
  "${repo_root}/.agents/workflows/discover-and-load.md"
  "${extension_root}/gemini-extension.json"
)

for path in "${required[@]}"; do
  [[ -e "${path}" ]] || { echo "missing: ${path}" >&2; exit 1; }
done

echo "ralphglasses Antigravity extension bundle looks healthy"
