// genconfig introspects the ralphglasses config structs and .ralphrc key
// registry to produce a comprehensive markdown reference document.
//
// Usage:
//
//	go run tools/genconfig/main.go > docs/ralphrc-reference.md
package main

import (
	"fmt"
	"reflect"
	"sort"
	"strings"
	"time"

	"github.com/hairglasses-studio/ralphglasses/internal/config"
	"github.com/hairglasses-studio/ralphglasses/internal/model"
	"github.com/hairglasses-studio/ralphglasses/internal/ralphpath"
)

func main() {
	fmt.Print(renderConfigReference())
}

func renderConfigReference() string {
	var b strings.Builder
	w := &b

	fmt.Fprintln(w, "# Ralphglasses Configuration Reference")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "<!-- Auto-generated by tools/genconfig/main.go -- do not edit manually -->")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Ralphglasses uses two configuration layers:")
	fmt.Fprintln(w)
	fmt.Fprintf(w, "1. **Runtime config** (`%s`) -- JSON file with typed fields for the TUI and session manager.\n", ralphpath.ConfigPathDefaultDescription())
	fmt.Fprintln(w, "2. **Per-repo config** (`.ralphrc`) -- key=value file in each repo root for per-project settings.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "---")
	fmt.Fprintln(w)

	// ---------------------------------------------------------------
	// Section 1: Runtime Config struct (internal/config.Config)
	// ---------------------------------------------------------------
	fmt.Fprintln(w, "## Runtime Config (`config.json`)")
	fmt.Fprintln(w)
	fmt.Fprintf(w, "Loaded from `%s`.\n", ralphpath.ConfigPathDefaultDescription())
	fmt.Fprintln(w, "Format: JSON. The config watcher auto-reloads on file change with a 500ms debounce.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "### Fields")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "| Field | JSON Key | Type | Default | Description |")
	fmt.Fprintln(w, "|-------|----------|------|---------|-------------|")

	t := reflect.TypeFor[config.Config]()
	for f := range t.Fields() {
		f := f
		jsonTag := f.Tag.Get("json")
		jsonKey := strings.Split(jsonTag, ",")[0]
		if jsonKey == "" || jsonKey == "-" {
			continue
		}
		typeName := friendlyType(f.Type)
		desc := structFieldDescription(f)
		def := structFieldDefault(f)
		fmt.Fprintf(w, "| `%s` | `%s` | `%s` | %s | %s |\n", f.Name, jsonKey, typeName, def, desc)
	}

	fmt.Fprintln(w)
	fmt.Fprintln(w, "### Example")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "```json")
	fmt.Fprintln(w, `{`)
	fmt.Fprintf(w, "  \"scan_paths\": [\"%s\"],\n", config.DefaultScanPath)
	fmt.Fprintln(w, `  "default_provider": "codex",`)
	fmt.Fprintln(w, `  "worker_provider": "gemini",`)
	fmt.Fprintln(w, `  "max_workers": 4,`)
	fmt.Fprintln(w, `  "default_budget_usd": 5.00,`)
	fmt.Fprintln(w, `  "cost_rate_multiplier": 1.0,`)
	fmt.Fprintln(w, `  "session_timeout": "30m",`)
	fmt.Fprintln(w, `  "health_check_interval": "10s"`)
	fmt.Fprintln(w, `}`)
	fmt.Fprintln(w, "```")
	fmt.Fprintln(w)

	// ---------------------------------------------------------------
	// Section 2: Provider Costs
	// ---------------------------------------------------------------
	fmt.Fprintln(w, "### Provider Cost Overrides (`cost_rates.json`)")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Cost rates can be overridden via `.ralph/cost_rates.json` or the `provider_costs` field.")
	fmt.Fprintln(w, "Partial overrides are merged with compiled-in defaults.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "**Default rates (USD per 1M tokens):**")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "| Model Key | Input | Output |")
	fmt.Fprintln(w, "|-----------|-------|--------|")

	defaults := config.DefaultProviderCosts()
	// Collect all model keys.
	modelKeys := make(map[string]bool)
	for k := range defaults.InputPerMToken {
		modelKeys[k] = true
	}
	for k := range defaults.OutputPerMToken {
		modelKeys[k] = true
	}
	sortedModels := make([]string, 0, len(modelKeys))
	for k := range modelKeys {
		sortedModels = append(sortedModels, k)
	}
	sort.Strings(sortedModels)
	for _, m := range sortedModels {
		in := defaults.InputRate(m, 0)
		out := defaults.OutputRate(m, 0)
		inStr := "--"
		outStr := "--"
		if in > 0 {
			inStr = fmt.Sprintf("$%.2f", in)
		}
		if out > 0 {
			outStr = fmt.Sprintf("$%.2f", out)
		}
		fmt.Fprintf(w, "| `%s` | %s | %s |\n", m, inStr, outStr)
	}

	fmt.Fprintln(w)
	fmt.Fprintln(w, "```json")
	fmt.Fprintln(w, `{`)
	fmt.Fprintln(w, `  "input_per_m_token": { "claude_sonnet": 3.00 },`)
	fmt.Fprintln(w, `  "output_per_m_token": { "claude_sonnet": 15.00 }`)
	fmt.Fprintln(w, `}`)
	fmt.Fprintln(w, "```")
	fmt.Fprintln(w)

	// ---------------------------------------------------------------
	// Section 3: Canonical config keys (config package raw validator)
	// ---------------------------------------------------------------
	fmt.Fprintln(w, "### Canonical Config Keys")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "These keys are recognized by the structured JSON config validator (`ValidateRawConfig`).")
	fmt.Fprintln(w, "The `plugin_*` namespace is reserved for per-plugin configuration.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "| Key | Type | Allowed Values | Range |")
	fmt.Fprintln(w, "|-----|------|----------------|-------|")

	knownKeys := config.KnownKeys()
	for _, k := range knownKeys {
		allowed := "--"
		if len(k.AllowedStr) > 0 {
			allowed = "`" + strings.Join(k.AllowedStr, "`, `") + "`"
		}
		rangeStr := "--"
		if k.MinInt != 0 || k.MaxInt != 0 {
			rangeStr = fmt.Sprintf("[%d, %d]", k.MinInt, k.MaxInt)
		}
		fmt.Fprintf(w, "| `%s` | `%s` | %s | %s |\n", k.Name, k.Type, allowed, rangeStr)
	}

	fmt.Fprintln(w)
	fmt.Fprintln(w, "---")
	fmt.Fprintln(w)

	// ---------------------------------------------------------------
	// Section 4: .ralphrc per-repo config
	// ---------------------------------------------------------------
	fmt.Fprintln(w, "## Per-Repo Config (`.ralphrc`)")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "A simple `KEY=\"value\"` file in the repo root. Lines starting with `#` are comments.")
	fmt.Fprintln(w, "Keys must match `[A-Z_][A-Z0-9_]*`.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "### Known Keys")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "| Key | Type | Default | Description |")
	fmt.Fprintln(w, "|-----|------|---------|-------------|")

	// Sort by key name.
	rcKeys := make([]string, 0, len(model.KnownKeys))
	for k := range model.KnownKeys {
		rcKeys = append(rcKeys, k)
	}
	sort.Strings(rcKeys)

	for _, key := range rcKeys {
		spec := model.KnownKeys[key]
		typeName := configKeyTypeName(spec.Type)
		def := spec.Default
		if def == "" {
			def = "--"
		} else {
			def = "`" + def + "`"
		}
		rangeNote := ""
		switch spec.Type {
		case model.ConfigTypeInt:
			if spec.MinInt != 0 || spec.MaxInt != 0 {
				rangeNote = fmt.Sprintf(" (range: %d--%d)", spec.MinInt, spec.MaxInt)
			}
		case model.ConfigTypeFloat:
			if spec.MinFloat != 0 || spec.MaxFloat != 0 {
				rangeNote = fmt.Sprintf(" (range: %g--%g)", spec.MinFloat, spec.MaxFloat)
			}
		}
		fmt.Fprintf(w, "| `%s` | %s | %s | %s%s |\n", key, typeName, def, spec.Description, rangeNote)
	}

	fmt.Fprintln(w)
	fmt.Fprintln(w, "### Example `.ralphrc`")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "```sh")
	fmt.Fprintln(w, `PROJECT_NAME="my-service"`)
	fmt.Fprintln(w, `MODEL="gpt-5.4"`)
	fmt.Fprintln(w, `BUDGET="10.00"`)
	fmt.Fprintln(w, `PROVIDER="codex"`)
	fmt.Fprintln(w, `MAX_CALLS_PER_HOUR="120"`)
	fmt.Fprintln(w, `CASCADE_ENABLED="true"`)
	fmt.Fprintln(w, `CASCADE_CHEAP_PROVIDER="gemini"`)
	fmt.Fprintln(w, `AUTONOMY_LEVEL="1"`)
	fmt.Fprintln(w, "```")
	fmt.Fprintln(w)

	// ---------------------------------------------------------------
	// Section 5: Deprecated keys
	// ---------------------------------------------------------------
	fmt.Fprintln(w, "### Deprecated Keys")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "These keys are recognized but will be migrated automatically on next load.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "| Deprecated Key | Migration Hint |")
	fmt.Fprintln(w, "|----------------|----------------|")

	depKeys := make([]string, 0, len(model.DeprecatedKeys))
	for k := range model.DeprecatedKeys {
		depKeys = append(depKeys, k)
	}
	sort.Strings(depKeys)
	for _, k := range depKeys {
		fmt.Fprintf(w, "| `%s` | %s |\n", k, model.DeprecatedKeys[k])
	}

	fmt.Fprintln(w)
	fmt.Fprintln(w, "---")
	fmt.Fprintln(w)

	// ---------------------------------------------------------------
	// Section 6: Environment Variables
	// ---------------------------------------------------------------
	fmt.Fprintln(w, "## Environment Variables")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "| Variable | Description |")
	fmt.Fprintln(w, "|----------|-------------|")
	fmt.Fprintln(w, "| `RALPHGLASSES_SCAN_PATH` | Override scan path for the MCP server (colon-separated for multiple paths) |")
	fmt.Fprintln(w, "| `RALPH_THEME` | Default theme name when `--theme` flag is not provided |")
	fmt.Fprintln(w, "| `ANTHROPIC_API_KEY` | Anthropic API key for Claude provider (optional -- Claude Code uses OAuth if missing) |")
	fmt.Fprintln(w, "| `GEMINI_API_KEY` | Google Gemini API key for Gemini provider |")
	fmt.Fprintln(w, "| `OPENAI_API_KEY` | OpenAI API key for Codex/OpenAI provider |")
	fmt.Fprintln(w, "| `OLLAMA_BASE_URL` | Base URL for local Ollama runtime (default `http://127.0.0.1:11434`) |")
	fmt.Fprintln(w, "| `OLLAMA_API_KEY` | Optional Ollama API key; defaults to `ollama` for local compatibility endpoints |")
	fmt.Fprintln(w, "| `OLLAMA_CHAT_MODEL` | Shared local chat/default lightweight model |")
	fmt.Fprintln(w, "| `OLLAMA_FAST_MODEL` | Shared fast local coding lane for verify/report/reflection work |")
	fmt.Fprintln(w, "| `OLLAMA_CODE_MODEL` | Shared local code model used by Ollama session launches |")
	fmt.Fprintln(w, "| `OLLAMA_HEAVY_CODE_MODEL` | Shared heavier local code model |")
	fmt.Fprintln(w, "| `OLLAMA_HIGH_CONTEXT_CODE_MODEL` | Shared high-context local code model |")
	fmt.Fprintln(w, "| `OLLAMA_CLOUD_CODE_MODEL` | Shared cloud coding lane exposed through Ollama-compatible tooling when auth is available |")
	fmt.Fprintln(w, "| `OLLAMA_CLOUD_VERIFIED_CODE_MODEL` | Shared verified/fallback cloud coding lane |")
	fmt.Fprintln(w, "| `OLLAMA_MULTILINGUAL_CODE_MODEL` | Shared multilingual cloud coding lane |")
	fmt.Fprintln(w, "| `OLLAMA_THINKING_CODE_MODEL` | Shared deep-thinking cloud coding lane |")
	fmt.Fprintln(w, "| `OLLAMA_EMBED_MODEL` | Shared local embedding model |")
	fmt.Fprintln(w, "| `OLLAMA_KEEP_ALIVE` | Model keep-alive duration passed through to Ollama-aware surfaces |")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "---")
	fmt.Fprintln(w)

	// ---------------------------------------------------------------
	// Section 7: Valid providers and models
	// ---------------------------------------------------------------
	fmt.Fprintln(w, "## Providers and Models")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "### Recognized Providers")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "`claude`, `gemini`, `codex`, `ollama`, `antigravity`, `crush`, `goose`, `amp`, `a2a`")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "`openai` remains accepted as a deprecated alias for `codex` in config and natural-language routing.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "### Model Prefix Validation")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "| Provider | Accepted Prefixes |")
	fmt.Fprintln(w, "|----------|-------------------|")
	fmt.Fprintln(w, "| `claude` | `claude-`, `sonnet`, `opus`, `haiku` |")
	fmt.Fprintln(w, "| `gemini` | `gemini-` |")
	fmt.Fprintln(w, "| `codex` | `gpt-`, `o1-`, `o3-`, `o4-`, `codex-` |")
	fmt.Fprintln(w, "| `openai` | `gpt-`, `o1-`, `o3-`, `o4-`, `codex-` |")
	fmt.Fprintln(w, "| `ollama` | `llama`, `mistral`, `codellama`, `deepseek`, `phi`, `qwen`, `gemma`, `starcoder`, `devstral`, `nomic`, `glm`, `kimi`, `minimax` |")
	fmt.Fprintln(w, "| `crush` | `sonnet`, `claude-`, `gpt-`, `gemini-` |")
	fmt.Fprintln(w, "| `goose` | `claude-`, `sonnet`, `gpt-`, `gemini-` |")
	fmt.Fprintln(w, "| `amp` | `amp-`, `claude-`, `gpt-`, `gemini-` |")
	fmt.Fprintln(w, "| `a2a` | `a2a-` |")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "---")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "## Validation")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Both config layers are validated on load:")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "- **Runtime config**: `ValidateStruct()` runs 7 rules (budget range, cost rate, provider names, scan paths, duration formats, worker count, conflicting flags).")
	fmt.Fprintln(w, "- **Per-repo `.ralphrc`**: `ValidateConfig()` checks types, ranges, enum membership, and flags deprecated/unknown keys.")
	fmt.Fprintln(w, "- **Config watcher**: Auto-reloads on file change; invalid JSON is rejected (old config preserved), validation warnings are logged but applied.")
	fmt.Fprintln(w)

	return b.String()
}

// friendlyType converts a reflect.Type to a human-readable string.
func friendlyType(t reflect.Type) string {
	// time.Duration is an int64 alias, check before kind switch.
	if t == reflect.TypeFor[time.Duration]() {
		return "duration"
	}
	switch t.Kind() {
	case reflect.Slice:
		return "[]" + friendlyType(t.Elem())
	case reflect.Pointer:
		return "*" + friendlyType(t.Elem())
	case reflect.Struct:
		return t.Name()
	default:
		return t.Name()
	}
}

// structFieldDescription returns a description for a config struct field
// based on its name and type.
func structFieldDescription(f reflect.StructField) string {
	descriptions := map[string]string{
		"ScanPaths":           "Directories to scan for ralph-enabled repos",
		"DefaultProvider":     "Default LLM provider (claude, gemini, codex, ollama, antigravity, crush, goose, amp, a2a; openai is a deprecated codex alias)",
		"WorkerProvider":      "Default provider for worker/delegate tasks",
		"MaxWorkers":          "Maximum concurrent worker sessions (0-50)",
		"DefaultBudgetUSD":    "Default per-session budget in USD (0-10000)",
		"CostRateMultiplier":  "Scales cost estimates (1.0 = normal)",
		"SessionTimeout":      "Default session timeout (Go duration)",
		"HealthCheckInterval": "Provider health poll interval (Go duration)",
		"ProviderCosts":       "Per-model cost rate overrides (USD per 1M tokens)",
	}
	if d, ok := descriptions[f.Name]; ok {
		return d
	}
	return f.Name
}

// structFieldDefault returns the default value for a config struct field.
func structFieldDefault(f reflect.StructField) string {
	defaults := map[string]string{
		"ScanPaths":           "--",
		"DefaultProvider":     "`codex`",
		"WorkerProvider":      "`\"\"`",
		"MaxWorkers":          "`0`",
		"DefaultBudgetUSD":    "`0`",
		"CostRateMultiplier":  "`0`",
		"SessionTimeout":      "`0`",
		"HealthCheckInterval": "`0`",
		"ProviderCosts":       "`nil` (uses compiled-in defaults)",
	}
	if d, ok := defaults[f.Name]; ok {
		return d
	}
	return "--"
}

// configKeyTypeName converts a ConfigKeyType to a display string.
func configKeyTypeName(t model.ConfigKeyType) string {
	switch t {
	case model.ConfigTypeString:
		return "string"
	case model.ConfigTypeInt:
		return "int"
	case model.ConfigTypeFloat:
		return "float"
	case model.ConfigTypeBool:
		return "bool"
	default:
		return "unknown"
	}
}
