package chains

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/hairglasses-studio/webb/internal/patterns"
)

func TestConvertPattern(t *testing.T) {
	registry := NewRegistry()
	converter := NewPatternConverter(registry, "")

	pattern := patterns.DiscoveredPattern{
		ID:           "test-pattern-001",
		Name:         "Investigation Flow",
		Type:         patterns.PatternSequential,
		ToolSequence: []string{"webb_k8s_pods", "webb_k8s_logs", "webb_grafana_alerts"},
		Frequency:    10,
		SuccessRate:  0.85,
	}

	chain := converter.ConvertPattern(pattern, "")

	if chain == nil {
		t.Fatal("expected non-nil chain")
	}

	if !strings.HasPrefix(chain.Name, "pattern-") {
		t.Errorf("expected chain name to start with 'pattern-', got %s", chain.Name)
	}

	if len(chain.Steps) != 3 {
		t.Errorf("expected 3 steps, got %d", len(chain.Steps))
	}

	if chain.Steps[0].Tool != "webb_k8s_pods" {
		t.Errorf("expected first step tool to be webb_k8s_pods, got %s", chain.Steps[0].Tool)
	}

	// Check tags
	hasAutoGenerated := false
	hasPatternMined := false
	for _, tag := range chain.Tags {
		if tag == "auto-generated" {
			hasAutoGenerated = true
		}
		if tag == "pattern-mined" {
			hasPatternMined = true
		}
	}
	if !hasAutoGenerated {
		t.Error("expected 'auto-generated' tag")
	}
	if !hasPatternMined {
		t.Error("expected 'pattern-mined' tag")
	}
}

func TestConvertPatternWithCustomName(t *testing.T) {
	registry := NewRegistry()
	converter := NewPatternConverter(registry, "")

	pattern := patterns.DiscoveredPattern{
		ID:           "test-pattern-002",
		ToolSequence: []string{"webb_pylon_list", "webb_shortcut_search"},
		Frequency:    5,
		SuccessRate:  0.9,
	}

	chain := converter.ConvertPattern(pattern, "my-custom-chain")

	if chain.Name != "my-custom-chain" {
		t.Errorf("expected custom name 'my-custom-chain', got %s", chain.Name)
	}
}

func TestSaveAsYAML(t *testing.T) {
	tmpDir := t.TempDir()
	registry := NewRegistry()
	converter := NewPatternConverter(registry, tmpDir)

	pattern := patterns.DiscoveredPattern{
		ID:           "yaml-test-001",
		Name:         "Ticket Investigation",
		Type:         patterns.PatternSequential,
		ToolSequence: []string{"webb_pylon_search", "webb_incident_list"},
		Frequency:    8,
		SuccessRate:  0.75,
	}

	result, err := converter.SaveAsYAML(pattern, "")
	if err != nil {
		t.Fatalf("failed to save as YAML: %v", err)
	}

	if result.SavedPath == "" {
		t.Error("expected non-empty saved path")
	}

	// Check file exists
	if _, err := os.Stat(result.SavedPath); os.IsNotExist(err) {
		t.Errorf("expected file at %s", result.SavedPath)
	}

	// Read and verify contents
	data, err := os.ReadFile(result.SavedPath)
	if err != nil {
		t.Fatalf("failed to read saved file: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "Auto-generated chain from discovered pattern") {
		t.Error("expected header comment in YAML file")
	}
	if !strings.Contains(content, "webb_pylon_search") {
		t.Error("expected tool name in YAML file")
	}
}

func TestRegisterChain(t *testing.T) {
	registry := NewRegistry()
	converter := NewPatternConverter(registry, "")

	pattern := patterns.DiscoveredPattern{
		ID:           "register-test-001",
		Name:         "Alert Response",
		Type:         patterns.PatternSequential,
		ToolSequence: []string{"webb_grafana_alerts", "webb_k8s_pods"},
		Frequency:    15,
		SuccessRate:  0.95,
	}

	result, err := converter.RegisterChain(pattern, "alert-response-chain")
	if err != nil {
		t.Fatalf("failed to register chain: %v", err)
	}

	if !result.Registered {
		t.Error("expected Registered to be true")
	}

	if result.ChainName != "alert-response-chain" {
		t.Errorf("expected chain name 'alert-response-chain', got %s", result.ChainName)
	}

	// Verify chain is in registry
	chain, err := registry.Get("alert-response-chain")
	if err != nil {
		t.Fatalf("failed to get registered chain: %v", err)
	}

	if chain.Name != "alert-response-chain" {
		t.Errorf("expected registered chain name, got %s", chain.Name)
	}
}

func TestSaveAndRegister(t *testing.T) {
	tmpDir := t.TempDir()
	registry := NewRegistry()
	converter := NewPatternConverter(registry, tmpDir)

	pattern := patterns.DiscoveredPattern{
		ID:           "save-register-001",
		Name:         "Full Flow",
		Type:         patterns.PatternSequential,
		ToolSequence: []string{"webb_ask", "webb_cluster_health"},
		Frequency:    20,
		SuccessRate:  0.88,
	}

	result, err := converter.SaveAndRegister(pattern, "full-flow-chain")
	if err != nil {
		t.Fatalf("failed to save and register: %v", err)
	}

	if !result.Registered {
		t.Error("expected Registered to be true")
	}

	if result.SavedPath == "" {
		t.Error("expected non-empty saved path")
	}

	// Verify file exists
	if _, err := os.Stat(result.SavedPath); os.IsNotExist(err) {
		t.Errorf("expected file at %s", result.SavedPath)
	}

	// Verify chain in registry
	if _, err := registry.Get("full-flow-chain"); err != nil {
		t.Fatalf("chain not in registry: %v", err)
	}
}

func TestInferCategory(t *testing.T) {
	converter := NewPatternConverter(nil, "")

	tests := []struct {
		tools    []string
		expected ChainCategory
	}{
		{
			tools:    []string{"webb_k8s_pods", "webb_k8s_logs", "webb_helm_releases"},
			expected: CategoryOperational,
		},
		{
			tools:    []string{"webb_pylon_search", "webb_ticket_summary", "webb_incident_list"},
			expected: CategoryCustomer,
		},
		{
			tools:    []string{"webb_remediate_pod", "webb_fix_deployment"},
			expected: CategoryRemediation,
		},
		{
			tools:    []string{"webb_investigate_pod", "webb_debug_service"},
			expected: CategoryInvestigative,
		},
	}

	for _, tt := range tests {
		category := converter.inferCategory(tt.tools)
		if category != tt.expected {
			t.Errorf("inferCategory(%v) = %s, expected %s", tt.tools, category, tt.expected)
		}
	}
}

func TestCalculateTimeout(t *testing.T) {
	converter := NewPatternConverter(nil, "")

	tests := []struct {
		toolCount int
		expected  string
	}{
		{toolCount: 1, expected: "1m"},
		{toolCount: 2, expected: "1m"},
		{toolCount: 3, expected: "2m"},
		{toolCount: 5, expected: "4m"}, // 5 * 30s = 150s -> 2.5min * 1.5 = 3.75 -> 4m
		{toolCount: 8, expected: "6m"}, // 8 * 30s = 240s = 4min * 1.5 = 6min
	}

	for _, tt := range tests {
		pattern := patterns.DiscoveredPattern{
			ToolSequence: make([]string, tt.toolCount),
		}
		for i := range pattern.ToolSequence {
			pattern.ToolSequence[i] = "webb_test_tool"
		}

		timeout := converter.calculateTimeout(pattern)
		if timeout != tt.expected {
			t.Errorf("calculateTimeout(%d tools) = %s, expected %s", tt.toolCount, timeout, tt.expected)
		}
	}
}

func TestListConvertiblePatterns(t *testing.T) {
	converter := NewPatternConverter(nil, "")

	discoveredPatterns := []patterns.DiscoveredPattern{
		{
			ID:           "p1",
			Type:         patterns.PatternSequential,
			ToolSequence: []string{"webb_a", "webb_b"},
			Frequency:    5,
		},
		{
			ID:           "p2",
			Type:         patterns.PatternSequential,
			ToolSequence: []string{"webb_c"},
			Frequency:    10, // Only 1 tool - should be excluded
		},
		{
			ID:           "p3",
			Type:         patterns.PatternSequential,
			ToolSequence: []string{"webb_d", "webb_e", "webb_f"},
			Frequency:    2, // Below threshold
		},
		{
			ID:           "p4",
			Type:         "concurrent", // Wrong type
			ToolSequence: []string{"webb_g", "webb_h"},
			Frequency:    10,
		},
	}

	convertible := converter.ListConvertiblePatterns(discoveredPatterns, 3)

	if len(convertible) != 1 {
		t.Errorf("expected 1 convertible pattern, got %d", len(convertible))
	}

	if len(convertible) > 0 && convertible[0].ID != "p1" {
		t.Errorf("expected pattern p1, got %s", convertible[0].ID)
	}
}

func TestGenerateChainName(t *testing.T) {
	converter := NewPatternConverter(nil, "")

	tests := []struct {
		pattern  patterns.DiscoveredPattern
		expected string
	}{
		{
			pattern: patterns.DiscoveredPattern{
				Name:         "Investigation Flow",
				ToolSequence: []string{"webb_a"},
			},
			expected: "pattern-investigation-flow",
		},
		{
			pattern: patterns.DiscoveredPattern{
				Name:         "",
				ToolSequence: []string{"webb_k8s_pods", "webb_grafana_alerts"},
			},
			expected: "pattern-k8s-pods-to-grafana-alerts",
		},
		{
			pattern: patterns.DiscoveredPattern{
				ID:           "abc123",
				Name:         "",
				ToolSequence: []string{},
			},
			expected: "pattern-abc123",
		},
	}

	for _, tt := range tests {
		name := converter.generateChainName(tt.pattern)
		if name != tt.expected {
			t.Errorf("generateChainName() = %s, expected %s", name, tt.expected)
		}
	}
}

func TestDefaultChainsDir(t *testing.T) {
	tmpDir := t.TempDir()
	os.Setenv("HOME", tmpDir)
	defer os.Unsetenv("HOME")

	converter := NewPatternConverter(nil, "")

	expectedDir := filepath.Join(tmpDir, ".config", "webb", "chains")
	if converter.chainsDir != expectedDir {
		t.Errorf("expected chainsDir %s, got %s", expectedDir, converter.chainsDir)
	}
}
