package descriptions

const (
	DescRalphglassesFleetStatus       = "Fleet-wide dashboard: aggregate status, costs, health, and alerts across all repos and sessions in one call"
	DescRalphglassesFleetAnalytics    = "Cost breakdown by provider/repo/time-period with trend analysis. Requires a fleet coordinator started via `ralphglasses serve --coordinator` and an MCP client configured with `RALPH_FLEET_URL`."
	DescRalphglassesFleetSubmit       = "Submit work for `repo` with `prompt` to the distributed fleet queue. Requires a fleet coordinator started via `ralphglasses serve --coordinator` and an MCP client configured with `RALPH_FLEET_URL`."
	DescRalphglassesFleetBudget       = "View or set the fleet-wide budget. Shows spent, remaining, and active work. Requires a fleet coordinator started via `ralphglasses serve --coordinator` and an MCP client configured with `RALPH_FLEET_URL`."
	DescRalphglassesFleetWorkers      = "List registered fleet workers with status, capacity, and spend. Optionally pause, resume, or drain a worker. Requires a fleet coordinator started via `ralphglasses serve --coordinator` and an MCP client configured with `RALPH_FLEET_URL`."
	DescRalphglassesFleetDlq          = "Dead letter queue operations for permanently failed fleet work items. Actions: list, retry, purge, depth. Requires fleet coordinator mode."
	DescRalphglassesFleetSchedule     = "Build a dependency-ordered schedule plan from tasks with dependencies. Uses topological sort to group tasks into parallelizable batches. Returns batch plan, critical path, and depth."
	DescRalphglassesMarathonDashboard = "Compact marathon status: burn rate, stale sessions, team progress, alerts"
	DescRalphglassesFleetRuntime      = "Start, stop, restart, inspect, or auto-discover fleet runtime mode parity for the CLI serve command"
	DescRalphglassesMarathon          = "Start, resume, inspect, or stop the CLI marathon workflow"
	DescRalphglassesFleetCapacityPlan = "Recommend worker count from queue depth and budget. Returns recommended workers, estimated cost, completion time, and cost per worker hour."
	DescRalphglassesFleetGrafana      = "Export a Grafana-compatible JSON dashboard for fleet metrics (session throughput, cost burn rate, provider comparison, error rate, active sessions, budget utilization). Import the output directly into Grafana."
	DescRalphglassesBlackboardQuery   = "Query blackboard entries by namespace for fleet worker coordination. Requires a fleet coordinator started via `ralphglasses serve --coordinator` and an MCP client configured with `RALPH_FLEET_URL`."
	DescRalphglassesBlackboardPut     = "Write an entry to the blackboard for fleet coordination. Requires a fleet coordinator started via `ralphglasses serve --coordinator` and an MCP client configured with `RALPH_FLEET_URL`."
	DescRalphglassesA2aOffers         = "List open agent-to-agent task delegation offers. Requires a fleet coordinator started via `ralphglasses serve --coordinator` and an MCP client configured with `RALPH_FLEET_URL`."
	DescRalphglassesCostForecast      = "Cost burn rate, anomaly detection, and budget exhaustion ETA. Requires a fleet coordinator started via `ralphglasses serve --coordinator` and an MCP client configured with `RALPH_FLEET_URL`."
	DescRalphglassesCostRecommend     = "Analyze cost history and recommend config changes: provider switches, budget pacing, anomaly responses, cache optimization, model downgrades"
	DescRalphglassesRepoHealth        = "Composite health check: circuit breaker, budget, staleness, errors, active sessions"
	DescRalphglassesRepoOptimize      = "Analyze and optimize ralph config files — detect misconfigs, missing settings, stale plans"
	DescRalphglassesRepoScaffold      = "Create/initialize ralph config files (.ralph/, .ralphrc, PROMPT.md, AGENT.md, fix_plan.md) for a repo"
	DescRalphglassesRepoSurfaceAudit  = "Audit repo instruction/config surfaces used by Codex, Claude, Gemini, and MCP clients"
	DescRalphglassesClaudemdCheck     = "Health-check a repo's CLAUDE.md for common issues (length, inline code, overtrigger language, missing headers)"
	DescRalphglassesSnapshot          = "Save or list fleet state snapshots"
	DescRalphglassesWorktreeCreate    = "Create a new git worktree for a repo under .ralph/worktrees/manual/"
	DescRalphglassesWorktreeList      = "List git worktrees for a repo with optional dirty/stale filtering"
	DescRalphglassesWorktreeCleanup   = "Clean up stale loop worktrees older than a given age — skips locked/active worktrees"
)
