package descriptions

const (
	DescRalphglassesSessionLaunch       = "Launch a headless LLM CLI session (claude/gemini/codex) for a repo with a `prompt`"
	DescRalphglassesSessionList         = "List all tracked LLM sessions with status, cost, and turns"
	DescRalphglassesSessionStatus       = "Get detailed status for a session by `id` including output, cost, and turns"
	DescRalphglassesSessionResume       = "Resume a previous LLM CLI session for `repo` using `session_id`"
	DescRalphglassesSessionStop         = "Stop a running session by `id`"
	DescRalphglassesSessionStopAll      = "Stop all running LLM sessions — emergency cost cutoff"
	DescRalphglassesSessionBudget       = "Get cost/budget info for a session by `id`, update the budget, or reset spend tracking"
	DescRalphglassesBudgetStatus        = "Show aggregate budget status across all sessions, matching the CLI budget status command"
	DescRalphglassesSessionRetry        = "Re-launch a failed session by `id` with same params, optional overrides"
	DescRalphglassesSessionOutput       = "Get recent output from a session by `id`"
	DescRalphglassesSessionTail         = "Tail session output by `id` with cursor — returns only new lines since last call"
	DescRalphglassesSessionDiff         = "Git changes made during a session's execution window by `id`"
	DescRalphglassesSessionCompare      = "Compare two sessions by `id1` and `id2`: cost, turns, duration, provider efficiency"
	DescRalphglassesSessionReplayDiff   = "Side-by-side comparison of two session JSONL replay files: event alignment, similarity score"
	DescRalphglassesSessionErrors       = "Aggregated error view: parse failures, API errors, budget warnings"
	DescRalphglassesSessionExport       = "Export a recorded session replay as Markdown or JSON — includes timeline, tool calls, inputs/outputs"
	DescRalphglassesSessionFork         = "Fork a running or completed session — creates a child session with the parent's context and optional new prompt"
	DescRalphglassesSessionHandoff      = "Transfer session state to a new session, optionally switching providers. Includes context from observations, cost tracking, and scratchpad."
	DescRalphglassesErrorContext        = "Get error context for a session — consecutive errors, escalation status, and formatted recent errors for LLM context injection (12-Factor Agents Factor 9)"
	DescRalphglassesLoopStart           = "Create a multi-provider planner/worker perpetual development loop for a repo"
	DescRalphglassesLoopStatus          = "Get status for a perpetual development loop by `id`"
	DescRalphglassesLoopStep            = "Execute one planner/worker/verifier iteration for a loop by `id`"
	DescRalphglassesLoopStop            = "Stop a perpetual development loop by `id`"
	DescRalphglassesLoopBenchmark       = "P50/P95 metrics from recent loop observations for a repo"
	DescRalphglassesLoopBaseline        = "Generate, view, or pin loop performance baseline for a repo"
	DescRalphglassesLoopGates           = "Evaluate regression gates — returns pass/warn/fail report"
	DescRalphglassesSelfTest            = "Run recursive self-test iterations against a repository using the ralphglasses loop engine"
	DescRalphglassesSelfImprove         = "Start a self-improvement loop that autonomously improves a repository — auto-merges safe changes, creates PRs for review-required changes"
	DescRalphglassesLoopPrune           = "Prune stale loop run files by status and age — removes phantom pending/failed loop state that accumulates over time"
	DescRalphglassesLoopAwait           = "Block until a session or loop completes (replaces sleep anti-pattern)"
	DescRalphglassesLoopPoll            = "Non-blocking single status check for a session or loop"
	DescRalphglassesPromptAnalyze       = "Score a prompt across 10 quality dimensions (clarity, specificity, structure, examples, etc.) with letter grades and actionable suggestions"
	DescRalphglassesPromptEnhance       = "Run the 13-stage prompt enhancement pipeline (specificity, positive reframing, XML structure, context reorder, format enforcement, etc.)"
	DescRalphglassesPromptLint          = "Deep-lint a prompt for anti-patterns: unmotivated rules, negative framing, aggressive caps, vague quantifiers, injection risks, cache-unfriendly ordering"
	DescRalphglassesPromptImprove       = "LLM-powered prompt improvement using Claude, Gemini, or OpenAI with domain-specific meta-prompts"
	DescRalphglassesPromptClassify      = "Classify a prompt's task type (code, troubleshooting, analysis, creative, workflow, general)"
	DescRalphglassesPromptShouldEnhance = "Check whether a prompt would benefit from enhancement"
	DescRalphglassesPromptTemplates     = "List available prompt templates with descriptions and required variables"
	DescRalphglassesPromptTemplateFill  = "Fill a prompt template by `name` with `vars` (JSON key-value pairs)"
	DescRalphglassesPromptAbTest        = "A/B test two prompts by scoring them across 10 quality dimensions. Returns winner, score diff, confidence, and per-dimension comparison."
)
