#!/usr/bin/env bash
set -euo pipefail

# Weekly E2E batch: mock scenarios + optional live-fire + regression report.
#
# Usage:
#   scripts/e2e/weekly-batch.sh                  # Mock only
#   scripts/e2e/weekly-batch.sh --live            # Mock + live-fire
#   scripts/e2e/weekly-batch.sh --live --budget 5 # Live with budget cap

LIVE=false
BUDGET=10
BASELINE_PATH=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --live)    LIVE=true; shift ;;
        --budget)  BUDGET="$2"; shift 2 ;;
        --baseline) BASELINE_PATH="$2"; shift 2 ;;
        *) echo "Unknown arg: $1"; exit 1 ;;
    esac
done

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/../.." && pwd)"
go_cmd="${repo_root}/scripts/dev/go.sh"
report_path="${repo_root}/.ralph/e2e-report.md"

mkdir -p "${repo_root}/.ralph"

echo "=== Weekly E2E Batch ($(date -Iseconds)) ==="
echo ""

# Step 1: Mock scenarios
echo "--- Mock Scenarios ---"
if "${go_cmd}" test -run TestE2EAllScenarios ./internal/e2e/ -v -count=1 2>&1 | tee /tmp/e2e-mock.log; then
    mock_status="PASS"
else
    mock_status="FAIL"
fi
echo ""

# Step 2: Regression gates
echo "--- Regression Gates ---"
bl_flag=""
if [[ -n "$BASELINE_PATH" ]]; then
    bl_flag="--baseline ${BASELINE_PATH}"
elif [[ -f "${repo_root}/internal/e2e/testdata/mock_baseline.json" ]]; then
    bl_flag="--baseline ${repo_root}/internal/e2e/testdata/mock_baseline.json"
fi

gate_verdict="skip"
if "${go_cmd}" run . gate-check ${bl_flag} --hours 0 2>/dev/null; then
    gate_verdict="pass"
else
    gate_verdict="fail"
fi
echo "Gate verdict: ${gate_verdict}"
echo ""

# Step 3: Live-fire (optional)
live_status="skipped"
if [[ "$LIVE" == "true" ]]; then
    echo "--- Live-Fire Scenarios ---"
    if BUDGET="${BUDGET}" bash "${script_dir}/run-live.sh" 2>&1 | tee /tmp/e2e-live.log; then
        live_status="PASS"
    else
        live_status="FAIL"
    fi
    echo ""
fi

# Step 4: Generate report
cat > "${report_path}" << EOF
# E2E Batch Report — $(date -Iseconds)

## Mock Scenarios: ${mock_status}

$(grep -E "^(=== RUN|--- (PASS|FAIL))" /tmp/e2e-mock.log 2>/dev/null || echo "No output captured")

## Regression Gates: ${gate_verdict}

## Live-Fire: ${live_status}

---
Generated by \`scripts/e2e/weekly-batch.sh\`
EOF

echo "=== Report written to ${report_path} ==="
echo "Mock: ${mock_status} | Gates: ${gate_verdict} | Live: ${live_status}"

# Exit non-zero on any failure
if [[ "$mock_status" == "FAIL" || "$gate_verdict" == "fail" ]]; then
    exit 1
fi
