#!/usr/bin/env bash
# setup-secrets.sh — First-boot 1Password integration for ralphglasses thin client
# Authenticates with 1Password and writes API keys to env file.
#
# Usage: ./setup-secrets.sh
# Requires: 1password-cli (op)

set -euo pipefail

ENVFILE="${HOME}/.config/ralphglasses/env"
mkdir -p "$(dirname "$ENVFILE")"

echo "=== ralphglasses 1Password Setup ==="
echo "Authenticating with 1Password..."

# Check if op is installed
if ! command -v op &>/dev/null; then
    echo "ERROR: 1password-cli (op) not installed."
    echo "Install: pacman -S 1password-cli"
    exit 1
fi

# Authenticate (interactive — user signs in)
eval "$(op signin 2>/dev/null)" || {
    echo "ERROR: 1Password sign-in failed."
    echo "Run 'eval \$(op signin)' manually first."
    exit 1
}

echo "Reading API keys..."

# Read keys from 1Password vault
ANTHROPIC_API_KEY=$(op read "op://Private/Anthropic API Key/credential" 2>/dev/null || echo "")
OPENAI_API_KEY=$(op read "op://Private/OpenAI API Key/credential" 2>/dev/null || echo "")
GEMINI_API_KEY=$(op read "op://Private/Google AI API Key/credential" 2>/dev/null || echo "")

# Write env file
cat > "$ENVFILE" <<EOF
# Auto-generated by setup-secrets.sh — do not commit
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
OPENAI_API_KEY=${OPENAI_API_KEY}
GEMINI_API_KEY=${GEMINI_API_KEY}
EOF

chmod 600 "$ENVFILE"

# Count configured keys
count=0
[ -n "$ANTHROPIC_API_KEY" ] && count=$((count + 1))
[ -n "$OPENAI_API_KEY" ] && count=$((count + 1))
[ -n "$GEMINI_API_KEY" ] && count=$((count + 1))

echo "Wrote $count API key(s) to $ENVFILE"
echo "Source it in your shell: source $ENVFILE"
