#!/bin/bash
# ltsp-setup.sh — Configure PXE boot server for ralphglasses thin clients
#
# Sets up dnsmasq (DHCP proxy + TFTP), populates the TFTP root with iPXE
# binaries and kernel/initrd, exports NFS root, and optionally generates
# the iPXE config from a template.
#
# Intended for Ubuntu 24.04 server (bare metal, Proxmox VM, or UNRAID Docker).
# Supports both BIOS and UEFI PXE clients.
#
# Usage:
#   sudo ./ltsp-setup.sh [--interface eth0] [--server-ip 10.0.0.1]
#   sudo ./ltsp-setup.sh --dry-run

set -euo pipefail

# ── Defaults ──────────────────────────────────────────────────────────
IFACE="${IFACE:-eth0}"
SERVER_IP="${SERVER_IP:-}"
TFTP_ROOT="/srv/tftp"
IMAGE_DIR="/srv/ltsp/images/ralphglasses"
HTTP_PORT="8080"
DNSMASQ_CONF="/etc/dnsmasq.d/ralphglasses-pxe.conf"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DRY_RUN=0

# ── Parse arguments ──────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --interface)  IFACE="$2"; shift 2 ;;
        --server-ip)  SERVER_IP="$2"; shift 2 ;;
        --tftp-root)  TFTP_ROOT="$2"; shift 2 ;;
        --image-dir)  IMAGE_DIR="$2"; shift 2 ;;
        --http-port)  HTTP_PORT="$2"; shift 2 ;;
        --dry-run)    DRY_RUN=1; shift ;;
        -h|--help)
            echo "Usage: $0 [--interface IFACE] [--server-ip IP] [--tftp-root DIR]"
            echo "          [--image-dir DIR] [--http-port PORT] [--dry-run]"
            exit 0
            ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

# ── Detect server IP if not provided ─────────────────────────────────
if [[ -z "${SERVER_IP}" ]]; then
    SERVER_IP=$(ip -4 addr show "${IFACE}" | awk '/inet / {split($2,a,"/"); print a[1]; exit}')
    if [[ -z "${SERVER_IP}" ]]; then
        echo "ERROR: Could not detect IP for interface ${IFACE}" >&2
        echo "       Pass --server-ip explicitly or check --interface" >&2
        exit 1
    fi
fi

echo "==> ralphglasses PXE server setup"
echo "    Interface:  ${IFACE}"
echo "    Server IP:  ${SERVER_IP}"
echo "    TFTP root:  ${TFTP_ROOT}"
echo "    Image dir:  ${IMAGE_DIR}"
echo "    HTTP port:  ${HTTP_PORT}"
echo "    Dry run:    ${DRY_RUN}"
echo

run() {
    echo "  [run] $*"
    if [[ "${DRY_RUN}" -eq 0 ]]; then
        "$@"
    fi
}

# ── Install dependencies ─────────────────────────────────────────────
echo "==> Installing packages..."
run apt-get update -qq
run apt-get install -y --no-install-recommends \
    dnsmasq \
    ipxe \
    nfs-kernel-server \
    nginx-light \
    squashfs-tools \
    ltsp

# ── Create directory structure ────────────────────────────────────────
echo "==> Creating directory structure..."
run mkdir -p "${TFTP_ROOT}/bios"
run mkdir -p "${TFTP_ROOT}/efi"
run mkdir -p "${TFTP_ROOT}/boot"
run mkdir -p "${IMAGE_DIR}"

# ── Copy iPXE binaries for BIOS and UEFI ─────────────────────────────
echo "==> Copying iPXE boot binaries..."
# BIOS: undionly.kpxe — chainloads from legacy PXE ROM
if [[ -f /usr/lib/ipxe/undionly.kpxe ]]; then
    run cp /usr/lib/ipxe/undionly.kpxe "${TFTP_ROOT}/bios/undionly.kpxe"
elif [[ -f /boot/ipxe/undionly.kpxe ]]; then
    run cp /boot/ipxe/undionly.kpxe "${TFTP_ROOT}/bios/undionly.kpxe"
else
    echo "  WARN: undionly.kpxe not found, BIOS PXE boot may not work"
fi

# UEFI: ipxe.efi or snponly.efi
if [[ -f /usr/lib/ipxe/ipxe.efi ]]; then
    run cp /usr/lib/ipxe/ipxe.efi "${TFTP_ROOT}/efi/ipxe.efi"
elif [[ -f /boot/ipxe/ipxe.efi ]]; then
    run cp /boot/ipxe/ipxe.efi "${TFTP_ROOT}/efi/ipxe.efi"
elif [[ -f /usr/lib/ipxe/snponly.efi ]]; then
    run cp /usr/lib/ipxe/snponly.efi "${TFTP_ROOT}/efi/ipxe.efi"
else
    echo "  WARN: ipxe.efi not found, UEFI PXE boot may not work"
fi

# ── Install iPXE boot script ─────────────────────────────────────────
echo "==> Installing iPXE boot script..."
if [[ -f "${SCRIPT_DIR}/ipxe.cfg" ]]; then
    run cp "${SCRIPT_DIR}/ipxe.cfg" "${TFTP_ROOT}/boot/ipxe.cfg"
else
    echo "  WARN: ipxe.cfg not found in ${SCRIPT_DIR}, skipping"
fi

# ── Configure dnsmasq (DHCP proxy + TFTP) ────────────────────────────
echo "==> Configuring dnsmasq for PXE..."
if [[ "${DRY_RUN}" -eq 0 ]]; then
    cat > "${DNSMASQ_CONF}" <<DNSMASQ
# ralphglasses PXE boot — generated by ltsp-setup.sh
# Proxy DHCP mode: works alongside existing DHCP server

# Interface binding
interface=${IFACE}
bind-interfaces

# Proxy DHCP — respond to PXE requests without handing out IPs
dhcp-range=${SERVER_IP},proxy

# Enable TFTP
enable-tftp
tftp-root=${TFTP_ROOT}

# BIOS clients: serve undionly.kpxe, then chainload ipxe.cfg
# Match tag "ipxe" for clients already running iPXE
dhcp-match=set:ipxe,175
dhcp-boot=tag:!ipxe,bios/undionly.kpxe,,${SERVER_IP}
dhcp-boot=tag:ipxe,boot/ipxe.cfg,,${SERVER_IP}

# UEFI clients: architecture detection via DHCP option 93
# x86-64 UEFI = 7, x86 UEFI = 6, ARM64 = 11
dhcp-match=set:efi-x86_64,option:client-arch,7
dhcp-match=set:efi-x86_64,option:client-arch,9
dhcp-boot=tag:efi-x86_64,efi/ipxe.efi,,${SERVER_IP}

# Logging
log-dhcp
log-queries
log-facility=/var/log/dnsmasq-pxe.log
DNSMASQ
else
    echo "  [dry-run] Would write ${DNSMASQ_CONF}"
fi

# ── NFS export for root filesystem ────────────────────────────────────
echo "==> Configuring NFS export..."
NFS_EXPORT="${IMAGE_DIR} *(ro,async,no_subtree_check,no_root_squash)"
if [[ "${DRY_RUN}" -eq 0 ]]; then
    if ! grep -qF "${IMAGE_DIR}" /etc/exports 2>/dev/null; then
        echo "${NFS_EXPORT}" >> /etc/exports
        echo "  Added NFS export: ${NFS_EXPORT}"
    else
        echo "  NFS export already exists for ${IMAGE_DIR}"
    fi
else
    echo "  [dry-run] Would add to /etc/exports: ${NFS_EXPORT}"
fi

# ── HTTP server for kernel/initrd/squashfs ────────────────────────────
echo "==> Configuring nginx for HTTP boot assets..."
NGINX_CONF="/etc/nginx/sites-available/ralphglasses-pxe"
if [[ "${DRY_RUN}" -eq 0 ]]; then
    cat > "${NGINX_CONF}" <<NGINX
# ralphglasses PXE — HTTP boot asset server
server {
    listen ${HTTP_PORT};
    server_name _;
    root ${IMAGE_DIR};

    location / {
        autoindex on;
        sendfile on;
        tcp_nopush on;
    }
}
NGINX
    run ln -sf "${NGINX_CONF}" /etc/nginx/sites-enabled/ralphglasses-pxe
else
    echo "  [dry-run] Would write ${NGINX_CONF}"
fi

# ── Generate LTSP image if ltsp is available ──────────────────────────
echo "==> Checking LTSP image generation..."
if command -v ltsp &>/dev/null && [[ "${DRY_RUN}" -eq 0 ]]; then
    echo "  LTSP is available. Run these manually when rootfs is ready:"
    echo "    ltsp image ralphglasses"
    echo "    ltsp ipxe"
    echo "    ltsp initrd"
else
    echo "  [info] LTSP commands will be available after package install"
fi

# ── Populate boot assets from LTSP image ─────────────────────────────
echo "==> Checking boot assets..."
for asset in vmlinuz initrd.img; do
    if [[ -f "${IMAGE_DIR}/${asset}" ]]; then
        echo "  Found: ${IMAGE_DIR}/${asset}"
    else
        echo "  MISSING: ${IMAGE_DIR}/${asset}"
        echo "    Copy from rootfs: cp /path/to/rootfs/boot/${asset} ${IMAGE_DIR}/"
    fi
done

# ── Restart services ──────────────────────────────────────────────────
echo "==> Restarting services..."
run systemctl restart dnsmasq
run systemctl restart nfs-kernel-server
run systemctl restart nginx
run exportfs -ra

# ── Firewall hints ────────────────────────────────────────────────────
echo
echo "==> Firewall rules (apply if using ufw/iptables):"
echo "    UDP 67-69   — DHCP + TFTP"
echo "    TCP ${HTTP_PORT}     — HTTP boot assets"
echo "    TCP 2049    — NFS"
echo "    UDP 4011    — Proxy DHCP"
echo

# ── Summary ───────────────────────────────────────────────────────────
echo "==> Setup complete."
echo
echo "Next steps:"
echo "  1. Build the ralphglasses rootfs (distro/Makefile)"
echo "  2. Copy vmlinuz + initrd.img to ${IMAGE_DIR}/"
echo "  3. Generate squashfs: mksquashfs /path/to/rootfs ${IMAGE_DIR}/filesystem.squashfs"
echo "  4. PXE boot a thin client on the same network"
echo
echo "Test with: curl http://${SERVER_IP}:${HTTP_PORT}/"
