package mcpserver

import (
	"github.com/hairglasses-studio/ralphglasses/internal/mcpserver/descriptions"
	"github.com/mark3labs/mcp-go/mcp"
)

func (s *Server) buildRoadmapGroup() ToolGroup {
	return ToolGroup{
		Name:        "roadmap",
		Description: "Roadmap automation: parse, analyze, research, expand, export",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_roadmap_parse",
				mcp.WithDescription(descriptions.DescRalphglassesRoadmapParse),
				mcp.WithString("path", mcp.Required(), mcp.Description("Repo root or direct .md path")),
				mcp.WithString("file", mcp.Description("Override filename (default: ROADMAP.md)")),
				mcp.WithString("phase", mcp.Description("Filter to a specific phase name")),
				mcp.WithBoolean("summary_only", mcp.Description("Return compact summary (phase counts, completion %) instead of full task details")),
				mcp.WithNumber("max_depth", mcp.Description("Depth of detail: 0=phases only, 1=phases+sections, 2=full (default 2)")),
			), s.handleRoadmapParse},
			{mcp.NewTool("ralphglasses_roadmap_analyze",
				mcp.WithDescription(descriptions.DescRalphglassesRoadmapAnalyze),
				mcp.WithString("path", mcp.Required(), mcp.Description("Repo root path")),
				mcp.WithString("file", mcp.Description("Override filename (default: ROADMAP.md)")),
				mcp.WithString("category", mcp.Description("Filter by category: gaps, stale, orphaned, ready")),
				mcp.WithNumber("limit", mcp.Description("Max items per category (default 20)")),
			), s.handleRoadmapAnalyze},
			{mcp.NewTool("ralphglasses_roadmap_research",
				mcp.WithDescription(descriptions.DescRalphglassesRoadmapResearch),
				mcp.WithString("path", mcp.Required(), mcp.Description("Repo root path")),
				mcp.WithString("topics", mcp.Description("Search topics (inferred from go.mod/README if omitted)")),
				mcp.WithNumber("limit", mcp.Description("Max results (default 10)")),
			), s.handleRoadmapResearch},
			{mcp.NewTool("ralphglasses_roadmap_expand",
				mcp.WithDescription(descriptions.DescRalphglassesRoadmapExpand),
				mcp.WithString("path", mcp.Required(), mcp.Description("Repo root path")),
				mcp.WithString("file", mcp.Description("Override filename (default: ROADMAP.md)")),
				mcp.WithString("research", mcp.Description("Research topics to include (runs research internally)")),
				mcp.WithString("style", mcp.Description("Expansion style: conservative, balanced, aggressive (default: balanced)")),
				mcp.WithString("phase", mcp.Description("Filter proposals to a specific phase")),
				mcp.WithNumber("limit", mcp.Description("Max proposals to return (default 20)")),
				mcp.WithBoolean("summary_only", mcp.Description("Drop proposal markdown and return truncated summaries only")),
			), s.handleRoadmapExpand},
			{mcp.NewTool("ralphglasses_roadmap_export",
				mcp.WithDescription(descriptions.DescRalphglassesRoadmapExport),
				mcp.WithString("path", mcp.Required(), mcp.Description("Repo root path")),
				mcp.WithString("file", mcp.Description("Override filename (default: ROADMAP.md)")),
				mcp.WithString("format", mcp.Description("Output format: rdcycle, fix_plan, progress, launch_ready, checkpoint (default: rdcycle). checkpoint emits a docs-ready tranche summary with completed work, verification notes, and next-wave follow-ups. launch_ready enriches tasks with difficulty_score, suggested_provider, estimated_budget_usd")),
				mcp.WithString("phase", mcp.Description("Filter by phase name (default: all)")),
				mcp.WithString("section", mcp.Description("Filter by section name (default: all)")),
				mcp.WithNumber("max_tasks", mcp.Description("Max tasks to export (default 20)")),
				mcp.WithString("respect_deps", mcp.Description("Skip tasks with unmet deps (default: true)")),
				mcp.WithString("status", mcp.Description("Filter by status: incomplete (default), complete, all")),
			), s.handleRoadmapExport},
			{mcp.NewTool("ralphglasses_roadmap_prioritize",
				mcp.WithDescription(descriptions.DescRalphglassesRoadmapPrioritize),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithString("weights", mcp.Description("JSON weights: {\"impact\": 0.4, \"effort\": 0.3, \"dependency\": 0.3}")),
				mcp.WithNumber("top_n", mcp.Description("Number of items to return (default: 20)")),
				mcp.WithString("phase_filter", mcp.Description("Filter to phases containing this string (e.g., 'Phase 10')")),
			), s.handleRoadmapPrioritize},
		},
	}
}

func (s *Server) buildTeamGroup() ToolGroup {
	return ToolGroup{
		Name:        "team",
		Description: "Agent teams and definitions: team_create, team_status, team_delegate, agent_define, agent_list, agent_compose",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_team_create",
				mcp.WithDescription(descriptions.DescRalphglassesTeamCreate),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("name", mcp.Required(), mcp.Description("Team name")),
				mcp.WithString("tenant_id", mcp.Description("Workspace tenant ID (default: _default)")),
				mcp.WithString("tasks", mcp.Required(), mcp.Description("Newline-separated task descriptions")),
				mcp.WithString("provider", mcp.Description("LLM provider for lead: codex (default), claude, gemini")),
				mcp.WithString("worker_provider", mcp.Description("Default LLM provider for worker tasks: codex (default), claude, gemini")),
				mcp.WithString("lead_agent", mcp.Description("Provider-native agent definition name for the lead session. Not supported for Codex teams.")),
				mcp.WithString("model", mcp.Description("Model for lead session")),
				mcp.WithString("worker_model", mcp.Description("Model override for worker sessions")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget in USD — total budget for the team")),
				mcp.WithNumber("max_concurrency", mcp.Description("Maximum concurrent worker tasks (default 2)")),
				mcp.WithNumber("max_retries", mcp.Description("Maximum retries per task (default 2)")),
				mcp.WithString("execution_backend", mcp.Description("Worker execution backend: local, fleet, or a2a")),
				mcp.WithString("worktree_policy", mcp.Description("Worker isolation mode: per_worker (default for Codex) or shared")),
				mcp.WithString("target_branch", mcp.Description("Repo branch to reconcile/promote into (default main)")),
				mcp.WithBoolean("autostart", mcp.Description("Start the background team controller immediately; defaults true for Codex teams")),
				mcp.WithString("a2a_agent_url", mcp.Description("Remote A2A agent/coordinator base URL when execution_backend=a2a")),
				mcp.WithBoolean("dry_run", mcp.Description("Return team configuration without launching sessions")),
			), s.handleTeamCreate},
			{mcp.NewTool("ralphglasses_team_status",
				mcp.WithDescription(descriptions.DescRalphglassesTeamStatus),
				mcp.WithString("name", mcp.Required(), mcp.Description("Team name")),
				mcp.WithString("tenant_id", mcp.Description("Workspace tenant ID (default: _default)")),
			), s.handleTeamStatus},
			{mcp.NewTool("ralphglasses_team_delegate",
				mcp.WithDescription(descriptions.DescRalphglassesTeamDelegate),
				mcp.WithString("name", mcp.Required(), mcp.Description("Team name")),
				mcp.WithString("tenant_id", mcp.Description("Workspace tenant ID (default: _default)")),
				mcp.WithString("task", mcp.Required(), mcp.Description("Task description to delegate")),
				mcp.WithString("provider", mcp.Description("LLM provider override for this task: claude, gemini, codex")),
			), s.handleTeamDelegate},
			{mcp.NewTool("ralphglasses_agent_define",
				mcp.WithDescription(descriptions.DescRalphglassesAgentDefine),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("name", mcp.Required(), mcp.Description("Agent name")),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("Agent system prompt / instructions (markdown)")),
				mcp.WithString("provider", mcp.Description("Target provider: codex (default, .codex/agents/*.toml), claude (.claude/agents/), gemini (.gemini/agents/*.md)")),
				mcp.WithString("description", mcp.Description("Agent description")),
				mcp.WithString("model", mcp.Description("Model override (sonnet, opus, haiku)")),
				mcp.WithString("tools", mcp.Description("Comma-separated allowed tools")),
				mcp.WithNumber("max_turns", mcp.Description("Max turns for this agent")),
			), s.handleAgentDefine},
			{mcp.NewTool("ralphglasses_agent_list",
				mcp.WithDescription(descriptions.DescRalphglassesAgentList),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("provider", mcp.Description("Filter by provider: codex (default), claude, gemini, or 'all'")),
			), s.handleAgentList},
			{mcp.NewTool("ralphglasses_agent_compose",
				mcp.WithDescription(descriptions.DescRalphglassesAgentCompose),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("name", mcp.Required(), mcp.Description("Name for the composite agent")),
				mcp.WithString("agents", mcp.Required(), mcp.Description("Comma-separated agent names to compose")),
				mcp.WithString("provider", mcp.Description("Provider: codex (default), claude, gemini")),
				mcp.WithString("model", mcp.Description("Override model for composite agent")),
			), s.handleAgentCompose},
		},
	}
}

func (s *Server) buildAwesomeGroup() ToolGroup {
	return ToolGroup{
		Name:        "awesome",
		Description: "Awesome-list research: fetch, analyze, diff, report, sync",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_awesome_fetch",
				mcp.WithDescription(descriptions.DescRalphglassesAwesomeFetch),
				mcp.WithString("repo", mcp.Description("GitHub repo (default: hesreallyhim/awesome-claude-code)")),
			), s.handleAwesomeFetch},
			{mcp.NewTool("ralphglasses_awesome_analyze",
				mcp.WithDescription(descriptions.DescRalphglassesAwesomeAnalyze),
				mcp.WithString("repo", mcp.Description("GitHub repo (default: hesreallyhim/awesome-claude-code)")),
				mcp.WithNumber("max_workers", mcp.Description("Concurrent README fetches (default 5)")),
			), s.handleAwesomeAnalyze},
			{mcp.NewTool("ralphglasses_awesome_diff",
				mcp.WithDescription(descriptions.DescRalphglassesAwesomeDiff),
				mcp.WithString("save_to", mcp.Required(), mcp.Description("Repo path where previous index is saved")),
				mcp.WithString("repo", mcp.Description("GitHub repo (default: hesreallyhim/awesome-claude-code)")),
			), s.handleAwesomeDiff},
			{mcp.NewTool("ralphglasses_awesome_report",
				mcp.WithDescription(descriptions.DescRalphglassesAwesomeReport),
				mcp.WithString("save_to", mcp.Required(), mcp.Description("Repo path where analysis is saved")),
				mcp.WithString("format", mcp.Description("Output format: json or markdown (default: markdown)")),
			), s.handleAwesomeReport},
			{mcp.NewTool("ralphglasses_awesome_sync",
				mcp.WithDescription(descriptions.DescRalphglassesAwesomeSync),
				mcp.WithString("save_to", mcp.Required(), mcp.Description("Repo path to save results")),
				mcp.WithString("repo", mcp.Description("GitHub repo (default: hesreallyhim/awesome-claude-code)")),
				mcp.WithString("full_rescan", mcp.Description("Re-analyze all entries, not just new: true/false (default: false)")),
				mcp.WithNumber("max_workers", mcp.Description("Concurrent README fetches (default 5)")),
			), s.handleAwesomeSync},
		},
	}
}

func (s *Server) buildRCGroup() ToolGroup {
	return ToolGroup{
		Name:        "rc",
		Description: "Remote control — send prompts, read output, and act on sessions from mobile or scripted contexts",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_rc_status",
				mcp.WithDescription(descriptions.DescRalphglassesRcStatus),
			), s.handleRCStatus},
			{mcp.NewTool("ralphglasses_rc_send",
				mcp.WithDescription(descriptions.DescRalphglassesRcSend),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("What to tell the agent")),
				mcp.WithString("provider", mcp.Description("Provider override: codex, claude, gemini, ollama, or auto/omit for runtime selection")),
				mcp.WithString("model", mcp.Description("Override model")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget in USD (default: 5.0)")),
				mcp.WithString("resume", mcp.Description("true to resume last session instead of fresh start")),
			), s.handleRCSend},
			{mcp.NewTool("ralphglasses_rc_read",
				mcp.WithDescription(descriptions.DescRalphglassesRcRead),
				mcp.WithString("id", mcp.Description("Session ID (omit for most recently active)")),
				mcp.WithString("cursor", mcp.Description("Cursor from previous call -- only new output")),
				mcp.WithNumber("lines", mcp.Description("Max lines (default 10, max 30)")),
			), s.handleRCRead},
			{mcp.NewTool("ralphglasses_rc_act",
				mcp.WithDescription(descriptions.DescRalphglassesRcAct),
				mcp.WithString("action", mcp.Required(), mcp.Description("Action: stop, stop_all, pause, resume, retry")),
				mcp.WithString("target", mcp.Description("Session ID or repo name (required except stop_all)")),
			), s.handleRCAct},
			{mcp.NewTool("ralphglasses_dispatch",
				mcp.WithDescription(descriptions.DescRalphglassesDispatch),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("action", mcp.Required(), mcp.Description("Action: send, stop, pause, resume, retry")),
				mcp.WithString("prompt", mcp.Description("Prompt text (required for send action)")),
				mcp.WithString("provider", mcp.Description("Provider override: claude, codex, gemini, ollama, or auto (default: auto; runtime selects when omitted)")),
			), s.handleDispatch},
			{mcp.NewTool("ralphglasses_fleet_summary",
				mcp.WithDescription(descriptions.DescRalphglassesFleetSummary),
			), s.handleFleetSummary},
		},
	}
}

func (s *Server) buildAutonomyGroup() ToolGroup {
	return ToolGroup{
		Name:        "autonomy",
		Description: "Autonomy management — view/set autonomy level, inspect supervisor status, review and override autonomous decisions, track HITL events",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_autonomy_level",
				mcp.WithDescription(descriptions.DescRalphglassesAutonomyLevel),
				mcp.WithString("level", mcp.Description("New level: 0-3 or name (omit to view current)")),
				mcp.WithString("repo_path", mcp.Description("Repo path for the supervisor (used when setting level)")),
			), s.handleAutonomyLevel},
			{mcp.NewTool("ralphglasses_supervisor_status",
				mcp.WithDescription(descriptions.DescRalphglassesSupervisorStatus),
			), s.handleSupervisorStatus},
			{mcp.NewTool("ralphglasses_automation_policy",
				mcp.WithDescription(descriptions.DescRalphglassesAutomationPolicy),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("action", mcp.Description("Action: get, set, recommend (default: get)")),
				mcp.WithBoolean("enabled", mcp.Description("Enable or disable subscription-window automation")),
				mcp.WithString("provider", mcp.Description("Provider to automate (default: codex)")),
				mcp.WithString("timezone", mcp.Description("IANA timezone for reset windows")),
				mcp.WithString("reset_cron", mcp.Description("5-field cron for subscription reset timing")),
				mcp.WithString("reset_anchor", mcp.Description("RFC3339 anchor timestamp when using fixed reset_window_hours")),
				mcp.WithNumber("reset_window_hours", mcp.Description("Window size in hours when using reset_anchor")),
				mcp.WithNumber("window_budget_usd", mcp.Description("Synthetic per-window budget used for pacing and forecasting")),
				mcp.WithNumber("target_utilization_pct", mcp.Description("Target percent of the synthetic budget to consume before reset")),
				mcp.WithNumber("resume_backoff_minutes", mcp.Description("Backoff between failed auto-resume attempts")),
				mcp.WithString("default_model", mcp.Description("Default model for queued work")),
				mcp.WithNumber("default_task_budget_usd", mcp.Description("Default budget for queued work items")),
				mcp.WithNumber("default_task_max_turns", mcp.Description("Default max turns for queued work items")),
				mcp.WithNumber("max_concurrent_sessions", mcp.Description("Max concurrent automated sessions (v1 only supports 1)")),
			), s.handleAutomationPolicy},
			{mcp.NewTool("ralphglasses_automation_queue",
				mcp.WithDescription(descriptions.DescRalphglassesAutomationQueue),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("action", mcp.Description("Action: list, enqueue, remove, reprioritize (default: list)")),
				mcp.WithString("job_kind", mcp.Description("Queue job kind: session (default), loop, cycle, research")),
				mcp.WithString("prompt", mcp.Description("Prompt to enqueue")),
				mcp.WithString("provider", mcp.Description("Provider override for queued item")),
				mcp.WithString("model", mcp.Description("Model override for queued item")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget override for queued item")),
				mcp.WithNumber("max_turns", mcp.Description("Max turns override for queued item")),
				mcp.WithNumber("priority", mcp.Description("Queue priority (higher runs first)")),
				mcp.WithString("source", mcp.Description("Queue item source label")),
				mcp.WithString("name", mcp.Description("Cycle name for cycle jobs")),
				mcp.WithString("objective", mcp.Description("Cycle or research objective/topic")),
				mcp.WithString("criteria", mcp.Description("Comma-separated success criteria for cycle jobs")),
				mcp.WithNumber("max_tasks", mcp.Description("Max tasks for cycle jobs")),
				mcp.WithString("research_domain", mcp.Description("Research domain for research jobs")),
				mcp.WithString("research_model_tier", mcp.Description("Research queue model tier for research jobs")),
				mcp.WithNumber("research_priority_score", mcp.Description("Research queue priority score for research jobs")),
				mcp.WithString("id", mcp.Description("Queue item ID for remove/reprioritize")),
			), s.handleAutomationQueue},
			{mcp.NewTool("ralphglasses_autonomy_decisions",
				mcp.WithDescription(descriptions.DescRalphglassesAutonomyDecisions),
				mcp.WithNumber("limit", mcp.Description("Max decisions (default: 20)")),
			), s.handleAutonomyDecisions},
			{mcp.NewTool("ralphglasses_autonomy_override",
				mcp.WithDescription(descriptions.DescRalphglassesAutonomyOverride),
				mcp.WithString("decision_id", mcp.Required(), mcp.Description("Decision ID to override")),
				mcp.WithString("details", mcp.Description("Why this was overridden")),
			), s.handleAutonomyOverride},
			{mcp.NewTool("ralphglasses_hitl_score",
				mcp.WithDescription(descriptions.DescRalphglassesHitlScore),
				mcp.WithNumber("hours", mcp.Description("Time window in hours (default: 24)")),
			), s.handleHITLScore},
			{mcp.NewTool("ralphglasses_hitl_history",
				mcp.WithDescription(descriptions.DescRalphglassesHitlHistory),
				mcp.WithNumber("hours", mcp.Description("Time window in hours (default: 24)")),
				mcp.WithNumber("limit", mcp.Description("Max events (default: 50)")),
			), s.handleHITLHistory},
		},
	}
}

func (s *Server) buildWorkflowGroup() ToolGroup {
	return ToolGroup{
		Name:        "workflow",
		Description: "Workflow automation — define, run, and delete multi-step YAML workflows that sequence agent sessions",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_workflow_define",
				mcp.WithDescription(descriptions.DescRalphglassesWorkflowDefine),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("name", mcp.Required(), mcp.Description("Workflow name")),
				mcp.WithString("yaml", mcp.Required(), mcp.Description("Workflow YAML definition")),
			), s.handleWorkflowDefine},
			{mcp.NewTool("ralphglasses_workflow_run",
				mcp.WithDescription(descriptions.DescRalphglassesWorkflowRun),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("name", mcp.Required(), mcp.Description("Workflow name")),
			), s.handleWorkflowRun},
			{mcp.NewTool("ralphglasses_workflow_delete",
				mcp.WithDescription(descriptions.DescRalphglassesWorkflowDelete),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("name", mcp.Required(), mcp.Description("Workflow name to delete")),
			), s.handleWorkflowDelete},
		},
	}
}

func (s *Server) buildEventsGroup() ToolGroup {
	return ToolGroup{
		Name:        "events",
		Description: "Fleet event bus: query and poll for session, cost, loop, and circuit events",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_event_list",
				mcp.WithDescription(descriptions.DescRalphglassesEventList),
				mcp.WithString("type", mcp.Description("Filter by event type (e.g. session.started, cost.update)")),
				mcp.WithString("types", mcp.Description("Comma-separated event types to filter (OR). Alternative to single 'type' param")),
				mcp.WithString("repo", mcp.Description("Filter by repo name")),
				mcp.WithNumber("limit", mcp.Description("Max events to return (default 50)")),
				mcp.WithString("since", mcp.Description("ISO timestamp filter")),
				mcp.WithString("until", mcp.Description("ISO timestamp upper bound (exclusive)")),
				mcp.WithString("session_id", mcp.Description("Filter by session ID")),
				mcp.WithString("provider", mcp.Description("Filter by provider")),
				mcp.WithNumber("offset", mcp.Description("Skip first N results for pagination (default 0)")),
			), s.handleEventList},
			{mcp.NewTool("ralphglasses_event_poll",
				mcp.WithDescription(descriptions.DescRalphglassesEventPoll),
				mcp.WithString("cursor", mcp.Description("Cursor from previous response (omit for recent)")),
				mcp.WithNumber("limit", mcp.Description("Max events (default 20, max 50)")),
				mcp.WithString("type", mcp.Description("Filter by event type (e.g. session.started, cost.update)")),
			), s.handleEventPoll},
		},
	}
}

func (s *Server) buildFeedbackGroup() ToolGroup {
	return ToolGroup{
		Name:        "feedback",
		Description: "Provider feedback: performance profiles, recommendations, bandit stats, confidence calibration",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_feedback_profiles",
				mcp.WithDescription(descriptions.DescRalphglassesFeedbackProfiles),
				mcp.WithString("action", mcp.Description("Action: 'get' (default) returns profiles, 'seed' forces re-seed from observations")),
				mcp.WithString("type", mcp.Description("Filter: prompt, provider, or omit for both")),
			), s.handleFeedbackProfiles},
			{mcp.NewTool("ralphglasses_provider_recommend",
				mcp.WithDescription(descriptions.DescRalphglassesProviderRecommend),
				mcp.WithString("task", mcp.Required(), mcp.Description("Task description (e.g. 'fix lint errors', 'add search feature')")),
			), s.handleProviderRecommend},
			{mcp.NewTool("ralphglasses_provider_capabilities",
				mcp.WithDescription(descriptions.DescRalphglassesProviderCapabilities),
				mcp.WithString("provider", mcp.Description("Optional provider filter: claude, codex, gemini")),
			), s.handleProviderCapabilities},
			{mcp.NewTool("ralphglasses_provider_compare",
				mcp.WithDescription(descriptions.DescRalphglassesProviderCompare),
				mcp.WithString("task", mcp.Description("Optional task description to include recommendation and feedback context")),
			), s.handleProviderCompare},
			{mcp.NewTool("ralphglasses_bandit_status",
				mcp.WithDescription(descriptions.DescRalphglassesBanditStatus),
			), s.handleBanditStatus},
			{mcp.NewTool("ralphglasses_confidence_calibration",
				mcp.WithDescription(descriptions.DescRalphglassesConfidenceCalibration),
			), s.handleConfidenceCalibration},
		},
	}
}

func (s *Server) buildAdvancedGroup() ToolGroup {
	return ToolGroup{
		Name:        "advanced",
		Description: "Advanced: journals, tool benchmark, circuit breaker reset",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_tool_benchmark",
				mcp.WithDescription(descriptions.DescRalphglassesToolBenchmark),
				mcp.WithString("tool", mcp.Description("Filter to a specific tool name")),
				mcp.WithString("compare", mcp.Description("Include regression analysis vs previous baseline: true/false (default: false)")),
				mcp.WithNumber("hours", mcp.Description("Time window in hours (default 24)")),
			), s.handleToolBenchmark},
			{mcp.NewTool("ralphglasses_journal_read",
				mcp.WithDescription(descriptions.DescRalphglassesJournalRead),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("limit", mcp.Description("Max entries to return (default 10)")),
			), s.handleJournalRead},
			{mcp.NewTool("ralphglasses_journal_write",
				mcp.WithDescription(descriptions.DescRalphglassesJournalWrite),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("worked", mcp.Description("Comma-separated items that worked")),
				mcp.WithString("failed", mcp.Description("Comma-separated items that failed")),
				mcp.WithString("suggest", mcp.Description("Comma-separated suggestions")),
				mcp.WithString("session_id", mcp.Description("Associated session ID (optional)")),
			), s.handleJournalWrite},
			{mcp.NewTool("ralphglasses_journal_prune",
				mcp.WithDescription(descriptions.DescRalphglassesJournalPrune),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("keep", mcp.Description("Number of entries to keep (default 100)")),
				mcp.WithString("dry_run", mcp.Description("Preview only, don't modify: true/false (default: true)")),
			), s.handleJournalPrune},
			{mcp.NewTool("ralphglasses_circuit_reset",
				mcp.WithDescription(descriptions.DescRalphglassesCircuitReset),
				mcp.WithString("service", mcp.Required(), mcp.Description("Service/circuit to reset: 'enhancer' or a repo name")),
			), s.handleCircuitReset},
		},
	}
}

func (s *Server) buildEvalGroup() ToolGroup {
	return ToolGroup{
		Name:        "eval",
		Description: "Offline evaluation: counterfactual analysis, Bayesian A/B testing, frequentist significance testing, changepoint detection",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_eval_counterfactual",
				mcp.WithDescription(descriptions.DescRalphglassesEvalCounterfactual),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Observation window in hours (default: 168 = 7 days)")),
				mcp.WithString("policy", mcp.Required(), mcp.Description("Policy type: cascade_threshold or provider_routing")),
				mcp.WithNumber("threshold", mcp.Description("New cascade threshold for cascade_threshold policy (default: 0.6)")),
				mcp.WithString("task_type", mcp.Description("Task type for provider_routing policy")),
				mcp.WithString("provider", mcp.Description("Target provider for provider_routing policy")),
			), s.handleEvalCounterfactual},
			{mcp.NewTool("ralphglasses_eval_ab_test",
				mcp.WithDescription(descriptions.DescRalphglassesEvalAbTest),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Observation window in hours (default: 168)")),
				mcp.WithString("mode", mcp.Required(), mcp.Description("Comparison mode: providers or periods")),
				mcp.WithString("provider_a", mcp.Description("First provider (providers mode)")),
				mcp.WithString("provider_b", mcp.Description("Second provider (providers mode)")),
				mcp.WithNumber("split_hours_ago", mcp.Description("Hours ago to split time periods (periods mode)")),
			), s.handleEvalABTest},
			{mcp.NewTool("ralphglasses_eval_changepoints",
				mcp.WithDescription(descriptions.DescRalphglassesEvalChangepoints),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Observation window in hours (default: 168)")),
				mcp.WithString("metric", mcp.Description("Specific metric to analyze (completion_rate, cost, latency, confidence, difficulty). Omit for all.")),
			), s.handleEvalChangepoints},
			{mcp.NewTool("ralphglasses_eval_significance",
				mcp.WithDescription(descriptions.DescRalphglassesEvalSignificance),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Observation window in hours (default: 168)")),
				mcp.WithString("mode", mcp.Required(), mcp.Description("Comparison mode: providers, periods, or cost")),
				mcp.WithString("provider_a", mcp.Description("First provider (providers/cost mode)")),
				mcp.WithString("provider_b", mcp.Description("Second provider (providers/cost mode)")),
				mcp.WithNumber("split_hours_ago", mcp.Description("Hours ago to split time periods (periods mode)")),
			), s.handleEvalSignificance},
			{mcp.NewTool("ralphglasses_anomaly_detect",
				mcp.WithDescription(descriptions.DescRalphglassesAnomalyDetect),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Observation window in hours (default: 168)")),
				mcp.WithString("metric", mcp.Required(), mcp.Description("Metric to analyze — full names (total_cost_usd, total_latency_ms, confidence, difficulty_score) or shorthands (cost, latency, difficulty)")),
			), s.handleAnomalyDetect},
			{mcp.NewTool("ralphglasses_eval_define",
				mcp.WithDescription(descriptions.DescRalphglassesEvalDefine),
				mcp.WithString("yaml_content", mcp.Required(), mcp.Description("YAML content defining the A/B test (name, variants, metrics, sample_size, timeout)")),
			), s.handleEvalDefine},
			{mcp.NewTool("ralphglasses_provider_benchmark",
				mcp.WithDescription(descriptions.DescRalphglassesProviderBenchmark),
				mcp.WithString("providers", mcp.Description("Comma-separated providers to benchmark (default: codex,gemini,claude)")),
				mcp.WithNumber("iterations", mcp.Description("Number of iterations per task (default: 3, max: 10)")),
				mcp.WithString("repo", mcp.Description("Repo for result storage")),
			), s.handleProviderBenchmark},
		},
	}
}

func (s *Server) buildRdcycleGroup() ToolGroup {
	return ToolGroup{
		Name:        "rdcycle",
		Description: "R&D cycle automation — finding-to-task conversion, cycle planning, baselines, merging, and scheduling",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_finding_to_task",
				mcp.WithDescription(descriptions.DescRalphglassesFindingToTask),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithString("finding_id", mcp.Description("Finding ID (e.g., FINDING-240); if omitted, all findings in the scratchpad are converted")),
				mcp.WithString("scratchpad_name", mcp.Required(), mcp.Description("Scratchpad filename without path; supports .md or .jsonl (default .md)")),
			), s.handleFindingToTask},
			{mcp.NewTool("ralphglasses_cycle_baseline",
				mcp.WithDescription(descriptions.DescRalphglassesCycleBaseline),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
			), s.handleCycleBaseline},
			{mcp.NewTool("ralphglasses_cycle_plan",
				mcp.WithDescription(descriptions.DescRalphglassesCyclePlan),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithString("previous_cycle_id", mcp.Description("Previous cycle ID for continuity")),
				mcp.WithNumber("max_tasks", mcp.Description("Maximum tasks to include (default: 10)")),
				mcp.WithNumber("budget", mcp.Description("Budget in USD (default: 5.0)")),
			), s.handleCyclePlan},
			{mcp.NewTool("ralphglasses_cycle_merge",
				mcp.WithDescription(descriptions.DescRalphglassesCycleMerge),
				mcp.WithString("worktree_paths", mcp.Required(), mcp.Description("Comma-separated worktree paths to merge")),
				mcp.WithString("conflict_strategy", mcp.Description("Conflict resolution: ours, theirs, or manual (default: manual)")),
			), s.handleCycleMerge},
			{mcp.NewTool("ralphglasses_cycle_schedule",
				mcp.WithDescription(descriptions.DescRalphglassesCycleSchedule),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithString("cron_expr", mcp.Required(), mcp.Description("Cron expression (e.g., '0 2 * * 1' for Monday 2am)")),
				mcp.WithString("cycle_config", mcp.Description("JSON cycle configuration")),
				mcp.WithString("job_kind", mcp.Description("Scheduled job kind (default: cycle)")),
				mcp.WithString("name", mcp.Description("Cycle name for cycle schedules")),
				mcp.WithString("objective", mcp.Description("Cycle objective when cycle_config is omitted")),
				mcp.WithString("criteria", mcp.Description("Comma-separated success criteria when cycle_config is omitted")),
				mcp.WithNumber("max_tasks", mcp.Description("Max cycle tasks when cycle_config is omitted")),
				mcp.WithBoolean("enabled", mcp.Description("Whether the schedule is active (default: true)")),
			), s.handleCycleSchedule},
			{mcp.NewTool("ralphglasses_loop_replay",
				mcp.WithDescription(descriptions.DescRalphglassesLoopReplay),
				mcp.WithString("loop_id", mcp.Required(), mcp.Description("Loop run ID")),
				mcp.WithNumber("iteration", mcp.Required(), mcp.Description("Iteration number to replay")),
				mcp.WithString("overrides", mcp.Description("JSON overrides: {model, provider, budget}")),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected if omitted)")),
			), s.handleLoopReplay},
			{mcp.NewTool("ralphglasses_budget_forecast",
				mcp.WithDescription(descriptions.DescRalphglassesBudgetForecast),
				mcp.WithString("loop_id", mcp.Required(), mcp.Description("Loop run ID to forecast")),
				mcp.WithNumber("iterations", mcp.Description("Number of iterations to forecast (default 10)")),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected if omitted)")),
			), s.handleBudgetForecast},
			{mcp.NewTool("ralphglasses_diff_review",
				mcp.WithDescription(descriptions.DescRalphglassesDiffReview),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithString("ref", mcp.Description("Git ref to review (default HEAD)")),
				mcp.WithString("checks", mcp.Description("CSV of checks: scope_creep, missing_tests, style, todos (default: all)")),
			), s.handleDiffReview},
			{mcp.NewTool("ralphglasses_finding_reason",
				mcp.WithDescription(descriptions.DescRalphglassesFindingReason),
				mcp.WithString("name", mcp.Required(), mcp.Description("Scratchpad name (e.g., 'tool_improvement')")),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected if omitted)")),
			), s.handleFindingReason},
			// Cycle engine tools (state machine integration)
			{mcp.NewTool("ralphglasses_cycle_create",
				mcp.WithDescription(descriptions.DescRalphglassesCycleCreate),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithString("name", mcp.Description("Cycle name (default: 'cycle')")),
				mcp.WithString("objective", mcp.Required(), mcp.Description("Cycle objective")),
				mcp.WithString("criteria", mcp.Description("Comma-separated success criteria")),
			), s.handleCycleCreate},
			{mcp.NewTool("ralphglasses_cycle_advance",
				mcp.WithDescription(descriptions.DescRalphglassesCycleAdvance),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithString("cycle_id", mcp.Description("Cycle ID (default: active cycle)")),
			), s.handleCycleAdvance},
			{mcp.NewTool("ralphglasses_cycle_status",
				mcp.WithDescription(descriptions.DescRalphglassesCycleStatus),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithString("cycle_id", mcp.Description("Cycle ID (default: active cycle)")),
			), s.handleCycleStatus},
			{mcp.NewTool("ralphglasses_cycle_fail",
				mcp.WithDescription(descriptions.DescRalphglassesCycleFail),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithString("cycle_id", mcp.Description("Cycle ID (default: active cycle)")),
				mcp.WithString("error", mcp.Description("Error message")),
			), s.handleCycleFail},
			{mcp.NewTool("ralphglasses_cycle_list",
				mcp.WithDescription(descriptions.DescRalphglassesCycleList),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithNumber("limit", mcp.Description("Max results (default 20)")),
			), s.handleCycleList},
			{mcp.NewTool("ralphglasses_cycle_synthesize",
				mcp.WithDescription(descriptions.DescRalphglassesCycleSynthesize),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithString("cycle_id", mcp.Description("Cycle ID (default: active cycle)")),
				mcp.WithString("summary", mcp.Required(), mcp.Description("Synthesis summary")),
				mcp.WithString("accomplished", mcp.Description("Comma-separated list of accomplishments")),
				mcp.WithString("remaining", mcp.Description("Comma-separated list of remaining work")),
				mcp.WithString("next_objective", mcp.Description("Objective for next cycle")),
				mcp.WithString("patterns", mcp.Description("Comma-separated patterns observed")),
			), s.handleCycleSynthesize},
			{mcp.NewTool("ralphglasses_cycle_run",
				mcp.WithDescription(descriptions.DescRalphglassesCycleRun),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithString("repo_path", mcp.Description("Deprecated alias for repo; retained for backward compatibility")),
				mcp.WithString("name", mcp.Description("Cycle name (default: 'cycle')")),
				mcp.WithString("objective", mcp.Required(), mcp.Description("Cycle objective")),
				mcp.WithString("criteria", mcp.Description("Comma-separated success criteria")),
				mcp.WithNumber("max_tasks", mcp.Description("Max tasks to plan (default 10)")),
			), s.handleCycleRun},
		},
	}
}

func (s *Server) buildObservabilityGroup() ToolGroup {
	return ToolGroup{
		Name:        "observability",
		Description: "Observation queries, scratchpad automation, loop wait/poll, coverage, cost estimation, merge verification",
		Tools: []ToolEntry{
			// Observation query tools
			{mcp.NewTool("ralphglasses_observation_query",
				mcp.WithDescription(descriptions.DescRalphglassesObservationQuery),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Hours of history to query (default 48)")),
				mcp.WithString("loop_id", mcp.Description("Filter by loop ID")),
				mcp.WithString("status", mcp.Description("Filter by status (pass, fail, error)")),
				mcp.WithString("provider", mcp.Description("Filter by provider")),
				mcp.WithNumber("limit", mcp.Description("Max results (default 50, max 500)")),
				mcp.WithString("since", mcp.Description("RFC3339 timestamp lower bound (overrides hours if set)")),
				mcp.WithString("until", mcp.Description("RFC3339 timestamp upper bound")),
			), s.handleObservationQuery},
			{mcp.NewTool("ralphglasses_observation_summary",
				mcp.WithDescription(descriptions.DescRalphglassesObservationSummary),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Hours of history (default 48)")),
				mcp.WithString("loop_id", mcp.Description("Filter by loop ID")),
				mcp.WithString("since", mcp.Description("RFC3339 timestamp lower bound (overrides hours if set)")),
				mcp.WithString("until", mcp.Description("RFC3339 timestamp upper bound")),
			), s.handleObservationSummary},

			// Scratchpad tools
			{mcp.NewTool("ralphglasses_scratchpad_read",
				mcp.WithDescription(descriptions.DescRalphglassesScratchpadRead),
				mcp.WithString("name", mcp.Required(), mcp.Description("Scratchpad name (e.g. 'tool_improvement')")),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected from CWD; required when multiple repos are scanned)")),
			), s.handleScratchpadRead},
			{mcp.NewTool("ralphglasses_scratchpad_append",
				mcp.WithDescription(descriptions.DescRalphglassesScratchpadAppend),
				mcp.WithString("name", mcp.Required(), mcp.Description("Scratchpad name")),
				mcp.WithString("content", mcp.Required(), mcp.Description("Markdown content to append")),
				mcp.WithString("section", mcp.Description("Optional section header to add before content")),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected from CWD; required when multiple repos are scanned)")),
			), s.handleScratchpadAppend},
			{mcp.NewTool("ralphglasses_scratchpad_list",
				mcp.WithDescription(descriptions.DescRalphglassesScratchpadList),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected from CWD; required when multiple repos are scanned)")),
			), s.handleScratchpadList},
			{mcp.NewTool("ralphglasses_scratchpad_resolve",
				mcp.WithDescription(descriptions.DescRalphglassesScratchpadResolve),
				mcp.WithString("name", mcp.Required(), mcp.Description("Scratchpad name")),
				mcp.WithNumber("item_number", mcp.Required(), mcp.Description("Item number to resolve")),
				mcp.WithString("resolution", mcp.Required(), mcp.Description("Resolution description")),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected from CWD; required when multiple repos are scanned)")),
			), s.handleScratchpadResolve},
			{mcp.NewTool("ralphglasses_scratchpad_delete",
				mcp.WithDescription(descriptions.DescRalphglassesScratchpadDelete),
				mcp.WithString("scratchpad", mcp.Required(), mcp.Description("Scratchpad name")),
				mcp.WithString("finding_id", mcp.Required(), mcp.Description("Finding number to delete (e.g. '2')")),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected from CWD; required when multiple repos are scanned)")),
			), s.handleScratchpadDelete},
			{mcp.NewTool("ralphglasses_scratchpad_validate",
				mcp.WithDescription(descriptions.DescRalphglassesScratchpadValidate),
				mcp.WithString("name", mcp.Required(), mcp.Description("Scratchpad name")),
				mcp.WithString("check", mcp.Required(), mcp.Description("Validation type: scores, paths, budget, noops, all")),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected from CWD; required when multiple repos are scanned)")),
			), s.handleScratchpadValidate},
			{mcp.NewTool("ralphglasses_scratchpad_context",
				mcp.WithDescription(descriptions.DescRalphglassesScratchpadContext),
				mcp.WithString("name", mcp.Required(), mcp.Description("Scratchpad name")),
				mcp.WithString("sections", mcp.Required(), mcp.Description("Comma-separated sections: fleet, observations, routing, autonomy, all")),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected from CWD; required when multiple repos are scanned)")),
			), s.handleScratchpadContext},
			{mcp.NewTool("ralphglasses_scratchpad_reason",
				mcp.WithDescription(descriptions.DescRalphglassesScratchpadReason),
				mcp.WithString("name", mcp.Required(), mcp.Description("Scratchpad name")),
				mcp.WithString("topic", mcp.Required(), mcp.Description("Reasoning topic: enhance_stages, rate_cards, prune_thresholds, provider_selection")),
				mcp.WithString("input", mcp.Description("JSON string with context data for the reasoning")),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected from CWD; required when multiple repos are scanned)")),
			), s.handleScratchpadReason},

			// Coverage report
			{mcp.NewTool("ralphglasses_coverage_report",
				mcp.WithDescription(descriptions.DescRalphglassesCoverageReport),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name or absolute path")),
				mcp.WithString("packages", mcp.Description("Package pattern (default ./...)")),
				mcp.WithNumber("threshold", mcp.Description("Coverage threshold percentage (default 70)")),
			), s.handleCoverageReport},

			// Cost estimation
			{mcp.NewTool("ralphglasses_cost_estimate",
				mcp.WithDescription(descriptions.DescRalphglassesCostEstimate),
				mcp.WithString("provider", mcp.Required(), mcp.Description("Provider: claude, gemini, or codex")),
				mcp.WithString("model", mcp.Description("Model name (uses provider default if omitted)")),
				mcp.WithNumber("prompt_tokens", mcp.Description("Prompt length in tokens (default 5000)")),
				mcp.WithNumber("turns", mcp.Description("Expected conversation turns (default 5)")),
				mcp.WithNumber("output_tokens_per_turn", mcp.Description("Output tokens per turn (default 2000)")),
				mcp.WithString("mode", mcp.Description("'session' or 'loop' (default session)")),
				mcp.WithNumber("iterations", mcp.Description("Loop iterations for mode=loop (default 3)")),
				mcp.WithString("repo", mcp.Description("Repo name for historical calibration")),
			), s.handleCostEstimate},

			// Merge verification
			{mcp.NewTool("ralphglasses_merge_verify",
				mcp.WithDescription(descriptions.DescRalphglassesMergeVerify),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo path (absolute)")),
				mcp.WithBoolean("fast", mcp.Description("Use -short flag for faster tests")),
				mcp.WithBoolean("coverage", mcp.Description("Include coverage profile")),
				mcp.WithString("packages", mcp.Description("Package pattern to test (default ./...)")),
				mcp.WithBoolean("race", mcp.Description("Enable -race detector (default true)")),
			), s.handleMergeVerify},

			// Observation correlation (link observations to git commits)
			{mcp.NewTool("ralphglasses_observation_correlate",
				mcp.WithDescription(descriptions.DescRalphglassesObservationCorrelate),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithNumber("hours", mcp.Description("Hours of history to correlate (default 24)")),
			), s.handleObservationCorrelate},
		},
	}
}
