package mcpserver

import (
	"github.com/hairglasses-studio/ralphglasses/internal/mcpserver/descriptions"
	"github.com/mark3labs/mcp-go/mcp"
)

func (s *Server) buildSessionGroup() ToolGroup {
	return ToolGroup{
		Name:        "session",
		Description: "LLM session lifecycle: launch, list, status, resume, stop, budget, retry, output, tail, diff, compare, errors, export",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_session_launch",
				mcp.WithDescription(descriptions.DescRalphglassesSessionLaunch),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("Prompt/task to send")),
				mcp.WithString("tenant_id", mcp.Description("Workspace tenant ID (default: _default)")),
				mcp.WithString("provider", mcp.Description("LLM provider: omit/auto for runtime selection, or codex, claude, gemini, antigravity. Antigravity opens an external interactive handoff instead of a managed streaming session.")),
				mcp.WithString("model", mcp.Description("Model to use")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget in USD — maximum spend for this session. Native for Claude; externally enforced by ralphglasses for Codex, Gemini, and Antigravity.")),
				mcp.WithNumber("max_turns", mcp.Description("Maximum conversation turns. Native for Claude only.")),
				mcp.WithString("agent", mcp.Description("Agent/subagent name. Native for Claude only.")),
				mcp.WithString("allowed_tools", mcp.Description("Comma-separated allowed tools (e.g. Bash,Read,Edit). Supported by Claude, and Gemini; unsupported by Codex and Antigravity.")),
				mcp.WithString("system_prompt", mcp.Description("Additional system prompt to append. Native for Claude only; use GEMINI.md or AGENTS.md plus .agents/rules/.agents/workflows for Gemini, Codex, and Antigravity repo instructions.")),
				mcp.WithString("session_name", mcp.Description("Human-readable session name")),
				mcp.WithString("worktree", mcp.Description("Git worktree isolation (true for auto, or branch name). Supported by Claude and Gemini; unsupported for Codex and Antigravity.")),
				mcp.WithString("no_journal", mcp.Description("Skip improvement journal injection: true/false (default: false)")),
				mcp.WithString("enhance_prompt", mcp.Description("Auto-enhance the prompt before launch: local (deterministic), llm (Claude API), auto (try LLM, fallback). Omit to skip enhancement")),
				mcp.WithString("target_provider", mcp.Description("Target LLM provider for prompt enhancement: claude, gemini, openai (defaults to the session provider lane)")),
				mcp.WithBoolean("bare", mcp.Description("Skip hooks/plugins for faster scripted startup")),
				mcp.WithString("effort", mcp.Description("Thinking effort level: low, medium, high, max")),
				mcp.WithString("fallback_model", mcp.Description("Auto-fallback model on overload")),
				mcp.WithString("output_schema", mcp.Description("JSON schema for structured output validation (Claude: --json-schema, Codex: --output-schema)")),
			), s.handleSessionLaunch},
			{mcp.NewTool("ralphglasses_session_list",
				mcp.WithDescription(descriptions.DescRalphglassesSessionList),
				mcp.WithString("repo", mcp.Description("Filter by repo name (omit for all)")),
				mcp.WithString("tenant_id", mcp.Description("Workspace tenant ID (default: _default)")),
				mcp.WithString("provider", mcp.Description("Filter by provider: claude, gemini, codex, antigravity (omit for all)")),
				mcp.WithString("status", mcp.Description("Filter by status: running, completed, errored, stopped")),
				mcp.WithBoolean("include_ended", mcp.Description("Include historical ended sessions from the persistent store when available")),
			), s.handleSessionList},
			{mcp.NewTool("ralphglasses_session_status",
				mcp.WithDescription(descriptions.DescRalphglassesSessionStatus),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID")),
				mcp.WithString("tenant_id", mcp.Description("Workspace tenant ID (default: _default)")),
			), s.handleSessionStatus},
			{mcp.NewTool("ralphglasses_session_resume",
				mcp.WithDescription(descriptions.DescRalphglassesSessionResume),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("tenant_id", mcp.Description("Workspace tenant ID (default: _default)")),
				mcp.WithString("session_id", mcp.Required(), mcp.Description("Provider session ID to resume (from session status)")),
				mcp.WithString("provider", mcp.Description("LLM provider: omit/auto for runtime selection, or codex, claude, gemini. Antigravity is launch-only and cannot be resumed through ralphglasses.")),
				mcp.WithString("prompt", mcp.Description("Follow-up prompt (optional)")),
			), s.handleSessionResume},
			{mcp.NewTool("ralphglasses_session_stop",
				mcp.WithDescription(descriptions.DescRalphglassesSessionStop),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID to stop")),
				mcp.WithString("tenant_id", mcp.Description("Workspace tenant ID (default: _default)")),
			), s.handleSessionStop},
			{mcp.NewTool("ralphglasses_session_stop_all",
				mcp.WithDescription(descriptions.DescRalphglassesSessionStopAll),
				mcp.WithString("tenant_id", mcp.Description("Workspace tenant ID (default: _default)")),
			), s.handleSessionStopAll},
			{mcp.NewTool("ralphglasses_session_budget",
				mcp.WithDescription(descriptions.DescRalphglassesSessionBudget),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID")),
				mcp.WithString("tenant_id", mcp.Description("Workspace tenant ID (default: _default)")),
				mcp.WithString("action", mcp.Description("Action: get (default), set, or reset_spend")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget in USD — new budget to set (omit to just query)")),
			), s.handleSessionBudget},
			{mcp.NewTool("ralphglasses_budget_status",
				mcp.WithDescription(descriptions.DescRalphglassesBudgetStatus),
				mcp.WithString("tenant_id", mcp.Description("Workspace tenant ID (default: _default)")),
			), s.handleBudgetStatus},
			{mcp.NewTool("ralphglasses_session_retry",
				mcp.WithDescription(descriptions.DescRalphglassesSessionRetry),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID to retry")),
				mcp.WithString("tenant_id", mcp.Description("Workspace tenant ID (default: _default)")),
				mcp.WithString("model", mcp.Description("Override model")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget in USD — override budget for retry")),
			), s.handleSessionRetry},
			{mcp.NewTool("ralphglasses_session_output",
				mcp.WithDescription(descriptions.DescRalphglassesSessionOutput),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID")),
				mcp.WithString("tenant_id", mcp.Description("Workspace tenant ID (default: _default)")),
				mcp.WithNumber("lines", mcp.Description("Number of lines to return (default 20, max 100)")),
			), s.handleSessionOutput},
			{mcp.NewTool("ralphglasses_session_tail",
				mcp.WithDescription(descriptions.DescRalphglassesSessionTail),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID")),
				mcp.WithString("tenant_id", mcp.Description("Workspace tenant ID (default: _default)")),
				mcp.WithString("cursor", mcp.Description("Cursor from previous response (omit for latest)")),
				mcp.WithNumber("lines", mcp.Description("Max lines to return (default 30, max 100)")),
			), s.handleSessionTail},
			{mcp.NewTool("ralphglasses_session_diff",
				mcp.WithDescription(descriptions.DescRalphglassesSessionDiff),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID")),
				mcp.WithString("tenant_id", mcp.Description("Workspace tenant ID (default: _default)")),
				mcp.WithString("stat_only", mcp.Description("true/false (default: true)")),
				mcp.WithNumber("max_lines", mcp.Description("Truncate diff at N lines (default 200)")),
			), s.handleSessionDiff},
			{mcp.NewTool("ralphglasses_session_compare",
				mcp.WithDescription(descriptions.DescRalphglassesSessionCompare),
				mcp.WithString("id1", mcp.Required(), mcp.Description("First session ID")),
				mcp.WithString("id2", mcp.Required(), mcp.Description("Second session ID")),
				mcp.WithString("tenant_id", mcp.Description("Workspace tenant ID (default: _default)")),
			), s.handleSessionCompare},
			{mcp.NewTool("ralphglasses_session_replay_diff",
				mcp.WithDescription(descriptions.DescRalphglassesSessionReplayDiff),
				mcp.WithString("path_a", mcp.Required(), mcp.Description("Path to first JSONL replay file")),
				mcp.WithString("path_b", mcp.Required(), mcp.Description("Path to second JSONL replay file")),
				mcp.WithNumber("max_events", mcp.Description("Max events in response (default 100)")),
			), s.handleSessionReplayDiff},
			{mcp.NewTool("ralphglasses_session_errors",
				mcp.WithDescription(descriptions.DescRalphglassesSessionErrors),
				mcp.WithString("repo", mcp.Description("Filter by repo name")),
				mcp.WithString("tenant_id", mcp.Description("Workspace tenant ID (default: _default)")),
				mcp.WithString("severity", mcp.Description("Filter: critical, warning, info")),
				mcp.WithNumber("limit", mcp.Description("Max errors (default 50)")),
			), s.handleSessionErrors},
			{mcp.NewTool("ralphglasses_session_export",
				mcp.WithDescription(descriptions.DescRalphglassesSessionExport),
				mcp.WithString("session_id", mcp.Required(), mcp.Description("Session ID whose replay to export")),
				mcp.WithString("format", mcp.Description("Export format: markdown (default) or json")),
				mcp.WithString("repo", mcp.Description("Repo name hint for locating replay file")),
				mcp.WithString("event_types", mcp.Description("Comma-separated event types to include: input, output, tool, status (default: all)")),
				mcp.WithString("after", mcp.Description("Only include events after this RFC3339 timestamp")),
				mcp.WithString("before", mcp.Description("Only include events before this RFC3339 timestamp")),
			), s.handleSessionExport},
			{mcp.NewTool("ralphglasses_session_fork",
				mcp.WithDescription(descriptions.DescRalphglassesSessionFork),
				mcp.WithString("id", mcp.Required(), mcp.Description("Parent session ID to fork from")),
				mcp.WithString("prompt", mcp.Description("New prompt for the forked session (inherits parent prompt if omitted)")),
				mcp.WithString("model", mcp.Description("Override model for the fork (inherits parent model if omitted)")),
				mcp.WithString("provider", mcp.Description("Override provider for the fork (inherits parent provider if omitted)")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget override in USD (inherits parent budget if omitted)")),
				mcp.WithBoolean("inject_context", mcp.Description("Include parent session output history in fork prompt (default: true)")),
			), s.handleSessionFork},
			{mcp.NewTool("ralphglasses_session_handoff",
				mcp.WithDescription(descriptions.DescRalphglassesSessionHandoff),
				mcp.WithString("source_session_id", mcp.Required(), mcp.Description("Session ID to transfer from")),
				mcp.WithString("target_provider", mcp.Description("Target provider: omit/auto for runtime selection, or claude, gemini, codex, antigravity (default: same as source)")),
				mcp.WithBoolean("include_context", mcp.Description("Include observation context in handoff (default: true)")),
				mcp.WithBoolean("stop_source", mcp.Description("Stop the source session after handoff (default: false)")),
				mcp.WithNumber("context_lines", mcp.Description("Number of recent observations to include (default: 5)")),
				mcp.WithString("handoff_reason", mcp.Description("Reason for handoff (tracked in handoff record)")),
			), s.handleSessionHandoff},
			{mcp.NewTool("ralphglasses_error_context",
				mcp.WithDescription(descriptions.DescRalphglassesErrorContext),
				mcp.WithString("session_id", mcp.Required(), mcp.Description("Session ID")),
			), s.handleErrorContext},
		},
	}
}

func (s *Server) buildLoopGroup() ToolGroup {
	return ToolGroup{
		Name:        "loop",
		Description: "Perpetual development loops: start, status, step, stop, benchmark, baseline, gates, self-test, self-improve",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_loop_start",
				mcp.WithDescription(descriptions.DescRalphglassesLoopStart),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("planner_model", mcp.Description("Planner model (default: gpt-5.4)")),
				mcp.WithString("worker_model", mcp.Description("Worker model (default: gpt-5.4)")),
				mcp.WithString("verifier_model", mcp.Description("Verifier model metadata (default: gpt-5.4)")),
				mcp.WithString("planner_provider", mcp.Description("Planner provider: claude, gemini, codex (default: codex)")),
				mcp.WithString("worker_provider", mcp.Description("Worker provider: claude, gemini, codex (default: codex)")),
				mcp.WithString("verifier_provider", mcp.Description("Verifier provider: claude, gemini, codex (default: codex)")),
				mcp.WithString("verify_commands", mcp.Description("SECURITY: Privileged input. Newline-separated bash commands (default: ./scripts/dev/ci.sh)")),
				mcp.WithNumber("retry_limit", mcp.Description("Maximum consecutive failed iterations before step is refused")),
				mcp.WithNumber("max_concurrent_workers", mcp.Description("Maximum concurrent workers (currently only 1 supported)")),
				mcp.WithString("worktree_policy", mcp.Description("Worktree isolation policy (default: git)")),
				mcp.WithBoolean("enable_reflexion", mcp.Description("Enable reflexion loop (failure correction injection)")),
				mcp.WithBoolean("enable_episodic_memory", mcp.Description("Enable episodic memory (successful trajectory recall)")),
				mcp.WithBoolean("enable_cascade", mcp.Description("Enable cascade routing (cheap-then-expensive provider)")),
				mcp.WithBoolean("enable_uncertainty", mcp.Description("Enable uncertainty quantification (confidence scoring)")),
				mcp.WithBoolean("enable_curriculum", mcp.Description("Enable curriculum learning (difficulty-based task sorting)")),
				mcp.WithBoolean("self_improvement", mcp.Description("Enable self-improvement mode with autonomous acceptance gate")),
				mcp.WithNumber("max_iterations", mcp.Description("Maximum loop iterations (0 = unlimited)")),
				mcp.WithNumber("duration_hours", mcp.Description("Maximum loop duration in hours (0 = unlimited)")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget in USD — total budget split 1/3 planner, 2/3 worker")),
				mcp.WithString("trace_level", mcp.Description("Trace verbosity: none, summary (default), verbose")),
			), s.handleLoopStart},
			{mcp.NewTool("ralphglasses_loop_status",
				mcp.WithDescription(descriptions.DescRalphglassesLoopStatus),
				mcp.WithString("id", mcp.Required(), mcp.Description("Loop run ID")),
			), s.handleLoopStatus},
			{mcp.NewTool("ralphglasses_loop_step",
				mcp.WithDescription(descriptions.DescRalphglassesLoopStep),
				mcp.WithString("id", mcp.Required(), mcp.Description("Loop run ID")),
			), s.handleLoopStep},
			{mcp.NewTool("ralphglasses_loop_stop",
				mcp.WithDescription(descriptions.DescRalphglassesLoopStop),
				mcp.WithString("id", mcp.Required(), mcp.Description("Loop run ID")),
			), s.handleLoopStop},
			{mcp.NewTool("ralphglasses_loop_benchmark",
				mcp.WithDescription(descriptions.DescRalphglassesLoopBenchmark),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Look-back window in hours (default: 48)")),
			), s.handleLoopBenchmark},
			{mcp.NewTool("ralphglasses_loop_baseline",
				mcp.WithDescription(descriptions.DescRalphglassesLoopBaseline),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("action", mcp.Description("Action: view (default), refresh, or pin")),
				mcp.WithNumber("hours", mcp.Description("Window for refresh/pin in hours (default: 48)")),
			), s.handleLoopBaseline},
			{mcp.NewTool("ralphglasses_loop_gates",
				mcp.WithDescription(descriptions.DescRalphglassesLoopGates),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Look-back window in hours (default: 24)")),
				mcp.WithString("baseline_path", mcp.Description("Optional absolute path to a baseline JSON file")),
			), s.handleLoopGates},
			{mcp.NewTool("ralphglasses_self_test",
				mcp.WithDescription(descriptions.DescRalphglassesSelfTest),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Absolute path to the repository to test")),
				mcp.WithNumber("iterations", mcp.Description("Number of self-test iterations (default: 3)")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget in USD (default: 5.0)")),
				mcp.WithBoolean("use_snapshot", mcp.Description("Restore repo snapshot between iterations (default: true)")),
				mcp.WithBoolean("dry_run", mcp.Description("Validate config without running iterations (default: false)")),
			), s.handleSelfTest},
			{mcp.NewTool("ralphglasses_self_improve",
				mcp.WithDescription(descriptions.DescRalphglassesSelfImprove),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("max_iterations", mcp.Description("Maximum iterations (default: 5)")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget in USD (default: 20.0, split 1/4 planner + 3/4 worker)")),
				mcp.WithNumber("duration_hours", mcp.Description("Maximum duration in hours (default: 4)")),
				mcp.WithString("planner_provider", mcp.Description("Planner provider (claude, gemini, codex)")),
				mcp.WithString("worker_provider", mcp.Description("Worker provider (claude, gemini, codex)")),
				mcp.WithString("trace_level", mcp.Description("Trace verbosity: none, summary (default), verbose")),
			), s.handleSelfImprove},
			{mcp.NewTool("ralphglasses_loop_prune",
				mcp.WithDescription(descriptions.DescRalphglassesLoopPrune),
				mcp.WithNumber("older_than_hours", mcp.Description("Only prune loop runs older than this many hours (default: 72)")),
				mcp.WithString("statuses", mcp.Description("Comma-separated statuses to prune (default: pending,failed)")),
				mcp.WithBoolean("dry_run", mcp.Description("If true, return count without deleting (default: true)")),
				mcp.WithString("repo", mcp.Description("Optional repo name filter — only prune runs for this repo")),
			), s.handleLoopPrune},
			{mcp.NewTool("ralphglasses_loop_await",
				mcp.WithDescription(descriptions.DescRalphglassesLoopAwait),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session or loop ID to wait for")),
				mcp.WithString("type", mcp.Required(), mcp.Description("'session' or 'loop'")),
				mcp.WithNumber("timeout_seconds", mcp.Description("Max wait time in seconds (default 300)")),
				mcp.WithNumber("poll_interval_seconds", mcp.Description("Poll interval in seconds (default 10, min 5)")),
			), s.handleLoopAwait},
			{mcp.NewTool("ralphglasses_loop_poll",
				mcp.WithDescription(descriptions.DescRalphglassesLoopPoll),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session or loop ID")),
				mcp.WithString("type", mcp.Required(), mcp.Description("'session' or 'loop'")),
			), s.handleLoopPoll},
		},
	}
}

func (s *Server) buildPromptGroup() ToolGroup {
	return ToolGroup{
		Name:        "prompt",
		Description: "Prompt enhancement: analyze, enhance, lint, improve, classify, should_enhance, templates, template_fill",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_prompt_analyze",
				mcp.WithDescription(descriptions.DescRalphglassesPromptAnalyze),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("The prompt text to analyze")),
				mcp.WithString("task_type", mcp.Description("Override auto-detection: code, troubleshooting, analysis, creative, workflow, general")),
				mcp.WithString("target_provider", mcp.Description("Target model provider for scoring suggestions: openai (default openai-style), claude, gemini")),
			), s.handlePromptAnalyze},
			{mcp.NewTool("ralphglasses_prompt_enhance",
				mcp.WithDescription(descriptions.DescRalphglassesPromptEnhance),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("The prompt text to enhance")),
				mcp.WithString("task_type", mcp.Description("Override auto-detection: code, troubleshooting, analysis, creative, workflow, general")),
				mcp.WithString("mode", mcp.Description("Enhancement mode: local (default, deterministic), llm (Claude/Gemini/OpenAI), auto (try LLM, fallback to local)")),
				mcp.WithString("repo", mcp.Description("Repo name to load .prompt-improver.yaml config from")),
				mcp.WithString("target_provider", mcp.Description("Target model provider — controls structure style and scoring: openai (default openai-style), claude, gemini")),
				mcp.WithString("trace_level", mcp.Description("Trace verbosity: none, summary (default), verbose")),
			), s.handlePromptEnhance},
			{mcp.NewTool("ralphglasses_prompt_lint",
				mcp.WithDescription(descriptions.DescRalphglassesPromptLint),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("The prompt text to lint")),
			), s.handlePromptLint},
			{mcp.NewTool("ralphglasses_prompt_improve",
				mcp.WithDescription(descriptions.DescRalphglassesPromptImprove),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("The prompt text to improve")),
				mcp.WithString("task_type", mcp.Description("Override auto-detection: code, troubleshooting, analysis, creative, workflow, general")),
				mcp.WithBoolean("thinking_enabled", mcp.Description("Include thinking scaffolding in the improved prompt")),
				mcp.WithString("feedback", mcp.Description("Optional feedback to guide the improvement direction")),
				mcp.WithString("provider", mcp.Description("LLM provider for improvement: openai (default) (local OpenAI-compatible lane), claude, gemini")),
			), s.handlePromptImprove},
			{mcp.NewTool("ralphglasses_prompt_classify",
				mcp.WithDescription(descriptions.DescRalphglassesPromptClassify),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("The prompt text to classify")),
			), s.handlePromptClassify},
			{mcp.NewTool("ralphglasses_prompt_should_enhance",
				mcp.WithDescription(descriptions.DescRalphglassesPromptShouldEnhance),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("The prompt text to check")),
				mcp.WithString("repo", mcp.Description("Repo name for loading .prompt-improver.yaml config")),
			), s.handlePromptShouldEnhance},
			{mcp.NewTool("ralphglasses_prompt_templates",
				mcp.WithDescription(descriptions.DescRalphglassesPromptTemplates),
			), s.handlePromptTemplates},
			{mcp.NewTool("ralphglasses_prompt_template_fill",
				mcp.WithDescription(descriptions.DescRalphglassesPromptTemplateFill),
				mcp.WithString("name", mcp.Required(), mcp.Description("Template name")),
				mcp.WithString("vars", mcp.Required(), mcp.Description("JSON object of variable key-value pairs")),
			), s.handlePromptTemplateFill},
			{mcp.NewTool("ralphglasses_prompt_ab_test",
				mcp.WithDescription(descriptions.DescRalphglassesPromptAbTest),
				mcp.WithString("prompt_a", mcp.Required(), mcp.Description("First prompt to compare")),
				mcp.WithString("prompt_b", mcp.Required(), mcp.Description("Second prompt to compare")),
				mcp.WithString("target_provider", mcp.Description("Target provider for scoring: openai (default openai-style), claude, gemini")),
				mcp.WithString("repo", mcp.Description("Repo name for result storage")),
			), s.handlePromptABTest},
		},
	}
}
