package mcpserver

import (
	"github.com/hairglasses-studio/ralphglasses/internal/mcpserver/descriptions"
	"github.com/mark3labs/mcp-go/mcp"
)

func (s *Server) buildSweepGroup() ToolGroup {
	return ToolGroup{
		Name:        "sweep",
		Description: "Cross-repo audit sweeps: generate optimized prompts, fan-out sessions, monitor, nudge stalled sessions, schedule recurring checks",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_sweep_generate",
				mcp.WithDescription(descriptions.DescRalphglassesSweepGenerate),
				mcp.WithString("task_type", mcp.Description("Task type for prompt template: audit (default), fix, review, improve")),
				mcp.WithString("target_provider", mcp.Description("Target model provider for structure style: openai or ollama (default openai-style), claude, gemini")),
				mcp.WithString("custom_prompt", mcp.Description("Custom base prompt instead of built-in template. Will be enhanced through the pipeline.")),
			), s.handleSweepGenerate},
			{mcp.NewTool("ralphglasses_sweep_launch",
				mcp.WithDescription(descriptions.DescRalphglassesSweepLaunch),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("The prompt to run (use sweep_generate output or provide your own). Use REPO_PLACEHOLDER for repo name substitution.")),
				mcp.WithString("repos", mcp.Description("JSON array of repo names, or \"active\" for recently-active repos, or \"all\". Default: active")),
				mcp.WithNumber("limit", mcp.Description("Max repos to launch against (default 10)")),
				mcp.WithString("provider", mcp.Description("LLM provider for each repo session: omit/auto for runtime selection, or codex, claude, gemini, ollama")),
				mcp.WithString("model", mcp.Description("Optional model override. Leave empty to use the selected provider default or runtime-selected lane. Examples: gpt-5.4, claude-sonnet-4-6, gemini-3.1-flash, code-primary")),
				mcp.WithString("permission_mode", mcp.Description("Permission mode passed through when the selected provider supports it: plan (default, read-only), auto, default")),
				mcp.WithString("enhance_prompt", mcp.Description("Enhance each repo's prompt before launch: local (default), llm, auto, none")),
				mcp.WithNumber("budget_usd", mcp.Description("Per-session budget in USD (default: 0.5, auto-sized upward when omitted and estimates require more headroom)")),
				mcp.WithString("effort", mcp.Description("Effort level: low, medium, high, max")),
				mcp.WithString("allowed_tools", mcp.Description("Comma-separated allowed tools (default: read-only tools for plan mode)")),
				mcp.WithNumber("max_sweep_budget_usd", mcp.Description("Total sweep budget cap in USD (default 100). Rejects launch if estimated cost exceeds this.")),
				mcp.WithNumber("max_turns", mcp.Description("Max turns per session (default 50). Prevents runaway sessions.")),
				mcp.WithBoolean("session_persistence", mcp.Description("Persist session history to disk (default false for sweeps).")),
				mcp.WithNumber("sweep_concurrency", mcp.Description("Max simultaneous session launches (default 10). Use 1 for serial, higher for large idle machines.")),
			), s.handleSweepLaunch},
			{mcp.NewTool("ralphglasses_sweep_status",
				mcp.WithDescription(descriptions.DescRalphglassesSweepStatus),
				mcp.WithString("sweep_id", mcp.Required(), mcp.Description("Sweep ID returned by sweep_launch")),
				mcp.WithBoolean("verbose", mcp.Description("Include last output lines per session (default false)")),
			), s.handleSweepStatus},
			{mcp.NewTool("ralphglasses_sweep_nudge",
				mcp.WithDescription(descriptions.DescRalphglassesSweepNudge),
				mcp.WithString("sweep_id", mcp.Required(), mcp.Description("Sweep ID to nudge")),
				mcp.WithNumber("stale_threshold_min", mcp.Description("Minutes idle before a session is considered stalled (default 5)")),
				mcp.WithString("action", mcp.Description("Action for stalled sessions: restart (default), skip")),
			), s.handleSweepNudge},
			{mcp.NewTool("ralphglasses_sweep_schedule",
				mcp.WithDescription(descriptions.DescRalphglassesSweepSchedule),
				mcp.WithString("sweep_id", mcp.Required(), mcp.Description("Sweep ID to monitor")),
				mcp.WithNumber("interval_minutes", mcp.Description("Check interval in minutes (default 5)")),
				mcp.WithBoolean("auto_nudge", mcp.Description("Automatically restart stalled sessions (default false)")),
				mcp.WithNumber("max_checks", mcp.Description("Stop after N checks, 0 for unlimited (default 0)")),
				mcp.WithNumber("max_sweep_budget_usd", mcp.Description("Abort sweep and stop all sessions if total spend exceeds this (default 0 = no cap)")),
			), s.handleSweepSchedule},
			{mcp.NewTool("ralphglasses_sweep_report",
				mcp.WithDescription(descriptions.DescRalphglassesSweepReport),
				mcp.WithString("sweep_id", mcp.Required(), mcp.Description("Sweep ID to report on")),
				mcp.WithString("format", mcp.Description("Output format: markdown (default), json")),
			), s.handleSweepReport},
			{mcp.NewTool("ralphglasses_sweep_retry",
				mcp.WithDescription(descriptions.DescRalphglassesSweepRetry),
				mcp.WithString("sweep_id", mcp.Required(), mcp.Description("Sweep ID to retry")),
				mcp.WithNumber("budget_usd", mcp.Description("Override per-session budget for retry (default: use original)")),
			), s.handleSweepRetry},
			{mcp.NewTool("ralphglasses_sweep_push",
				mcp.WithDescription(descriptions.DescRalphglassesSweepPush),
				mcp.WithString("sweep_id", mcp.Required(), mcp.Description("Sweep ID whose repos to push")),
				mcp.WithBoolean("dry_run", mcp.Description("Show what would be pushed without pushing (default false)")),
			), s.handleSweepPush},
		},
	}
}
