// Code generated by gen-tool-counts; DO NOT EDIT.
package mcpserver

// GeneratedToolCounts maps each tool group name to its current tool count.
// Re-generate with: go generate ./internal/mcpserver/...
var GeneratedToolCounts = map[string]int{
	"core": 13,
	"session": 18,
	"loop": 12,
	"prompt": 9,
	"fleet": 10,
	"repo": 7,
	"roadmap": 6,
	"team": 6,
	"awesome": 5,
	"advanced": 5,
	"events": 2,
	"feedback": 4,
	"eval": 7,
	"fleet_h": 5,
	"observability": 14,
	"rdcycle": 16,
	"plugin": 4,
	"sweep": 8,
	"rc": 6,
	"autonomy": 6,
	"workflow": 3,
	"docs": 8,
	"recovery": 6,
	"promptdj": 6,
	"a2a": 4,
	"trigger": 2,
	"approval": 3,
	"context": 1,
	"prefetch": 1,
}

// GeneratedTotalTools is the sum of all tool counts across all groups.
var GeneratedTotalTools = 197
