package mcpserver

import (
	"github.com/hairglasses-studio/ralphglasses/internal/mcpserver/descriptions"
	"github.com/mark3labs/mcp-go/mcp"
)

func (s *Server) buildFleetGroup() ToolGroup {
	return ToolGroup{
		Name:        "fleet",
		Description: "Fleet operations: fleet_status, analytics, submit, budget, workers, dlq, marathon_dashboard, capacity_plan",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_fleet_status",
				mcp.WithDescription(descriptions.DescRalphglassesFleetStatus),
				mcp.WithNumber("limit", mcp.Description("Max repos to return in full mode (default 50)")),
				mcp.WithNumber("offset", mcp.Description("Pagination offset for repos (default 0)")),
				mcp.WithString("tenant_id", mcp.Description("Workspace tenant ID (default: _default)")),
				mcp.WithString("repo", mcp.Description("Filter to a specific repo name")),
				mcp.WithBoolean("summary_only", mcp.Description("Return compact JSON with just repo names, session counts, and total spend instead of full dump")),
			), s.handleFleetStatus},
			{mcp.NewTool("ralphglasses_fleet_analytics",
				mcp.WithDescription(descriptions.DescRalphglassesFleetAnalytics),
				mcp.WithString("repo", mcp.Description("Filter by repo name")),
				mcp.WithString("provider", mcp.Description("Filter by provider")),
				mcp.WithString("window", mcp.Description("Time window as Go duration (e.g. '1h', '24h'). Default: 1h")),
			), s.handleFleetAnalytics},
			{mcp.NewTool("ralphglasses_fleet_submit",
				mcp.WithDescription(descriptions.DescRalphglassesFleetSubmit),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("Task prompt")),
				mcp.WithString("provider", mcp.Description("codex (default), claude, gemini")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget in USD (default: 5.0)")),
				mcp.WithNumber("priority", mcp.Description("Priority 0-10 (default: 5, higher = first)")),
			), s.handleFleetSubmit},
			{mcp.NewTool("ralphglasses_fleet_budget",
				mcp.WithDescription(descriptions.DescRalphglassesFleetBudget),
				mcp.WithNumber("limit", mcp.Description("New budget limit in USD (omit to just view current budget)")),
			), s.handleFleetBudget},
			{mcp.NewTool("ralphglasses_fleet_workers",
				mcp.WithDescription(descriptions.DescRalphglassesFleetWorkers),
				mcp.WithString("action", mcp.Description("Worker action: pause, resume, or drain (omit to list)")),
				mcp.WithString("worker_id", mcp.Description("Worker ID (required for pause/resume/drain actions)")),
			), s.handleFleetWorkers},
			{mcp.NewTool("ralphglasses_fleet_dlq",
				mcp.WithDescription(descriptions.DescRalphglassesFleetDlq),
				mcp.WithString("action", mcp.Description("Action: list (default), retry, purge, depth")),
				mcp.WithString("item_id", mcp.Description("Work item ID (required for retry action)")),
			), s.handleFleetDLQ},
			{mcp.NewTool("ralphglasses_fleet_schedule",
				mcp.WithDescription(descriptions.DescRalphglassesFleetSchedule),
				mcp.WithString("tasks", mcp.Required(), mcp.Description("JSON array of task objects: [{\"id\": \"build\", \"name\": \"Build\", \"dependencies\": [\"lint\"], \"priority\": 5}, ...]")),
			), s.handleFleetSchedule},
			{mcp.NewTool("ralphglasses_marathon_dashboard",
				mcp.WithDescription(descriptions.DescRalphglassesMarathonDashboard),
				mcp.WithNumber("stale_threshold_min", mcp.Description("Minutes idle before flagged stale (default 5)")),
			), s.handleMarathonDashboard},
			{mcp.NewTool("ralphglasses_fleet_runtime",
				mcp.WithDescription(descriptions.DescRalphglassesFleetRuntime),
				mcp.WithString("action", mcp.Description("Action: status (default), discover, start, stop, or restart")),
				mcp.WithString("mode", mcp.Description("Runtime mode: coordinator or worker (default: worker for start/restart)")),
				mcp.WithNumber("port", mcp.Description("Fleet port (default: 9473)")),
				mcp.WithString("coordinator_url", mcp.Description("Coordinator URL for worker mode")),
				mcp.WithNumber("fleet_budget", mcp.Description("Fleet-wide budget ceiling in USD (coordinator mode only)")),
				mcp.WithBoolean("automation", mcp.Description("Run repo-local automation supervisors alongside the runtime (default: true)")),
			), s.handleFleetRuntime},
			{mcp.NewTool("ralphglasses_marathon",
				mcp.WithDescription(descriptions.DescRalphglassesMarathon),
				mcp.WithString("action", mcp.Description("Action: status (default), start, resume, or stop")),
				mcp.WithString("repo", mcp.Description("Target repo name")),
				mcp.WithNumber("budget_usd", mcp.Description("Maximum budget in USD (default: 10.0)")),
				mcp.WithString("duration", mcp.Description("Maximum duration (default: 1h)")),
				mcp.WithString("checkpoint_interval", mcp.Description("Checkpoint interval (default: 10m)")),
			), s.handleMarathon},
			{mcp.NewTool("ralphglasses_fleet_capacity_plan",
				mcp.WithDescription(descriptions.DescRalphglassesFleetCapacityPlan),
				mcp.WithNumber("queue_depth", mcp.Required(), mcp.Description("Number of tasks in the queue")),
				mcp.WithNumber("available_budget", mcp.Required(), mcp.Description("Available budget in USD")),
				mcp.WithNumber("target_completion_hours", mcp.Description("Target completion time in hours (default: 4)")),
				mcp.WithNumber("avg_task_cost", mcp.Description("Average cost per task in USD (auto-estimated from observations if omitted)")),
				mcp.WithNumber("avg_task_duration_min", mcp.Description("Average task duration in minutes (default: 10)")),
				mcp.WithNumber("utilization_factor", mcp.Description("Worker efficiency factor 0.1-1.0 (default: 0.8 — workers aren't 100% productive)")),
			), s.handleFleetCapacityPlan},
			{mcp.NewTool("ralphglasses_fleet_grafana",
				mcp.WithDescription(descriptions.DescRalphglassesFleetGrafana),
				mcp.WithString("title", mcp.Description("Dashboard title (default: 'Ralphglasses Fleet Metrics')")),
				mcp.WithString("metrics", mcp.Description("Comma-separated metric names to include: session_throughput, cost_burn_rate, provider_comparison, error_rate, active_sessions, budget_utilization. Default: all")),
				mcp.WithString("datasource", mcp.Description("Prometheus data source name/UID (default: 'prometheus')")),
			), s.handleFleetGrafana},
		},
	}
}

func (s *Server) buildFleetHGroup() ToolGroup {
	return ToolGroup{
		Name:        "fleet_h",
		Description: "Fleet intelligence: blackboard coordination, A2A task delegation, cost forecasting, cost recommendations",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_blackboard_query",
				mcp.WithDescription(descriptions.DescRalphglassesBlackboardQuery),
				mcp.WithString("namespace", mcp.Required(), mcp.Description("Namespace to query")),
			), s.handleBlackboardQuery},
			{mcp.NewTool("ralphglasses_blackboard_put",
				mcp.WithDescription(descriptions.DescRalphglassesBlackboardPut),
				mcp.WithString("namespace", mcp.Required(), mcp.Description("Entry namespace")),
				mcp.WithString("key", mcp.Required(), mcp.Description("Entry key")),
				mcp.WithString("value", mcp.Required(), mcp.Description("JSON object value")),
				mcp.WithString("writer_id", mcp.Description("Writer identifier")),
				mcp.WithNumber("ttl_seconds", mcp.Description("Time-to-live in seconds (0 for no expiry)")),
			), s.handleBlackboardPut},
			{mcp.NewTool("ralphglasses_a2a_offers",
				mcp.WithDescription(descriptions.DescRalphglassesA2aOffers),
			), s.handleA2AOffers},
			{mcp.NewTool("ralphglasses_cost_forecast",
				mcp.WithDescription(descriptions.DescRalphglassesCostForecast),
				mcp.WithNumber("budget_remaining", mcp.Description("Remaining budget in USD for exhaustion ETA (default: 0)")),
			), s.handleCostForecast},
			{mcp.NewTool("ralphglasses_cost_recommend",
				mcp.WithDescription(descriptions.DescRalphglassesCostRecommend),
				mcp.WithNumber("budget_remaining", mcp.Description("Remaining budget in USD for pacing recommendations")),
				mcp.WithNumber("concurrency", mcp.Description("Current session concurrency for pacing recommendations")),
				mcp.WithNumber("budget_hours", mcp.Description("Desired budget runway in hours (default: 8)")),
				mcp.WithNumber("min_samples", mcp.Description("Minimum samples per provider for comparison (default: 5)")),
				mcp.WithString("type", mcp.Description("Filter by recommendation type: provider_switch, budget_pacing, anomaly_response, cache_optimize, model_downgrade")),
			), s.handleCostRecommend},
		},
	}
}

func (s *Server) buildRepoGroup() ToolGroup {
	return ToolGroup{
		Name:        "repo",
		Description: "Repo management: health, optimize, scaffold, claudemd_check, snapshot",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_repo_health",
				mcp.WithDescription(descriptions.DescRalphglassesRepoHealth),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
			), s.handleRepoHealth},
			{mcp.NewTool("ralphglasses_repo_optimize",
				mcp.WithDescription(descriptions.DescRalphglassesRepoOptimize),
				mcp.WithString("path", mcp.Required(), mcp.Description("Repo root path")),
				mcp.WithString("focus", mcp.Description("Focus area: config, prompt, plan, all (default: all)")),
				mcp.WithString("dry_run", mcp.Description("Report only, don't modify: true/false (default: true)")),
			), s.handleRepoOptimize},
			{mcp.NewTool("ralphglasses_repo_scaffold",
				mcp.WithDescription(descriptions.DescRalphglassesRepoScaffold),
				mcp.WithString("path", mcp.Required(), mcp.Description("Repo root path")),
				mcp.WithString("project_type", mcp.Description("Project type override (auto-detected from go.mod, package.json, etc.)")),
				mcp.WithString("project_name", mcp.Description("Project name override (defaults to directory name)")),
				mcp.WithString("force", mcp.Description("Overwrite existing files: true/false (default: false)")),
				mcp.WithBoolean("minimal", mcp.Description("Generate the minimal .ralphrc variant")),
			), s.handleRepoScaffold},
			{mcp.NewTool("ralphglasses_repo_surface_audit",
				mcp.WithDescription(descriptions.DescRalphglassesRepoSurfaceAudit),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
			), s.handleRepoSurfaceAudit},
			{mcp.NewTool("ralphglasses_surface_audit",
				mcp.WithDescription("Run the surfacekit workspace parity audit and return the JSON inventory snapshot"),
			), s.handleSurfaceAudit},
			{mcp.NewTool("ralphglasses_claudemd_check",
				mcp.WithDescription(descriptions.DescRalphglassesClaudemdCheck),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
			), s.handleClaudeMDCheck},
			{mcp.NewTool("ralphglasses_snapshot",
				mcp.WithDescription(descriptions.DescRalphglassesSnapshot),
				mcp.WithString("action", mcp.Description("Action: save (default) or list")),
				mcp.WithString("name", mcp.Description("Snapshot name (auto-generated if omitted)")),
				mcp.WithString("repo", mcp.Description("Target repo name for snapshot storage (resolved from CWD if omitted)")),
			), s.handleSnapshot},
			{mcp.NewTool("ralphglasses_worktree_create",
				mcp.WithDescription(descriptions.DescRalphglassesWorktreeCreate),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("name", mcp.Required(), mcp.Description("Worktree name (sanitized for filesystem)")),
			), s.handleWorktreeCreate},
			{mcp.NewTool("ralphglasses_worktree_list",
				mcp.WithDescription(descriptions.DescRalphglassesWorktreeList),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithBoolean("dirty_only", mcp.Description("Only include dirty worktrees")),
				mcp.WithBoolean("include_stale", mcp.Description("Annotate stale worktrees using stale_after_hours")),
				mcp.WithNumber("stale_after_hours", mcp.Description("Age threshold in hours for stale detection (default: 24)")),
			), s.handleWorktreeList},
			{mcp.NewTool("ralphglasses_worktree_cleanup",
				mcp.WithDescription(descriptions.DescRalphglassesWorktreeCleanup),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("max_age_hours", mcp.Description("Max age in hours before cleanup (default 24)")),
				mcp.WithBoolean("dry_run", mcp.Description("Preview stale worktrees without deleting them")),
			), s.handleWorktreeCleanup},
		},
	}
}
