package mcpserver

import (
	"github.com/mark3labs/mcp-go/mcp"
)

func (s *Server) buildRoadmapGroup() ToolGroup {
	return ToolGroup{
		Name:        "roadmap",
		Description: "Roadmap automation: parse, analyze, research, expand, export",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_roadmap_parse",
				mcp.WithDescription("Parse ROADMAP.md at `path` into structured JSON (phases, sections, tasks, deps, completion stats)"),
				mcp.WithString("path", mcp.Required(), mcp.Description("Repo root or direct .md path")),
				mcp.WithString("file", mcp.Description("Override filename (default: ROADMAP.md)")),
				mcp.WithString("phase", mcp.Description("Filter to a specific phase name")),
				mcp.WithBoolean("summary_only", mcp.Description("Return compact summary (phase counts, completion %) instead of full task details")),
				mcp.WithNumber("max_depth", mcp.Description("Depth of detail: 0=phases only, 1=phases+sections, 2=full (default 2)")),
			), s.handleRoadmapParse},
			{mcp.NewTool("ralphglasses_roadmap_analyze",
				mcp.WithDescription("Compare roadmap vs codebase at `path` — find gaps, stale checkboxes, ready tasks, orphaned code"),
				mcp.WithString("path", mcp.Required(), mcp.Description("Repo root path")),
				mcp.WithString("file", mcp.Description("Override filename (default: ROADMAP.md)")),
				mcp.WithString("category", mcp.Description("Filter by category: gaps, stale, orphaned, ready")),
				mcp.WithNumber("limit", mcp.Description("Max items per category (default 20)")),
			), s.handleRoadmapAnalyze},
			{mcp.NewTool("ralphglasses_roadmap_research",
				mcp.WithDescription("Search GitHub for relevant repos and tools at `path` that unlock new capabilities"),
				mcp.WithString("path", mcp.Required(), mcp.Description("Repo root path")),
				mcp.WithString("topics", mcp.Description("Search topics (inferred from go.mod/README if omitted)")),
				mcp.WithNumber("limit", mcp.Description("Max results (default 10)")),
			), s.handleRoadmapResearch},
			{mcp.NewTool("ralphglasses_roadmap_expand",
				mcp.WithDescription("Generate proposed roadmap expansions at `path` from analysis gaps and research findings"),
				mcp.WithString("path", mcp.Required(), mcp.Description("Repo root path")),
				mcp.WithString("file", mcp.Description("Override filename (default: ROADMAP.md)")),
				mcp.WithString("research", mcp.Description("Research topics to include (runs research internally)")),
				mcp.WithString("style", mcp.Description("Expansion style: conservative, balanced, aggressive (default: balanced)")),
				mcp.WithString("phase", mcp.Description("Filter proposals to a specific phase")),
				mcp.WithNumber("limit", mcp.Description("Max proposals to return (default 20)")),
			), s.handleRoadmapExpand},
			{mcp.NewTool("ralphglasses_roadmap_export",
				mcp.WithDescription("Export roadmap items at `path` as structured task specs for ralph loop consumption"),
				mcp.WithString("path", mcp.Required(), mcp.Description("Repo root path")),
				mcp.WithString("file", mcp.Description("Override filename (default: ROADMAP.md)")),
				mcp.WithString("format", mcp.Description("Output format: rdcycle, fix_plan, progress, launch_ready (default: rdcycle). launch_ready enriches tasks with difficulty_score, suggested_provider, estimated_budget_usd")),
				mcp.WithString("phase", mcp.Description("Filter by phase name (default: all)")),
				mcp.WithString("section", mcp.Description("Filter by section name (default: all)")),
				mcp.WithNumber("max_tasks", mcp.Description("Max tasks to export (default 20)")),
				mcp.WithString("respect_deps", mcp.Description("Skip tasks with unmet deps (default: true)")),
				mcp.WithString("status", mcp.Description("Filter by status: incomplete (default), complete, all")),
			), s.handleRoadmapExport},
		},
	}
}

func (s *Server) buildTeamGroup() ToolGroup {
	return ToolGroup{
		Name:        "team",
		Description: "Agent teams and definitions: team_create, team_status, team_delegate, agent_define, agent_list, agent_compose",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_team_create",
				mcp.WithDescription("Create an agent team by `name` for `repo` with a lead session that delegates tasks to teammates"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("name", mcp.Required(), mcp.Description("Team name")),
				mcp.WithString("tasks", mcp.Required(), mcp.Description("Newline-separated task descriptions")),
				mcp.WithString("provider", mcp.Description("LLM provider for lead: claude (default), gemini, codex")),
				mcp.WithString("worker_provider", mcp.Description("Default LLM provider for worker tasks: claude, gemini, codex")),
				mcp.WithString("lead_agent", mcp.Description("Agent definition for the lead (from .claude/agents/)")),
				mcp.WithString("model", mcp.Description("Model for lead session")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget in USD — total budget for the team")),
				mcp.WithBoolean("dry_run", mcp.Description("Return team configuration without launching sessions")),
			), s.handleTeamCreate},
			{mcp.NewTool("ralphglasses_team_status",
				mcp.WithDescription("Get team status including lead session, tasks, and progress"),
				mcp.WithString("name", mcp.Required(), mcp.Description("Team name")),
			), s.handleTeamStatus},
			{mcp.NewTool("ralphglasses_team_delegate",
				mcp.WithDescription("Add a new task to an existing team"),
				mcp.WithString("name", mcp.Required(), mcp.Description("Team name")),
				mcp.WithString("task", mcp.Required(), mcp.Description("Task description to delegate")),
				mcp.WithString("provider", mcp.Description("LLM provider override for this task: claude, gemini, codex")),
			), s.handleTeamDelegate},
			{mcp.NewTool("ralphglasses_agent_define",
				mcp.WithDescription("Create or update an agent definition for a repo (supports all providers)"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("name", mcp.Required(), mcp.Description("Agent name")),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("Agent system prompt / instructions (markdown)")),
				mcp.WithString("provider", mcp.Description("Target provider: claude (default, .claude/agents/), gemini (.gemini/agents/), codex (AGENTS.md)")),
				mcp.WithString("description", mcp.Description("Agent description")),
				mcp.WithString("model", mcp.Description("Model override (sonnet, opus, haiku)")),
				mcp.WithString("tools", mcp.Description("Comma-separated allowed tools")),
				mcp.WithNumber("max_turns", mcp.Description("Max turns for this agent")),
			), s.handleAgentDefine},
			{mcp.NewTool("ralphglasses_agent_list",
				mcp.WithDescription("List available agent definitions for a repo (supports all providers)"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("provider", mcp.Description("Filter by provider: claude (default), gemini, codex, or 'all'")),
			), s.handleAgentList},
			{mcp.NewTool("ralphglasses_agent_compose",
				mcp.WithDescription("Create a composite agent by layering multiple existing agent definitions"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("name", mcp.Required(), mcp.Description("Name for the composite agent")),
				mcp.WithString("agents", mcp.Required(), mcp.Description("Comma-separated agent names to compose")),
				mcp.WithString("provider", mcp.Description("Provider: claude (default), gemini, codex")),
				mcp.WithString("model", mcp.Description("Override model for composite agent")),
			), s.handleAgentCompose},
		},
	}
}

func (s *Server) buildAwesomeGroup() ToolGroup {
	return ToolGroup{
		Name:        "awesome",
		Description: "Awesome-list research: fetch, analyze, diff, report, sync",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_awesome_fetch",
				mcp.WithDescription("Fetch and parse an awesome-list README into structured entries with categories"),
				mcp.WithString("repo", mcp.Description("GitHub repo (default: hesreallyhim/awesome-claude-code)")),
			), s.handleAwesomeFetch},
			{mcp.NewTool("ralphglasses_awesome_analyze",
				mcp.WithDescription("Deep-analyze repos: fetch READMEs, score value/complexity vs ralph capabilities"),
				mcp.WithString("repo", mcp.Description("GitHub repo (default: hesreallyhim/awesome-claude-code)")),
				mcp.WithNumber("max_workers", mcp.Description("Concurrent README fetches (default 5)")),
			), s.handleAwesomeAnalyze},
			{mcp.NewTool("ralphglasses_awesome_diff",
				mcp.WithDescription("Compare current awesome-list against previous fetch (new/removed entries)"),
				mcp.WithString("save_to", mcp.Required(), mcp.Description("Repo path where previous index is saved")),
				mcp.WithString("repo", mcp.Description("GitHub repo (default: hesreallyhim/awesome-claude-code)")),
			), s.handleAwesomeDiff},
			{mcp.NewTool("ralphglasses_awesome_report",
				mcp.WithDescription("Generate formatted report from saved analysis results"),
				mcp.WithString("save_to", mcp.Required(), mcp.Description("Repo path where analysis is saved")),
				mcp.WithString("format", mcp.Description("Output format: json or markdown (default: markdown)")),
			), s.handleAwesomeReport},
			{mcp.NewTool("ralphglasses_awesome_sync",
				mcp.WithDescription("Full pipeline: fetch awesome-list -> diff -> analyze new entries -> report -> save"),
				mcp.WithString("save_to", mcp.Required(), mcp.Description("Repo path to save results")),
				mcp.WithString("repo", mcp.Description("GitHub repo (default: hesreallyhim/awesome-claude-code)")),
				mcp.WithString("full_rescan", mcp.Description("Re-analyze all entries, not just new: true/false (default: false)")),
				mcp.WithNumber("max_workers", mcp.Description("Concurrent README fetches (default 5)")),
			), s.handleAwesomeSync},
		},
	}
}

func (s *Server) buildAdvancedGroup() ToolGroup {
	return ToolGroup{
		Name:        "advanced",
		Description: "Advanced: RC tools, events, HITL, autonomy, feedback, provider recommend, journals, workflows, tool benchmark",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_rc_status",
				mcp.WithDescription("Compact fleet overview for mobile: active sessions, costs, alerts in readable text"),
			), s.handleRCStatus},
			{mcp.NewTool("ralphglasses_rc_send",
				mcp.WithDescription("Send prompt to repo -- auto-stops existing session, launches new. The 'input' tool for remote control."),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("What to tell the agent")),
				mcp.WithString("provider", mcp.Description("claude (default), gemini, codex")),
				mcp.WithString("model", mcp.Description("Override model")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget in USD (default: 5.0)")),
				mcp.WithString("resume", mcp.Description("true to resume last session instead of fresh start")),
			), s.handleRCSend},
			{mcp.NewTool("ralphglasses_rc_read",
				mcp.WithDescription("Read recent output from most active session. Combines tail + status for mobile."),
				mcp.WithString("id", mcp.Description("Session ID (omit for most recently active)")),
				mcp.WithString("cursor", mcp.Description("Cursor from previous call -- only new output")),
				mcp.WithNumber("lines", mcp.Description("Max lines (default 10, max 30)")),
			), s.handleRCRead},
			{mcp.NewTool("ralphglasses_rc_act",
				mcp.WithDescription("Quick fleet action: stop, stop_all, pause, resume, retry. Single tool for all control actions."),
				mcp.WithString("action", mcp.Required(), mcp.Description("Action: stop, stop_all, pause, resume, retry")),
				mcp.WithString("target", mcp.Description("Session ID or repo name (required except stop_all)")),
			), s.handleRCAct},
			{mcp.NewTool("ralphglasses_event_list",
				mcp.WithDescription("Query recent fleet events from the event bus"),
				mcp.WithString("type", mcp.Description("Filter by event type (e.g. session.started, cost.update)")),
				mcp.WithString("types", mcp.Description("Comma-separated event types to filter (OR). Alternative to single 'type' param")),
				mcp.WithString("repo", mcp.Description("Filter by repo name")),
				mcp.WithNumber("limit", mcp.Description("Max events to return (default 50)")),
				mcp.WithString("since", mcp.Description("ISO timestamp filter")),
				mcp.WithString("until", mcp.Description("ISO timestamp upper bound (exclusive)")),
				mcp.WithString("session_id", mcp.Description("Filter by session ID")),
				mcp.WithString("provider", mcp.Description("Filter by provider")),
				mcp.WithNumber("offset", mcp.Description("Skip first N results for pagination (default 0)")),
			), s.handleEventList},
			{mcp.NewTool("ralphglasses_event_poll",
				mcp.WithDescription("Poll for new fleet events since last check. Cursor-based for efficient mobile polling."),
				mcp.WithString("cursor", mcp.Description("Cursor from previous response (omit for recent)")),
				mcp.WithNumber("limit", mcp.Description("Max events (default 20, max 50)")),
				mcp.WithString("type", mcp.Description("Filter by event type (e.g. session.started, cost.update)")),
			), s.handleEventPoll},
			{mcp.NewTool("ralphglasses_hitl_score",
				mcp.WithDescription("Current human-in-the-loop score: manual interventions vs autonomous actions, with trend"),
				mcp.WithNumber("hours", mcp.Description("Time window in hours (default: 24)")),
			), s.handleHITLScore},
			{mcp.NewTool("ralphglasses_hitl_history",
				mcp.WithDescription("Recent HITL events: manual stops, auto-recoveries, config changes, etc."),
				mcp.WithNumber("hours", mcp.Description("Time window in hours (default: 24)")),
				mcp.WithNumber("limit", mcp.Description("Max events (default: 50)")),
			), s.handleHITLHistory},
			{mcp.NewTool("ralphglasses_autonomy_level",
				mcp.WithDescription("View or set the autonomy level (0=observe, 1=auto-recover, 2=auto-optimize, 3=full-autonomy). When setting, also starts/stops the autonomous supervisor."),
				mcp.WithString("level", mcp.Description("New level: 0-3 or name (omit to view current)")),
				mcp.WithString("repo_path", mcp.Description("Repo path for the supervisor (used when setting level)")),
			), s.handleAutonomyLevel},
			{mcp.NewTool("ralphglasses_supervisor_status",
				mcp.WithDescription("Returns the autonomous supervisor status including whether it's running, tick count, and last cycle launch time."),
			), s.handleSupervisorStatus},
			{mcp.NewTool("ralphglasses_autonomy_decisions",
				mcp.WithDescription("Recent autonomous decisions with rationale, inputs, and outcomes"),
				mcp.WithNumber("limit", mcp.Description("Max decisions (default: 20)")),
			), s.handleAutonomyDecisions},
			{mcp.NewTool("ralphglasses_autonomy_override",
				mcp.WithDescription("Override/reverse an autonomous decision and record human intervention"),
				mcp.WithString("decision_id", mcp.Required(), mcp.Description("Decision ID to override")),
				mcp.WithString("details", mcp.Description("Why this was overridden")),
			), s.handleAutonomyOverride},
			{mcp.NewTool("ralphglasses_feedback_profiles",
				mcp.WithDescription("View feedback profiles: per-task-type and per-provider performance data from journal analysis. Auto-seeds from observations when empty."),
				mcp.WithString("action", mcp.Description("Action: 'get' (default) returns profiles, 'seed' forces re-seed from observations")),
				mcp.WithString("type", mcp.Description("Filter: prompt, provider, or omit for both")),
			), s.handleFeedbackProfiles},
			{mcp.NewTool("ralphglasses_provider_recommend",
				mcp.WithDescription("Recommend best provider + model + budget for a task based on feedback profiles and cost normalization"),
				mcp.WithString("task", mcp.Required(), mcp.Description("Task description (e.g. 'fix lint errors', 'add search feature')")),
			), s.handleProviderRecommend},
			{mcp.NewTool("ralphglasses_tool_benchmark",
				mcp.WithDescription("Per-tool performance benchmarks: latency percentiles, success rates, and regression detection"),
				mcp.WithString("tool", mcp.Description("Filter to a specific tool name")),
				mcp.WithString("compare", mcp.Description("Include regression analysis vs previous baseline: true/false (default: false)")),
				mcp.WithNumber("hours", mcp.Description("Time window in hours (default 24)")),
			), s.handleToolBenchmark},
			{mcp.NewTool("ralphglasses_journal_read",
				mcp.WithDescription("Read improvement journal entries for a repo with synthesized context"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("limit", mcp.Description("Max entries to return (default 10)")),
			), s.handleJournalRead},
			{mcp.NewTool("ralphglasses_journal_write",
				mcp.WithDescription("Manually write an improvement note to a repo's journal"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("worked", mcp.Description("Comma-separated items that worked")),
				mcp.WithString("failed", mcp.Description("Comma-separated items that failed")),
				mcp.WithString("suggest", mcp.Description("Comma-separated suggestions")),
				mcp.WithString("session_id", mcp.Description("Associated session ID (optional)")),
			), s.handleJournalWrite},
			{mcp.NewTool("ralphglasses_journal_prune",
				mcp.WithDescription("Compact improvement journal to prevent unbounded growth"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("keep", mcp.Description("Number of entries to keep (default 100)")),
				mcp.WithString("dry_run", mcp.Description("Preview only, don't modify: true/false (default: true)")),
			), s.handleJournalPrune},
			{mcp.NewTool("ralphglasses_workflow_define",
				mcp.WithDescription("Define a multi-step workflow as YAML"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("name", mcp.Required(), mcp.Description("Workflow name")),
				mcp.WithString("yaml", mcp.Required(), mcp.Description("Workflow YAML definition")),
			), s.handleWorkflowDefine},
			{mcp.NewTool("ralphglasses_workflow_run",
				mcp.WithDescription("Execute a defined workflow, launching sessions per step"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("name", mcp.Required(), mcp.Description("Workflow name")),
			), s.handleWorkflowRun},
			{mcp.NewTool("ralphglasses_workflow_delete",
				mcp.WithDescription("Delete a workflow definition file"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("name", mcp.Required(), mcp.Description("Workflow name to delete")),
			), s.handleWorkflowDelete},
			{mcp.NewTool("ralphglasses_bandit_status",
				mcp.WithDescription("View multi-armed bandit arm statistics for provider selection"),
			), s.handleBanditStatus},
			{mcp.NewTool("ralphglasses_confidence_calibration",
				mcp.WithDescription("View calibrated confidence model weights, training status, and feature importances"),
			), s.handleConfidenceCalibration},
			{mcp.NewTool("ralphglasses_circuit_reset",
				mcp.WithDescription("Reset circuit breaker state for a named service, re-enabling requests after failures. Use 'enhancer' for the LLM prompt enhancer circuit breaker, or a repo name for its file-based circuit breaker."),
				mcp.WithString("service", mcp.Required(), mcp.Description("Service/circuit to reset: 'enhancer' or a repo name")),
			), s.handleCircuitReset},
		},
	}
}

func (s *Server) buildEvalGroup() ToolGroup {
	return ToolGroup{
		Name:        "eval",
		Description: "Offline evaluation: counterfactual analysis, Bayesian A/B testing, frequentist significance testing, changepoint detection",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_eval_counterfactual",
				mcp.WithDescription("Estimate outcomes under hypothetical policy changes using inverse propensity scoring on loop observations"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Observation window in hours (default: 168 = 7 days)")),
				mcp.WithString("policy", mcp.Required(), mcp.Description("Policy type: cascade_threshold or provider_routing")),
				mcp.WithNumber("threshold", mcp.Description("New cascade threshold for cascade_threshold policy (default: 0.6)")),
				mcp.WithString("task_type", mcp.Description("Task type for provider_routing policy")),
				mcp.WithString("provider", mcp.Description("Target provider for provider_routing policy")),
			), s.handleEvalCounterfactual},
			{mcp.NewTool("ralphglasses_eval_ab_test",
				mcp.WithDescription("Bayesian A/B test comparing providers or time periods using Beta-Bernoulli model"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Observation window in hours (default: 168)")),
				mcp.WithString("mode", mcp.Required(), mcp.Description("Comparison mode: providers or periods")),
				mcp.WithString("provider_a", mcp.Description("First provider (providers mode)")),
				mcp.WithString("provider_b", mcp.Description("Second provider (providers mode)")),
				mcp.WithNumber("split_hours_ago", mcp.Description("Hours ago to split time periods (periods mode)")),
			), s.handleEvalABTest},
			{mcp.NewTool("ralphglasses_eval_changepoints",
				mcp.WithDescription("Detect performance shifts using CUSUM changepoint detection on loop observations"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Observation window in hours (default: 168)")),
				mcp.WithString("metric", mcp.Description("Specific metric to analyze (completion_rate, cost, latency, confidence, difficulty). Omit for all.")),
			), s.handleEvalChangepoints},
			{mcp.NewTool("ralphglasses_eval_significance",
				mcp.WithDescription("Frequentist significance testing (z-test/t-test) with combined Bayesian comparison report"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Observation window in hours (default: 168)")),
				mcp.WithString("mode", mcp.Required(), mcp.Description("Comparison mode: providers, periods, or cost")),
				mcp.WithString("provider_a", mcp.Description("First provider (providers/cost mode)")),
				mcp.WithString("provider_b", mcp.Description("Second provider (providers/cost mode)")),
				mcp.WithNumber("split_hours_ago", mcp.Description("Hours ago to split time periods (periods mode)")),
			), s.handleEvalSignificance},
			{mcp.NewTool("ralphglasses_anomaly_detect",
				mcp.WithDescription("Detect anomalies in metric streams using sliding-window z-score analysis"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Observation window in hours (default: 168)")),
				mcp.WithString("metric", mcp.Required(), mcp.Description("Metric to analyze — full names (total_cost_usd, total_latency_ms, confidence, difficulty_score) or shorthands (cost, latency, difficulty)")),
			), s.handleAnomalyDetect},
		},
	}
}

func (s *Server) buildRdcycleGroup() ToolGroup {
	return ToolGroup{
		Name:        "rdcycle",
		Description: "R&D cycle automation — finding-to-task conversion, cycle planning, baselines, merging, and scheduling",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_finding_to_task",
				mcp.WithDescription("Convert a scratchpad finding into a structured loop task spec"),
				mcp.WithString("finding_id", mcp.Required(), mcp.Description("Finding ID (e.g., FINDING-240)")),
				mcp.WithString("scratchpad_name", mcp.Required(), mcp.Description("Scratchpad filename without path")),
			), s.handleFindingToTask},
			{mcp.NewTool("ralphglasses_cycle_baseline",
				mcp.WithDescription("Snapshot current repo metrics as a cycle baseline"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithString("metrics", mcp.Description("Comma-separated metric names to capture (default: all)")),
			), s.handleCycleBaseline},
			{mcp.NewTool("ralphglasses_cycle_plan",
				mcp.WithDescription("Generate a prioritized task plan for the next R&D cycle from unresolved findings"),
				mcp.WithString("previous_cycle_id", mcp.Description("Previous cycle ID for continuity")),
				mcp.WithNumber("max_tasks", mcp.Description("Maximum tasks to include (default: 10)")),
				mcp.WithNumber("budget", mcp.Description("Budget in USD (default: 5.0)")),
			), s.handleCyclePlan},
			{mcp.NewTool("ralphglasses_cycle_merge",
				mcp.WithDescription("Merge parallel worktree results with conflict detection"),
				mcp.WithString("worktree_paths", mcp.Required(), mcp.Description("Comma-separated worktree paths to merge")),
				mcp.WithString("conflict_strategy", mcp.Description("Conflict resolution: ours, theirs, or manual (default: manual)")),
			), s.handleCycleMerge},
			{mcp.NewTool("ralphglasses_cycle_schedule",
				mcp.WithDescription("Schedule recurring R&D cycles with cron expressions"),
				mcp.WithString("cron_expr", mcp.Required(), mcp.Description("Cron expression (e.g., '0 2 * * 1' for Monday 2am)")),
				mcp.WithString("cycle_config", mcp.Description("JSON cycle configuration")),
			), s.handleCycleSchedule},
			{mcp.NewTool("ralphglasses_loop_replay",
				mcp.WithDescription("Replay a failed loop iteration with modified parameters"),
				mcp.WithString("loop_id", mcp.Required(), mcp.Description("Loop run ID")),
				mcp.WithNumber("iteration", mcp.Required(), mcp.Description("Iteration number to replay")),
				mcp.WithString("overrides", mcp.Description("JSON overrides: {model, provider, budget}")),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected if omitted)")),
			), s.handleLoopReplay},
			{mcp.NewTool("ralphglasses_budget_forecast",
				mcp.WithDescription("Predict cost of N more iterations based on historical cost observations"),
				mcp.WithString("loop_id", mcp.Required(), mcp.Description("Loop run ID to forecast")),
				mcp.WithNumber("iterations", mcp.Description("Number of iterations to forecast (default 10)")),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected if omitted)")),
			), s.handleBudgetForecast},
			{mcp.NewTool("ralphglasses_diff_review",
				mcp.WithDescription("Auto-review a git diff for quality issues: scope creep, missing tests, TODOs, style"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithString("ref", mcp.Description("Git ref to review (default HEAD)")),
				mcp.WithString("checks", mcp.Description("CSV of checks: scope_creep, missing_tests, style, todos (default: all)")),
			), s.handleDiffReview},
			{mcp.NewTool("ralphglasses_finding_reason",
				mcp.WithDescription("Analyze scratchpad findings for root causes by category clustering"),
				mcp.WithString("name", mcp.Required(), mcp.Description("Scratchpad name (e.g., 'tool_improvement')")),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected if omitted)")),
			), s.handleFindingReason},
			{mcp.NewTool("ralphglasses_observation_correlate",
				mcp.WithDescription("Link observations to git commits by timestamp proximity"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithNumber("hours", mcp.Description("Hours of history to correlate (default 24)")),
			), s.handleObservationCorrelate},

			// Cycle engine tools (state machine integration)
			{mcp.NewTool("ralphglasses_cycle_create",
				mcp.WithDescription("Create a new R&D cycle with objective and success criteria"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithString("name", mcp.Description("Cycle name (default: 'cycle')")),
				mcp.WithString("objective", mcp.Required(), mcp.Description("Cycle objective")),
				mcp.WithString("criteria", mcp.Description("Comma-separated success criteria")),
			), s.handleCycleCreate},
			{mcp.NewTool("ralphglasses_cycle_advance",
				mcp.WithDescription("Advance active cycle to next phase in state machine"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithString("cycle_id", mcp.Description("Cycle ID (default: active cycle)")),
			), s.handleCycleAdvance},
			{mcp.NewTool("ralphglasses_cycle_status",
				mcp.WithDescription("Get current state of a cycle including tasks, findings, and synthesis"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithString("cycle_id", mcp.Description("Cycle ID (default: active cycle)")),
			), s.handleCycleStatus},
			{mcp.NewTool("ralphglasses_cycle_fail",
				mcp.WithDescription("Mark a cycle as failed with error message"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithString("cycle_id", mcp.Description("Cycle ID (default: active cycle)")),
				mcp.WithString("error", mcp.Description("Error message")),
			), s.handleCycleFail},
			{mcp.NewTool("ralphglasses_cycle_list",
				mcp.WithDescription("List all R&D cycles for a repo, sorted by most recent"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithNumber("limit", mcp.Description("Max results (default 20)")),
			), s.handleCycleList},
			{mcp.NewTool("ralphglasses_cycle_synthesize",
				mcp.WithDescription("Set cycle synthesis and advance to complete"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithString("cycle_id", mcp.Description("Cycle ID (default: active cycle)")),
				mcp.WithString("summary", mcp.Required(), mcp.Description("Synthesis summary")),
				mcp.WithString("accomplished", mcp.Description("Comma-separated list of accomplishments")),
				mcp.WithString("remaining", mcp.Description("Comma-separated list of remaining work")),
				mcp.WithString("next_objective", mcp.Description("Objective for next cycle")),
				mcp.WithString("patterns", mcp.Description("Comma-separated patterns observed")),
			), s.handleCycleSynthesize},
			{mcp.NewTool("ralphglasses_cycle_run",
				mcp.WithDescription("Drive a full R&D cycle synchronously through all phases: create, baseline, plan, execute, observe, synthesize, complete"),
				mcp.WithString("repo_path", mcp.Required(), mcp.Description("Repository name or path")),
				mcp.WithString("name", mcp.Description("Cycle name (default: 'cycle')")),
				mcp.WithString("objective", mcp.Required(), mcp.Description("Cycle objective")),
				mcp.WithString("criteria", mcp.Description("Comma-separated success criteria")),
				mcp.WithNumber("max_tasks", mcp.Description("Max tasks to plan (default 10)")),
			), s.handleCycleRun},
		},
	}
}

func (s *Server) buildObservabilityGroup() ToolGroup {
	return ToolGroup{
		Name:        "observability",
		Description: "Observation queries, scratchpad automation, loop wait/poll, coverage, cost estimation, merge verification",
		Tools: []ToolEntry{
			// Observation query tools
			{mcp.NewTool("ralphglasses_observation_query",
				mcp.WithDescription("Filter and paginate loop observations from .ralph/logs/loop_observations.jsonl"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Hours of history to query (default 48)")),
				mcp.WithString("loop_id", mcp.Description("Filter by loop ID")),
				mcp.WithString("status", mcp.Description("Filter by status (pass, fail, error)")),
				mcp.WithString("provider", mcp.Description("Filter by provider")),
				mcp.WithNumber("limit", mcp.Description("Max results (default 50, max 500)")),
				mcp.WithString("since", mcp.Description("RFC3339 timestamp lower bound (overrides hours if set)")),
				mcp.WithString("until", mcp.Description("RFC3339 timestamp upper bound")),
			), s.handleObservationQuery},
			{mcp.NewTool("ralphglasses_observation_summary",
				mcp.WithDescription("Aggregate observation stats with p50/p95/p99 percentiles via SummarizeObservations"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Hours of history (default 48)")),
				mcp.WithString("loop_id", mcp.Description("Filter by loop ID")),
				mcp.WithString("since", mcp.Description("RFC3339 timestamp lower bound (overrides hours if set)")),
				mcp.WithString("until", mcp.Description("RFC3339 timestamp upper bound")),
			), s.handleObservationSummary},

			// Scratchpad tools
			{mcp.NewTool("ralphglasses_scratchpad_read",
				mcp.WithDescription("Read a .ralph/{name}_scratchpad.md file"),
				mcp.WithString("name", mcp.Required(), mcp.Description("Scratchpad name (e.g. 'tool_improvement')")),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected from CWD; required when multiple repos are scanned)")),
			), s.handleScratchpadRead},
			{mcp.NewTool("ralphglasses_scratchpad_append",
				mcp.WithDescription("Append a markdown note to a scratchpad file"),
				mcp.WithString("name", mcp.Required(), mcp.Description("Scratchpad name")),
				mcp.WithString("content", mcp.Required(), mcp.Description("Markdown content to append")),
				mcp.WithString("section", mcp.Description("Optional section header to add before content")),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected from CWD; required when multiple repos are scanned)")),
			), s.handleScratchpadAppend},
			{mcp.NewTool("ralphglasses_scratchpad_list",
				mcp.WithDescription("List all scratchpad files in .ralph/"),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected from CWD; required when multiple repos are scanned)")),
			), s.handleScratchpadList},
			{mcp.NewTool("ralphglasses_scratchpad_resolve",
				mcp.WithDescription("Mark a numbered scratchpad item as resolved"),
				mcp.WithString("name", mcp.Required(), mcp.Description("Scratchpad name")),
				mcp.WithNumber("item_number", mcp.Required(), mcp.Description("Item number to resolve")),
				mcp.WithString("resolution", mcp.Required(), mcp.Description("Resolution description")),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected from CWD; required when multiple repos are scanned)")),
			), s.handleScratchpadResolve},
			{mcp.NewTool("ralphglasses_scratchpad_delete",
				mcp.WithDescription("Delete a numbered finding from a scratchpad file"),
				mcp.WithString("scratchpad", mcp.Required(), mcp.Description("Scratchpad name")),
				mcp.WithString("finding_id", mcp.Required(), mcp.Description("Finding number to delete (e.g. '2')")),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected from CWD; required when multiple repos are scanned)")),
			), s.handleScratchpadDelete},
			{mcp.NewTool("ralphglasses_scratchpad_validate",
				mcp.WithDescription("Validate scratchpad entries against expected constraints: score inflation, path errors, budget mismatches, no-op iterations"),
				mcp.WithString("name", mcp.Required(), mcp.Description("Scratchpad name")),
				mcp.WithString("check", mcp.Required(), mcp.Description("Validation type: scores, paths, budget, noops, all")),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected from CWD; required when multiple repos are scanned)")),
			), s.handleScratchpadValidate},
			{mcp.NewTool("ralphglasses_scratchpad_context",
				mcp.WithDescription("Auto-enrich scratchpad with current system context: fleet status, observations, routing, autonomy level"),
				mcp.WithString("name", mcp.Required(), mcp.Description("Scratchpad name")),
				mcp.WithString("sections", mcp.Required(), mcp.Description("Comma-separated sections: fleet, observations, routing, autonomy, all")),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected from CWD; required when multiple repos are scanned)")),
			), s.handleScratchpadContext},
			{mcp.NewTool("ralphglasses_scratchpad_reason",
				mcp.WithDescription("Record intermediate reasoning between tool calls: dimension-to-stage mapping, rate cards, prune thresholds, provider selection"),
				mcp.WithString("name", mcp.Required(), mcp.Description("Scratchpad name")),
				mcp.WithString("topic", mcp.Required(), mcp.Description("Reasoning topic: enhance_stages, rate_cards, prune_thresholds, provider_selection")),
				mcp.WithString("input", mcp.Description("JSON string with context data for the reasoning")),
				mcp.WithString("repo", mcp.Description("Repo name (auto-detected from CWD; required when multiple repos are scanned)")),
			), s.handleScratchpadReason},

			// Loop wait/poll tools
			{mcp.NewTool("ralphglasses_loop_await",
				mcp.WithDescription("Block until a session or loop completes (replaces sleep anti-pattern)"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session or loop ID to wait for")),
				mcp.WithString("type", mcp.Required(), mcp.Description("'session' or 'loop'")),
				mcp.WithNumber("timeout_seconds", mcp.Description("Max wait time in seconds (default 300)")),
				mcp.WithNumber("poll_interval_seconds", mcp.Description("Poll interval in seconds (default 10, min 5)")),
			), s.handleLoopAwait},
			{mcp.NewTool("ralphglasses_loop_poll",
				mcp.WithDescription("Non-blocking single status check for a session or loop"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session or loop ID")),
				mcp.WithString("type", mcp.Required(), mcp.Description("'session' or 'loop'")),
			), s.handleLoopPoll},

			// Coverage report
			{mcp.NewTool("ralphglasses_coverage_report",
				mcp.WithDescription("Run go test -coverprofile and report per-package coverage vs threshold"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name or absolute path")),
				mcp.WithString("packages", mcp.Description("Package pattern (default ./...)")),
				mcp.WithNumber("threshold", mcp.Description("Coverage threshold percentage (default 70)")),
			), s.handleCoverageReport},

			// Cost estimation
			{mcp.NewTool("ralphglasses_cost_estimate",
				mcp.WithDescription("Pre-launch cost estimate for a session or loop"),
				mcp.WithString("provider", mcp.Required(), mcp.Description("Provider: claude, gemini, or codex")),
				mcp.WithString("model", mcp.Description("Model name (uses provider default if omitted)")),
				mcp.WithNumber("prompt_tokens", mcp.Description("Prompt length in tokens (default 5000)")),
				mcp.WithNumber("turns", mcp.Description("Expected conversation turns (default 5)")),
				mcp.WithNumber("output_tokens_per_turn", mcp.Description("Output tokens per turn (default 2000)")),
				mcp.WithString("mode", mcp.Description("'session' or 'loop' (default session)")),
				mcp.WithNumber("iterations", mcp.Description("Loop iterations for mode=loop (default 3)")),
				mcp.WithString("repo", mcp.Description("Repo name for historical calibration")),
			), s.handleCostEstimate},

			// Merge verification
			{mcp.NewTool("ralphglasses_merge_verify",
				mcp.WithDescription("Run build+vet+test sequence to verify a merge"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo path (absolute)")),
				mcp.WithBoolean("fast", mcp.Description("Use -short flag for faster tests")),
				mcp.WithBoolean("coverage", mcp.Description("Include coverage profile")),
				mcp.WithString("packages", mcp.Description("Package pattern to test (default ./...)")),
				mcp.WithBoolean("race", mcp.Description("Enable -race detector (default true)")),
			), s.handleMergeVerify},

			// Worktree create
			{mcp.NewTool("ralphglasses_worktree_create",
				mcp.WithDescription("Create a new git worktree for a repo under .ralph/worktrees/manual/"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("name", mcp.Required(), mcp.Description("Worktree name (sanitized for filesystem)")),
			), s.handleWorktreeCreate},

			// Worktree cleanup
			{mcp.NewTool("ralphglasses_worktree_cleanup",
				mcp.WithDescription("Clean up stale loop worktrees older than a given age — skips locked/active worktrees"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("max_age_hours", mcp.Description("Max age in hours before cleanup (default 24)")),
			), s.handleWorktreeCleanup},
		},
	}
}
