package mcpserver

import (
	"github.com/mark3labs/mcp-go/mcp"
)

func (s *Server) buildSessionGroup() ToolGroup {
	return ToolGroup{
		Name:        "session",
		Description: "LLM session lifecycle: launch, list, status, resume, stop, budget, retry, output, tail, diff, compare, errors, export",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_session_launch",
				mcp.WithDescription("Launch a headless LLM CLI session (claude/gemini/codex) for a repo with a `prompt`"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("Prompt/task to send")),
				mcp.WithString("provider", mcp.Description("LLM provider: codex (default), claude, gemini")),
				mcp.WithString("model", mcp.Description("Model to use")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget in USD — maximum spend for this session")),
				mcp.WithNumber("max_turns", mcp.Description("Maximum conversation turns")),
				mcp.WithString("agent", mcp.Description("Agent name (from .claude/agents/)")),
				mcp.WithString("allowed_tools", mcp.Description("Comma-separated allowed tools (e.g. Bash,Read,Edit)")),
				mcp.WithString("system_prompt", mcp.Description("Additional system prompt to append")),
				mcp.WithString("session_name", mcp.Description("Human-readable session name")),
				mcp.WithString("worktree", mcp.Description("Git worktree isolation (true for auto, or branch name)")),
				mcp.WithString("no_journal", mcp.Description("Skip improvement journal injection: true/false (default: false)")),
				mcp.WithString("enhance_prompt", mcp.Description("Auto-enhance the prompt before launch: local (deterministic), llm (Claude API), auto (try LLM, fallback). Omit to skip enhancement")),
				mcp.WithString("target_provider", mcp.Description("Target LLM provider for prompt enhancement: claude, gemini, openai (defaults to session provider)")),
				mcp.WithBoolean("bare", mcp.Description("Skip hooks/plugins for faster scripted startup")),
				mcp.WithString("effort", mcp.Description("Thinking effort level: low, medium, high, max")),
				mcp.WithString("fallback_model", mcp.Description("Auto-fallback model on overload")),
				mcp.WithString("output_schema", mcp.Description("JSON schema for structured output validation (Claude: --json-schema, Codex: --output-schema)")),
			), s.handleSessionLaunch},
			{mcp.NewTool("ralphglasses_session_list",
				mcp.WithDescription("List all tracked LLM sessions with status, cost, and turns"),
				mcp.WithString("repo", mcp.Description("Filter by repo name (omit for all)")),
				mcp.WithString("provider", mcp.Description("Filter by provider: claude, gemini, codex (omit for all)")),
				mcp.WithString("status", mcp.Description("Filter by status: running, completed, errored, stopped")),
			), s.handleSessionList},
			{mcp.NewTool("ralphglasses_session_status",
				mcp.WithDescription("Get detailed status for a session by `id` including output, cost, and turns"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID")),
			), s.handleSessionStatus},
			{mcp.NewTool("ralphglasses_session_resume",
				mcp.WithDescription("Resume a previous LLM CLI session for `repo` using `session_id`"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("session_id", mcp.Required(), mcp.Description("Provider session ID to resume (from session status)")),
				mcp.WithString("provider", mcp.Description("LLM provider: codex (default), claude, gemini")),
				mcp.WithString("prompt", mcp.Description("Follow-up prompt (optional)")),
			), s.handleSessionResume},
			{mcp.NewTool("ralphglasses_session_stop",
				mcp.WithDescription("Stop a running session by `id`"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID to stop")),
			), s.handleSessionStop},
			{mcp.NewTool("ralphglasses_session_stop_all",
				mcp.WithDescription("Stop all running LLM sessions — emergency cost cutoff"),
			), s.handleSessionStopAll},
			{mcp.NewTool("ralphglasses_session_budget",
				mcp.WithDescription("Get cost/budget info for a session by `id`, or update budget"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget in USD — new budget to set (omit to just query)")),
			), s.handleSessionBudget},
			{mcp.NewTool("ralphglasses_session_retry",
				mcp.WithDescription("Re-launch a failed session by `id` with same params, optional overrides"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID to retry")),
				mcp.WithString("model", mcp.Description("Override model")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget in USD — override budget for retry")),
			), s.handleSessionRetry},
			{mcp.NewTool("ralphglasses_session_output",
				mcp.WithDescription("Get recent output from a session by `id`"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID")),
				mcp.WithNumber("lines", mcp.Description("Number of lines to return (default 20, max 100)")),
			), s.handleSessionOutput},
			{mcp.NewTool("ralphglasses_session_tail",
				mcp.WithDescription("Tail session output by `id` with cursor — returns only new lines since last call"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID")),
				mcp.WithString("cursor", mcp.Description("Cursor from previous response (omit for latest)")),
				mcp.WithNumber("lines", mcp.Description("Max lines to return (default 30, max 100)")),
			), s.handleSessionTail},
			{mcp.NewTool("ralphglasses_session_diff",
				mcp.WithDescription("Git changes made during a session's execution window by `id`"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID")),
				mcp.WithString("stat_only", mcp.Description("true/false (default: true)")),
				mcp.WithNumber("max_lines", mcp.Description("Truncate diff at N lines (default 200)")),
			), s.handleSessionDiff},
			{mcp.NewTool("ralphglasses_session_compare",
				mcp.WithDescription("Compare two sessions by `id1` and `id2`: cost, turns, duration, provider efficiency"),
				mcp.WithString("id1", mcp.Required(), mcp.Description("First session ID")),
				mcp.WithString("id2", mcp.Required(), mcp.Description("Second session ID")),
			), s.handleSessionCompare},
			{mcp.NewTool("ralphglasses_session_replay_diff",
				mcp.WithDescription("Side-by-side comparison of two session JSONL replay files: event alignment, similarity score"),
				mcp.WithString("path_a", mcp.Required(), mcp.Description("Path to first JSONL replay file")),
				mcp.WithString("path_b", mcp.Required(), mcp.Description("Path to second JSONL replay file")),
				mcp.WithNumber("max_events", mcp.Description("Max events in response (default 100)")),
			), s.handleSessionReplayDiff},
			{mcp.NewTool("ralphglasses_session_errors",
				mcp.WithDescription("Aggregated error view: parse failures, API errors, budget warnings"),
				mcp.WithString("repo", mcp.Description("Filter by repo name")),
				mcp.WithString("severity", mcp.Description("Filter: critical, warning, info")),
				mcp.WithNumber("limit", mcp.Description("Max errors (default 50)")),
			), s.handleSessionErrors},
			{mcp.NewTool("ralphglasses_session_export",
				mcp.WithDescription("Export a recorded session replay as Markdown or JSON — includes timeline, tool calls, inputs/outputs"),
				mcp.WithString("session_id", mcp.Required(), mcp.Description("Session ID whose replay to export")),
				mcp.WithString("format", mcp.Description("Export format: markdown (default) or json")),
				mcp.WithString("repo", mcp.Description("Repo name hint for locating replay file")),
				mcp.WithString("event_types", mcp.Description("Comma-separated event types to include: input, output, tool, status (default: all)")),
				mcp.WithString("after", mcp.Description("Only include events after this RFC3339 timestamp")),
				mcp.WithString("before", mcp.Description("Only include events before this RFC3339 timestamp")),
			), s.handleSessionExport},
			{mcp.NewTool("ralphglasses_session_fork",
				mcp.WithDescription("Fork a running or completed session — creates a child session with the parent's context and optional new prompt"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Parent session ID to fork from")),
				mcp.WithString("prompt", mcp.Description("New prompt for the forked session (inherits parent prompt if omitted)")),
				mcp.WithString("model", mcp.Description("Override model for the fork (inherits parent model if omitted)")),
				mcp.WithString("provider", mcp.Description("Override provider for the fork (inherits parent provider if omitted)")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget override in USD (inherits parent budget if omitted)")),
				mcp.WithBoolean("inject_context", mcp.Description("Include parent session output history in fork prompt (default: true)")),
			), s.handleSessionFork},
		},
	}
}

func (s *Server) buildLoopGroup() ToolGroup {
	return ToolGroup{
		Name:        "loop",
		Description: "Perpetual development loops: start, status, step, stop, benchmark, baseline, gates, self-test, self-improve",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_loop_start",
				mcp.WithDescription("Create a multi-provider planner/worker perpetual development loop for a repo"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("planner_model", mcp.Description("Planner model (default: o4-mini)")),
				mcp.WithString("worker_model", mcp.Description("Worker model (default: codex-mini-latest)")),
				mcp.WithString("verifier_model", mcp.Description("Verifier model metadata (default: codex-mini-latest)")),
				mcp.WithString("planner_provider", mcp.Description("Planner provider: claude, gemini, codex (default: codex)")),
				mcp.WithString("worker_provider", mcp.Description("Worker provider: claude, gemini, codex (default: codex)")),
				mcp.WithString("verifier_provider", mcp.Description("Verifier provider: claude, gemini, codex (default: codex)")),
				mcp.WithString("verify_commands", mcp.Description("Newline-separated verification commands (default: ./scripts/dev/ci.sh)")),
				mcp.WithNumber("retry_limit", mcp.Description("Maximum consecutive failed iterations before step is refused")),
				mcp.WithNumber("max_concurrent_workers", mcp.Description("Maximum concurrent workers (currently only 1 supported)")),
				mcp.WithString("worktree_policy", mcp.Description("Worktree isolation policy (default: git)")),
				mcp.WithBoolean("enable_reflexion", mcp.Description("Enable reflexion loop (failure correction injection)")),
				mcp.WithBoolean("enable_episodic_memory", mcp.Description("Enable episodic memory (successful trajectory recall)")),
				mcp.WithBoolean("enable_cascade", mcp.Description("Enable cascade routing (cheap-then-expensive provider)")),
				mcp.WithBoolean("enable_uncertainty", mcp.Description("Enable uncertainty quantification (confidence scoring)")),
				mcp.WithBoolean("enable_curriculum", mcp.Description("Enable curriculum learning (difficulty-based task sorting)")),
				mcp.WithBoolean("self_improvement", mcp.Description("Enable self-improvement mode with autonomous acceptance gate")),
				mcp.WithNumber("max_iterations", mcp.Description("Maximum loop iterations (0 = unlimited)")),
				mcp.WithNumber("duration_hours", mcp.Description("Maximum loop duration in hours (0 = unlimited)")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget in USD — total budget split 1/3 planner, 2/3 worker")),
				mcp.WithString("trace_level", mcp.Description("Trace verbosity: none, summary (default), verbose")),
			), s.handleLoopStart},
			{mcp.NewTool("ralphglasses_loop_status",
				mcp.WithDescription("Get status for a perpetual development loop by `id`"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Loop run ID")),
			), s.handleLoopStatus},
			{mcp.NewTool("ralphglasses_loop_step",
				mcp.WithDescription("Execute one planner/worker/verifier iteration for a loop by `id`"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Loop run ID")),
			), s.handleLoopStep},
			{mcp.NewTool("ralphglasses_loop_stop",
				mcp.WithDescription("Stop a perpetual development loop by `id`"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Loop run ID")),
			), s.handleLoopStop},
			{mcp.NewTool("ralphglasses_loop_benchmark",
				mcp.WithDescription("P50/P95 metrics from recent loop observations for a repo"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Look-back window in hours (default: 48)")),
			), s.handleLoopBenchmark},
			{mcp.NewTool("ralphglasses_loop_baseline",
				mcp.WithDescription("Generate, view, or pin loop performance baseline for a repo"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("action", mcp.Description("Action: view (default), refresh, or pin")),
				mcp.WithNumber("hours", mcp.Description("Window for refresh/pin in hours (default: 48)")),
			), s.handleLoopBaseline},
			{mcp.NewTool("ralphglasses_loop_gates",
				mcp.WithDescription("Evaluate regression gates — returns pass/warn/fail report"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Look-back window in hours (default: 24)")),
			), s.handleLoopGates},
			{mcp.NewTool("ralphglasses_self_test",
				mcp.WithDescription("Run recursive self-test iterations against a repository using the ralphglasses loop engine"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Absolute path to the repository to test")),
				mcp.WithNumber("iterations", mcp.Description("Number of self-test iterations (default: 3)")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget in USD (default: 5.0)")),
				mcp.WithBoolean("use_snapshot", mcp.Description("Restore repo snapshot between iterations (default: true)")),
				mcp.WithBoolean("dry_run", mcp.Description("Validate config without running iterations (default: false)")),
			), s.handleSelfTest},
			{mcp.NewTool("ralphglasses_self_improve",
				mcp.WithDescription("Start a self-improvement loop that autonomously improves a repository — auto-merges safe changes, creates PRs for review-required changes"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("max_iterations", mcp.Description("Maximum iterations (default: 5)")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget in USD (default: 20.0, split 1/4 planner + 3/4 worker)")),
				mcp.WithNumber("duration_hours", mcp.Description("Maximum duration in hours (default: 4)")),
				mcp.WithString("trace_level", mcp.Description("Trace verbosity: none, summary (default), verbose")),
			), s.handleSelfImprove},
			{mcp.NewTool("ralphglasses_session_handoff",
				mcp.WithDescription("Transfer session state to a new session, optionally switching providers. Includes context from observations, cost tracking, and scratchpad."),
				mcp.WithString("source_session_id", mcp.Required(), mcp.Description("Session ID to transfer from")),
				mcp.WithString("target_provider", mcp.Description("Target provider: claude, gemini, codex (default: same as source)")),
				mcp.WithBoolean("include_context", mcp.Description("Include observation context in handoff (default: true)")),
				mcp.WithBoolean("stop_source", mcp.Description("Stop the source session after handoff (default: false)")),
				mcp.WithNumber("context_lines", mcp.Description("Number of recent observations to include (default: 5)")),
				mcp.WithString("handoff_reason", mcp.Description("Reason for handoff (tracked in handoff record)")),
			), s.handleSessionHandoff},
			{mcp.NewTool("ralphglasses_loop_prune",
				mcp.WithDescription("Prune stale loop run files by status and age — removes phantom pending/failed loop state that accumulates over time"),
				mcp.WithNumber("older_than_hours", mcp.Description("Only prune loop runs older than this many hours (default: 72)")),
				mcp.WithString("statuses", mcp.Description("Comma-separated statuses to prune (default: pending,failed)")),
				mcp.WithBoolean("dry_run", mcp.Description("If true, return count without deleting (default: true)")),
				mcp.WithString("repo", mcp.Description("Optional repo name filter — only prune runs for this repo")),
			), s.handleLoopPrune},
		},
	}
}

func (s *Server) buildPromptGroup() ToolGroup {
	return ToolGroup{
		Name:        "prompt",
		Description: "Prompt enhancement: analyze, enhance, lint, improve, classify, should_enhance, templates, template_fill",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_prompt_analyze",
				mcp.WithDescription("Score a prompt across 10 quality dimensions (clarity, specificity, structure, examples, etc.) with letter grades and actionable suggestions"),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("The prompt text to analyze")),
				mcp.WithString("task_type", mcp.Description("Override auto-detection: code, troubleshooting, analysis, creative, workflow, general")),
				mcp.WithString("target_provider", mcp.Description("Target model provider for scoring suggestions: openai (default), claude, gemini")),
			), s.handlePromptAnalyze},
			{mcp.NewTool("ralphglasses_prompt_enhance",
				mcp.WithDescription("Run the 13-stage prompt enhancement pipeline (specificity, positive reframing, XML structure, context reorder, format enforcement, etc.)"),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("The prompt text to enhance")),
				mcp.WithString("task_type", mcp.Description("Override auto-detection: code, troubleshooting, analysis, creative, workflow, general")),
				mcp.WithString("mode", mcp.Description("Enhancement mode: local (default, deterministic), llm (Claude/Gemini/OpenAI API), auto (try LLM, fallback to local)")),
				mcp.WithString("repo", mcp.Description("Repo name to load .prompt-improver.yaml config from")),
				mcp.WithString("target_provider", mcp.Description("Target model provider — controls structure style and scoring: openai (default), claude, gemini")),
				mcp.WithString("trace_level", mcp.Description("Trace verbosity: none, summary (default), verbose")),
			), s.handlePromptEnhance},
			{mcp.NewTool("ralphglasses_prompt_lint",
				mcp.WithDescription("Deep-lint a prompt for anti-patterns: unmotivated rules, negative framing, aggressive caps, vague quantifiers, injection risks, cache-unfriendly ordering"),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("The prompt text to lint")),
			), s.handlePromptLint},
			{mcp.NewTool("ralphglasses_prompt_improve",
				mcp.WithDescription("LLM-powered prompt improvement using Claude, Gemini, or OpenAI with domain-specific meta-prompts"),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("The prompt text to improve")),
				mcp.WithString("task_type", mcp.Description("Override auto-detection: code, troubleshooting, analysis, creative, workflow, general")),
				mcp.WithBoolean("thinking_enabled", mcp.Description("Include thinking scaffolding in the improved prompt")),
				mcp.WithString("feedback", mcp.Description("Optional feedback to guide the improvement direction")),
				mcp.WithString("provider", mcp.Description("LLM provider for improvement: openai (default, requires OPENAI_API_KEY), claude (requires ANTHROPIC_API_KEY), gemini (requires GOOGLE_API_KEY)")),
			), s.handlePromptImprove},
			{mcp.NewTool("ralphglasses_prompt_classify",
				mcp.WithDescription("Classify a prompt's task type (code, troubleshooting, analysis, creative, workflow, general)"),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("The prompt text to classify")),
			), s.handlePromptClassify},
			{mcp.NewTool("ralphglasses_prompt_should_enhance",
				mcp.WithDescription("Check whether a prompt would benefit from enhancement"),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("The prompt text to check")),
				mcp.WithString("repo", mcp.Description("Repo name for loading .prompt-improver.yaml config")),
			), s.handlePromptShouldEnhance},
			{mcp.NewTool("ralphglasses_prompt_templates",
				mcp.WithDescription("List available prompt templates with descriptions and required variables"),
			), s.handlePromptTemplates},
			{mcp.NewTool("ralphglasses_prompt_template_fill",
				mcp.WithDescription("Fill a prompt template by `name` with `vars` (JSON key-value pairs)"),
				mcp.WithString("name", mcp.Required(), mcp.Description("Template name")),
				mcp.WithString("vars", mcp.Required(), mcp.Description("JSON object of variable key-value pairs")),
			), s.handlePromptTemplateFill},
			{mcp.NewTool("ralphglasses_prompt_ab_test",
				mcp.WithDescription("A/B test two prompts by scoring them across 10 quality dimensions. Returns winner, score diff, confidence, and per-dimension comparison."),
				mcp.WithString("prompt_a", mcp.Required(), mcp.Description("First prompt to compare")),
				mcp.WithString("prompt_b", mcp.Required(), mcp.Description("Second prompt to compare")),
				mcp.WithString("target_provider", mcp.Description("Target provider for scoring: openai (default), claude, gemini")),
				mcp.WithString("repo", mcp.Description("Repo name for result storage")),
			), s.handlePromptABTest},
		},
	}
}
