package mcpserver

import (
	"github.com/mark3labs/mcp-go/mcp"
)

// buildToolGroups constructs all tool groups with their tool definitions and handlers.
func (s *Server) buildToolGroups() []ToolGroup {
	return []ToolGroup{
		s.buildCoreGroup(),
		s.buildSessionGroup(),
		s.buildLoopGroup(),
		s.buildPromptGroup(),
		s.buildFleetGroup(),
		s.buildRepoGroup(),
		s.buildRoadmapGroup(),
		s.buildTeamGroup(),
		s.buildAwesomeGroup(),
		s.buildAdvancedGroup(),
		s.buildEvalGroup(),
		s.buildFleetHGroup(),
		s.buildObservabilityGroup(),
	}
}

func (s *Server) buildCoreGroup() ToolGroup {
	return ToolGroup{
		Name:        "core",
		Description: "Essential fleet management: scan, list, start, stop, pause, logs, config",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_scan",
				mcp.WithDescription("Scan for ralph-enabled repos and return their current status"),
			), s.handleScan},
			{mcp.NewTool("ralphglasses_list",
				mcp.WithDescription("List all discovered repos with status summary"),
			), s.handleList},
			{mcp.NewTool("ralphglasses_status",
				mcp.WithDescription("Get detailed status for a specific repo including loop status, circuit breaker, progress, and config"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name (basename of directory)")),
			), s.handleStatus},
			{mcp.NewTool("ralphglasses_start",
				mcp.WithDescription("Start a ralph loop for a repo"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name to start loop for")),
			), s.handleStart},
			{mcp.NewTool("ralphglasses_stop",
				mcp.WithDescription("Stop a running ralph loop for a repo"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name to stop loop for")),
			), s.handleStop},
			{mcp.NewTool("ralphglasses_stop_all",
				mcp.WithDescription("Stop all running ralph loops"),
			), s.handleStopAll},
			{mcp.NewTool("ralphglasses_pause",
				mcp.WithDescription("Pause or resume a running ralph loop"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name to pause/resume")),
			), s.handlePause},
			{mcp.NewTool("ralphglasses_logs",
				mcp.WithDescription("Get recent log lines from a repo's ralph log"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("lines", mcp.Description("Number of lines to return (default 50, max 500)")),
			), s.handleLogs},
			{mcp.NewTool("ralphglasses_config",
				mcp.WithDescription("Get or set .ralphrc config values for a repo"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("key", mcp.Description("Config key to get/set (omit to list all)")),
				mcp.WithString("value", mcp.Description("Value to set (omit to get current value)")),
			), s.handleConfig},
			{mcp.NewTool("ralphglasses_config_bulk",
				mcp.WithDescription("Get/set .ralphrc values across multiple repos"),
				mcp.WithString("key", mcp.Required(), mcp.Description("Config key to get/set")),
				mcp.WithString("value", mcp.Description("Value to set (omit to query)")),
				mcp.WithString("repos", mcp.Description("Comma-separated repo names (default: all)")),
			), s.handleConfigBulk},
		},
	}
}

func (s *Server) buildSessionGroup() ToolGroup {
	return ToolGroup{
		Name:        "session",
		Description: "LLM session lifecycle: launch, list, status, resume, stop, budget, retry, output, tail, diff, compare, errors",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_session_launch",
				mcp.WithDescription("Launch a headless LLM CLI session (claude/gemini/codex) for a repo"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("Prompt/task to send")),
				mcp.WithString("provider", mcp.Description("LLM provider: claude (default), gemini, codex")),
				mcp.WithString("model", mcp.Description("Model to use")),
				mcp.WithNumber("max_budget_usd", mcp.Description("Maximum spend in USD")),
				mcp.WithNumber("max_turns", mcp.Description("Maximum conversation turns")),
				mcp.WithString("agent", mcp.Description("Agent name (from .claude/agents/)")),
				mcp.WithString("allowed_tools", mcp.Description("Comma-separated allowed tools (e.g. Bash,Read,Edit)")),
				mcp.WithString("system_prompt", mcp.Description("Additional system prompt to append")),
				mcp.WithString("session_name", mcp.Description("Human-readable session name")),
				mcp.WithString("worktree", mcp.Description("Git worktree isolation (true for auto, or branch name)")),
				mcp.WithString("no_journal", mcp.Description("Skip improvement journal injection: true/false (default: false)")),
				mcp.WithString("enhance_prompt", mcp.Description("Auto-enhance the prompt before launch: local (deterministic), llm (Claude API), auto (try LLM, fallback). Omit to skip enhancement")),
				mcp.WithString("target_provider", mcp.Description("Target LLM provider for prompt enhancement: claude, gemini, openai (defaults to session provider)")),
				mcp.WithBoolean("bare", mcp.Description("Skip hooks/plugins for faster scripted startup")),
				mcp.WithString("effort", mcp.Description("Thinking effort level: low, medium, high, max")),
				mcp.WithString("fallback_model", mcp.Description("Auto-fallback model on overload")),
				mcp.WithString("output_schema", mcp.Description("JSON schema for structured output validation (Claude: --json-schema, Codex: --output-schema)")),
			), s.handleSessionLaunch},
			{mcp.NewTool("ralphglasses_session_list",
				mcp.WithDescription("List all tracked LLM sessions with status, cost, and turns"),
				mcp.WithString("repo", mcp.Description("Filter by repo name (omit for all)")),
				mcp.WithString("provider", mcp.Description("Filter by provider: claude, gemini, codex (omit for all)")),
				mcp.WithString("status", mcp.Description("Filter by status: running, completed, errored, stopped")),
			), s.handleSessionList},
			{mcp.NewTool("ralphglasses_session_status",
				mcp.WithDescription("Get detailed status for a Claude Code session including output, cost, and turns"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID")),
			), s.handleSessionStatus},
			{mcp.NewTool("ralphglasses_session_resume",
				mcp.WithDescription("Resume a previous LLM CLI session"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("session_id", mcp.Required(), mcp.Description("Provider session ID to resume (from session status)")),
				mcp.WithString("provider", mcp.Description("LLM provider: claude (default), gemini, codex")),
				mcp.WithString("prompt", mcp.Description("Follow-up prompt (optional)")),
			), s.handleSessionResume},
			{mcp.NewTool("ralphglasses_session_stop",
				mcp.WithDescription("Stop a running Claude Code session"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID to stop")),
			), s.handleSessionStop},
			{mcp.NewTool("ralphglasses_session_stop_all",
				mcp.WithDescription("Stop all running LLM sessions — emergency cost cutoff"),
			), s.handleSessionStopAll},
			{mcp.NewTool("ralphglasses_session_budget",
				mcp.WithDescription("Get cost/budget info for a session, or update budget"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID")),
				mcp.WithNumber("budget", mcp.Description("New budget in USD (omit to just query)")),
			), s.handleSessionBudget},
			{mcp.NewTool("ralphglasses_session_retry",
				mcp.WithDescription("Re-launch a failed session with same params, optional overrides"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID to retry")),
				mcp.WithString("model", mcp.Description("Override model")),
				mcp.WithNumber("max_budget_usd", mcp.Description("Override budget")),
			), s.handleSessionRetry},
			{mcp.NewTool("ralphglasses_session_output",
				mcp.WithDescription("Get recent output from a session's output history"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID")),
				mcp.WithNumber("lines", mcp.Description("Number of output lines (default 20, max 100)")),
			), s.handleSessionOutput},
			{mcp.NewTool("ralphglasses_session_tail",
				mcp.WithDescription("Tail session output with cursor — returns only new lines since last call"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID")),
				mcp.WithString("cursor", mcp.Description("Cursor from previous response (omit for latest)")),
				mcp.WithNumber("lines", mcp.Description("Max lines to return (default 30, max 100)")),
			), s.handleSessionTail},
			{mcp.NewTool("ralphglasses_session_diff",
				mcp.WithDescription("Git changes made during a session's execution window"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session ID")),
				mcp.WithString("stat_only", mcp.Description("true/false (default: true)")),
				mcp.WithNumber("max_lines", mcp.Description("Truncate diff at N lines (default 200)")),
			), s.handleSessionDiff},
			{mcp.NewTool("ralphglasses_session_compare",
				mcp.WithDescription("Compare two sessions by ID: cost, turns, duration, provider efficiency"),
				mcp.WithString("id1", mcp.Required(), mcp.Description("First session ID")),
				mcp.WithString("id2", mcp.Required(), mcp.Description("Second session ID")),
			), s.handleSessionCompare},
			{mcp.NewTool("ralphglasses_session_errors",
				mcp.WithDescription("Aggregated error view: parse failures, API errors, budget warnings"),
				mcp.WithString("repo", mcp.Description("Filter by repo name")),
				mcp.WithString("severity", mcp.Description("Filter: critical, warning, info")),
				mcp.WithNumber("limit", mcp.Description("Max errors (default 50)")),
			), s.handleSessionErrors},
		},
	}
}

func (s *Server) buildLoopGroup() ToolGroup {
	return ToolGroup{
		Name:        "loop",
		Description: "Perpetual development loops: start, status, step, stop, benchmark, baseline, gates, self-test, self-improve",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_loop_start",
				mcp.WithDescription("Create a multi-provider planner/worker perpetual development loop for a repo"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("planner_model", mcp.Description("Planner model (default: o1-pro)")),
				mcp.WithString("worker_model", mcp.Description("Worker model (default: gpt-5.4-xhigh)")),
				mcp.WithString("verifier_model", mcp.Description("Verifier model metadata (default: gpt-5.4-xhigh)")),
				mcp.WithString("planner_provider", mcp.Description("Planner provider: claude, gemini, codex (default: codex)")),
				mcp.WithString("worker_provider", mcp.Description("Worker provider: claude, gemini, codex (default: codex)")),
				mcp.WithString("verifier_provider", mcp.Description("Verifier provider: claude, gemini, codex (default: codex)")),
				mcp.WithString("verify_commands", mcp.Description("Newline-separated verification commands (default: ./scripts/dev/ci.sh)")),
				mcp.WithNumber("retry_limit", mcp.Description("Maximum consecutive failed iterations before step is refused")),
				mcp.WithNumber("max_concurrent_workers", mcp.Description("Maximum concurrent workers (currently only 1 supported)")),
				mcp.WithString("worktree_policy", mcp.Description("Worktree isolation policy (default: git)")),
				mcp.WithBoolean("enable_reflexion", mcp.Description("Enable reflexion loop (failure correction injection)")),
				mcp.WithBoolean("enable_episodic_memory", mcp.Description("Enable episodic memory (successful trajectory recall)")),
				mcp.WithBoolean("enable_cascade", mcp.Description("Enable cascade routing (cheap-then-expensive provider)")),
				mcp.WithBoolean("enable_uncertainty", mcp.Description("Enable uncertainty quantification (confidence scoring)")),
				mcp.WithBoolean("enable_curriculum", mcp.Description("Enable curriculum learning (difficulty-based task sorting)")),
				mcp.WithBoolean("self_improvement", mcp.Description("Enable self-improvement mode with autonomous acceptance gate")),
				mcp.WithNumber("max_iterations", mcp.Description("Maximum loop iterations (0 = unlimited)")),
				mcp.WithNumber("duration_hours", mcp.Description("Maximum loop duration in hours (0 = unlimited)")),
				mcp.WithNumber("budget_usd", mcp.Description("Total budget in USD (split 1/3 planner, 2/3 worker)")),
			), s.handleLoopStart},
			{mcp.NewTool("ralphglasses_loop_status",
				mcp.WithDescription("Get status for a perpetual development loop"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Loop run ID")),
			), s.handleLoopStatus},
			{mcp.NewTool("ralphglasses_loop_step",
				mcp.WithDescription("Execute one planner/worker/verifier iteration for a loop"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Loop run ID")),
			), s.handleLoopStep},
			{mcp.NewTool("ralphglasses_loop_stop",
				mcp.WithDescription("Stop a perpetual development loop"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Loop run ID")),
			), s.handleLoopStop},
			{mcp.NewTool("ralphglasses_loop_benchmark",
				mcp.WithDescription("P50/P95 metrics from recent loop observations for a repo"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Look-back window in hours (default: 48)")),
			), s.handleLoopBenchmark},
			{mcp.NewTool("ralphglasses_loop_baseline",
				mcp.WithDescription("Generate, view, or pin loop performance baseline for a repo"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("action", mcp.Description("Action: view (default), refresh, or pin")),
				mcp.WithNumber("hours", mcp.Description("Window for refresh/pin in hours (default: 48)")),
			), s.handleLoopBaseline},
			{mcp.NewTool("ralphglasses_loop_gates",
				mcp.WithDescription("Evaluate regression gates — returns pass/warn/fail report"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Look-back window in hours (default: 24)")),
			), s.handleLoopGates},
			{mcp.NewTool("ralphglasses_self_test",
				mcp.WithDescription("Run recursive self-test iterations against a repository using the ralphglasses loop engine"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Absolute path to the repository to test")),
				mcp.WithNumber("iterations", mcp.Description("Number of self-test iterations (default: 3)")),
				mcp.WithNumber("budget_usd", mcp.Description("Budget cap in USD (default: 5.0)")),
				mcp.WithBoolean("use_snapshot", mcp.Description("Restore repo snapshot between iterations (default: true)")),
				mcp.WithBoolean("dry_run", mcp.Description("Validate config without running iterations (default: false)")),
			), s.handleSelfTest},
			{mcp.NewTool("ralphglasses_self_improve",
				mcp.WithDescription("Start a self-improvement loop that autonomously improves a repository — auto-merges safe changes, creates PRs for review-required changes"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("max_iterations", mcp.Description("Maximum iterations (default: 5)")),
				mcp.WithNumber("budget_usd", mcp.Description("Total budget in USD (default: 20.0, split 1/4 planner + 3/4 worker)")),
				mcp.WithNumber("duration_hours", mcp.Description("Maximum duration in hours (default: 4)")),
			), s.handleSelfImprove},
		},
	}
}

func (s *Server) buildPromptGroup() ToolGroup {
	return ToolGroup{
		Name:        "prompt",
		Description: "Prompt enhancement: analyze, enhance, lint, improve, classify, should_enhance, templates, template_fill",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_prompt_analyze",
				mcp.WithDescription("Score a prompt across 10 quality dimensions (clarity, specificity, structure, examples, etc.) with letter grades and actionable suggestions"),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("The prompt text to analyze")),
				mcp.WithString("task_type", mcp.Description("Override auto-detection: code, troubleshooting, analysis, creative, workflow, general")),
				mcp.WithString("target_provider", mcp.Description("Target model provider for scoring suggestions: claude (default), gemini, openai")),
			), s.handlePromptAnalyze},
			{mcp.NewTool("ralphglasses_prompt_enhance",
				mcp.WithDescription("Run the 13-stage prompt enhancement pipeline (specificity, positive reframing, XML structure, context reorder, format enforcement, etc.)"),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("The prompt text to enhance")),
				mcp.WithString("task_type", mcp.Description("Override auto-detection: code, troubleshooting, analysis, creative, workflow, general")),
				mcp.WithString("mode", mcp.Description("Enhancement mode: local (default, deterministic), llm (Claude/Gemini/OpenAI API), auto (try LLM, fallback to local)")),
				mcp.WithString("repo", mcp.Description("Repo name to load .prompt-improver.yaml config from")),
				mcp.WithString("target_provider", mcp.Description("Target model provider — controls structure style and scoring: claude (default), gemini, openai")),
			), s.handlePromptEnhance},
			{mcp.NewTool("ralphglasses_prompt_lint",
				mcp.WithDescription("Deep-lint a prompt for anti-patterns: unmotivated rules, negative framing, aggressive caps, vague quantifiers, injection risks, cache-unfriendly ordering"),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("The prompt text to lint")),
			), s.handlePromptLint},
			{mcp.NewTool("ralphglasses_prompt_improve",
				mcp.WithDescription("LLM-powered prompt improvement using Claude, Gemini, or OpenAI with domain-specific meta-prompts"),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("The prompt text to improve")),
				mcp.WithString("task_type", mcp.Description("Override auto-detection: code, troubleshooting, analysis, creative, workflow, general")),
				mcp.WithBoolean("thinking_enabled", mcp.Description("Include thinking scaffolding in the improved prompt")),
				mcp.WithString("feedback", mcp.Description("Optional feedback to guide the improvement direction")),
				mcp.WithString("provider", mcp.Description("LLM provider for improvement: claude (default, requires ANTHROPIC_API_KEY), gemini (requires GOOGLE_API_KEY), openai (requires OPENAI_API_KEY)")),
			), s.handlePromptImprove},
			{mcp.NewTool("ralphglasses_prompt_classify",
				mcp.WithDescription("Classify a prompt's task type (code, troubleshooting, analysis, creative, workflow, general)"),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("The prompt text to classify")),
			), s.handlePromptClassify},
			{mcp.NewTool("ralphglasses_prompt_should_enhance",
				mcp.WithDescription("Check whether a prompt would benefit from enhancement"),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("The prompt text to check")),
				mcp.WithString("repo", mcp.Description("Repo name for loading .prompt-improver.yaml config")),
			), s.handlePromptShouldEnhance},
			{mcp.NewTool("ralphglasses_prompt_templates",
				mcp.WithDescription("List available prompt templates with descriptions and required variables"),
			), s.handlePromptTemplates},
			{mcp.NewTool("ralphglasses_prompt_template_fill",
				mcp.WithDescription("Fill a prompt template with variable values"),
				mcp.WithString("name", mcp.Required(), mcp.Description("Template name")),
				mcp.WithString("vars", mcp.Required(), mcp.Description("JSON object of variable key-value pairs")),
			), s.handlePromptTemplateFill},
		},
	}
}

func (s *Server) buildFleetGroup() ToolGroup {
	return ToolGroup{
		Name:        "fleet",
		Description: "Fleet operations: fleet_status, analytics, submit, budget, workers, marathon_dashboard",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_fleet_status",
				mcp.WithDescription("Fleet-wide dashboard: aggregate status, costs, health, and alerts across all repos and sessions in one call"),
				mcp.WithBoolean("summary_only", mcp.Description("Return compact JSON with just repo names, session counts, and total spend instead of full dump")),
			), s.handleFleetStatus},
			{mcp.NewTool("ralphglasses_fleet_analytics",
				mcp.WithDescription("Cost breakdown by provider/repo/time-period with trend analysis. Requires fleet server mode (ralphglasses mcp --fleet)."),
				mcp.WithString("repo", mcp.Description("Filter by repo name")),
				mcp.WithString("provider", mcp.Description("Filter by provider")),
				mcp.WithString("window", mcp.Description("Duration window for metrics snapshot (e.g. '1h', '24h'). Default: 1h")),
			), s.handleFleetAnalytics},
			{mcp.NewTool("ralphglasses_fleet_submit",
				mcp.WithDescription("Submit work to the distributed fleet queue for execution on any worker. Requires fleet server mode (ralphglasses mcp --fleet)."),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("Task prompt")),
				mcp.WithString("provider", mcp.Description("claude (default), gemini, codex")),
				mcp.WithNumber("budget", mcp.Description("Max budget USD (default: 5)")),
				mcp.WithNumber("priority", mcp.Description("Priority 0-10 (default: 5, higher = first)")),
			), s.handleFleetSubmit},
			{mcp.NewTool("ralphglasses_fleet_budget",
				mcp.WithDescription("View or set the fleet-wide budget. Shows spent, remaining, and active work. Requires fleet server mode (ralphglasses mcp --fleet)."),
				mcp.WithNumber("limit", mcp.Description("New budget limit in USD (omit to just view)")),
			), s.handleFleetBudget},
			{mcp.NewTool("ralphglasses_fleet_workers",
				mcp.WithDescription("List registered fleet workers with status, capacity, and spend. Requires fleet server mode (ralphglasses mcp --fleet)."),
			), s.handleFleetWorkers},
			{mcp.NewTool("ralphglasses_marathon_dashboard",
				mcp.WithDescription("Compact marathon status: burn rate, stale sessions, team progress, alerts"),
				mcp.WithNumber("stale_threshold_min", mcp.Description("Minutes idle before flagged stale (default 5)")),
			), s.handleMarathonDashboard},
		},
	}
}

func (s *Server) buildRepoGroup() ToolGroup {
	return ToolGroup{
		Name:        "repo",
		Description: "Repo management: health, optimize, scaffold, claudemd_check, snapshot",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_repo_health",
				mcp.WithDescription("Composite health check: circuit breaker, budget, staleness, errors, active sessions"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
			), s.handleRepoHealth},
			{mcp.NewTool("ralphglasses_repo_optimize",
				mcp.WithDescription("Analyze and optimize ralph config files — detect misconfigs, missing settings, stale plans"),
				mcp.WithString("path", mcp.Required(), mcp.Description("Repo root path")),
				mcp.WithString("focus", mcp.Description("Focus area: config, prompt, plan, all (default: all)")),
				mcp.WithString("dry_run", mcp.Description("Report only, don't modify: true/false (default: true)")),
			), s.handleRepoOptimize},
			{mcp.NewTool("ralphglasses_repo_scaffold",
				mcp.WithDescription("Create/initialize ralph config files (.ralph/, .ralphrc, PROMPT.md, AGENT.md, fix_plan.md) for a repo"),
				mcp.WithString("path", mcp.Required(), mcp.Description("Repo root path")),
				mcp.WithString("project_type", mcp.Description("Project type override (auto-detected from go.mod, package.json, etc.)")),
				mcp.WithString("project_name", mcp.Description("Project name override (defaults to directory name)")),
				mcp.WithString("force", mcp.Description("Overwrite existing files: true/false (default: false)")),
			), s.handleRepoScaffold},
			{mcp.NewTool("ralphglasses_claudemd_check",
				mcp.WithDescription("Health-check a repo's CLAUDE.md for common issues (length, inline code, overtrigger language, missing headers)"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
			), s.handleClaudeMDCheck},
			{mcp.NewTool("ralphglasses_snapshot",
				mcp.WithDescription("Save or list fleet state snapshots"),
				mcp.WithString("action", mcp.Description("Action: save (default) or list")),
				mcp.WithString("name", mcp.Description("Snapshot name (auto-generated if omitted)")),
			), s.handleSnapshot},
		},
	}
}

func (s *Server) buildRoadmapGroup() ToolGroup {
	return ToolGroup{
		Name:        "roadmap",
		Description: "Roadmap automation: parse, analyze, research, expand, export",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_roadmap_parse",
				mcp.WithDescription("Parse ROADMAP.md into structured JSON (phases, sections, tasks, deps, completion stats)"),
				mcp.WithString("path", mcp.Required(), mcp.Description("Repo root or direct .md path")),
				mcp.WithString("file", mcp.Description("Override filename (default: ROADMAP.md)")),
			), s.handleRoadmapParse},
			{mcp.NewTool("ralphglasses_roadmap_analyze",
				mcp.WithDescription("Compare roadmap vs codebase — find gaps, stale checkboxes, ready tasks, orphaned code"),
				mcp.WithString("path", mcp.Required(), mcp.Description("Repo root path")),
				mcp.WithString("file", mcp.Description("Override filename (default: ROADMAP.md)")),
			), s.handleRoadmapAnalyze},
			{mcp.NewTool("ralphglasses_roadmap_research",
				mcp.WithDescription("Search GitHub for relevant repos and tools that unlock new capabilities"),
				mcp.WithString("path", mcp.Required(), mcp.Description("Repo root path")),
				mcp.WithString("topics", mcp.Description("Search topics (inferred from go.mod/README if omitted)")),
				mcp.WithNumber("limit", mcp.Description("Max results (default 10)")),
			), s.handleRoadmapResearch},
			{mcp.NewTool("ralphglasses_roadmap_expand",
				mcp.WithDescription("Generate proposed roadmap expansions from analysis gaps and research findings"),
				mcp.WithString("path", mcp.Required(), mcp.Description("Repo root path")),
				mcp.WithString("file", mcp.Description("Override filename (default: ROADMAP.md)")),
				mcp.WithString("research", mcp.Description("Research topics to include (runs research internally)")),
				mcp.WithString("style", mcp.Description("Expansion style: conservative, balanced, aggressive (default: balanced)")),
			), s.handleRoadmapExpand},
			{mcp.NewTool("ralphglasses_roadmap_export",
				mcp.WithDescription("Export roadmap items as structured task specs for ralph loop consumption"),
				mcp.WithString("path", mcp.Required(), mcp.Description("Repo root path")),
				mcp.WithString("file", mcp.Description("Override filename (default: ROADMAP.md)")),
				mcp.WithString("format", mcp.Description("Output format: rdcycle, fix_plan, progress (default: rdcycle)")),
				mcp.WithString("phase", mcp.Description("Filter by phase name (default: all)")),
				mcp.WithString("section", mcp.Description("Filter by section name (default: all)")),
				mcp.WithNumber("max_tasks", mcp.Description("Max tasks to export (default 20)")),
				mcp.WithString("respect_deps", mcp.Description("Skip tasks with unmet deps (default: true)")),
			), s.handleRoadmapExport},
		},
	}
}

func (s *Server) buildTeamGroup() ToolGroup {
	return ToolGroup{
		Name:        "team",
		Description: "Agent teams and definitions: team_create, team_status, team_delegate, agent_define, agent_list, agent_compose",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_team_create",
				mcp.WithDescription("Create an agent team with a lead session that delegates tasks to teammates"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("name", mcp.Required(), mcp.Description("Team name")),
				mcp.WithString("tasks", mcp.Required(), mcp.Description("Newline-separated task descriptions")),
				mcp.WithString("provider", mcp.Description("LLM provider for lead: claude (default), gemini, codex")),
				mcp.WithString("worker_provider", mcp.Description("Default LLM provider for worker tasks: claude, gemini, codex")),
				mcp.WithString("lead_agent", mcp.Description("Agent definition for the lead (from .claude/agents/)")),
				mcp.WithString("model", mcp.Description("Model for lead session")),
				mcp.WithNumber("max_budget_usd", mcp.Description("Total budget for the team")),
				mcp.WithBoolean("dry_run", mcp.Description("Return team configuration without launching sessions")),
			), s.handleTeamCreate},
			{mcp.NewTool("ralphglasses_team_status",
				mcp.WithDescription("Get team status including lead session, tasks, and progress"),
				mcp.WithString("name", mcp.Required(), mcp.Description("Team name")),
			), s.handleTeamStatus},
			{mcp.NewTool("ralphglasses_team_delegate",
				mcp.WithDescription("Add a new task to an existing team"),
				mcp.WithString("name", mcp.Required(), mcp.Description("Team name")),
				mcp.WithString("task", mcp.Required(), mcp.Description("Task description to delegate")),
				mcp.WithString("provider", mcp.Description("LLM provider override for this task: claude, gemini, codex")),
			), s.handleTeamDelegate},
			{mcp.NewTool("ralphglasses_agent_define",
				mcp.WithDescription("Create or update an agent definition for a repo (supports all providers)"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("name", mcp.Required(), mcp.Description("Agent name")),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("Agent system prompt / instructions (markdown)")),
				mcp.WithString("provider", mcp.Description("Target provider: claude (default, .claude/agents/), gemini (.gemini/agents/), codex (AGENTS.md)")),
				mcp.WithString("description", mcp.Description("Agent description")),
				mcp.WithString("model", mcp.Description("Model override (sonnet, opus, haiku)")),
				mcp.WithString("tools", mcp.Description("Comma-separated allowed tools")),
				mcp.WithNumber("max_turns", mcp.Description("Max turns for this agent")),
			), s.handleAgentDefine},
			{mcp.NewTool("ralphglasses_agent_list",
				mcp.WithDescription("List available agent definitions for a repo (supports all providers)"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("provider", mcp.Description("Filter by provider: claude (default), gemini, codex, or 'all'")),
			), s.handleAgentList},
			{mcp.NewTool("ralphglasses_agent_compose",
				mcp.WithDescription("Create a composite agent by layering multiple existing agent definitions"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("name", mcp.Required(), mcp.Description("Name for the composite agent")),
				mcp.WithString("agents", mcp.Required(), mcp.Description("Comma-separated agent names to compose")),
				mcp.WithString("provider", mcp.Description("Provider: claude (default), gemini, codex")),
				mcp.WithString("model", mcp.Description("Override model for composite agent")),
			), s.handleAgentCompose},
		},
	}
}

func (s *Server) buildAwesomeGroup() ToolGroup {
	return ToolGroup{
		Name:        "awesome",
		Description: "Awesome-list research: fetch, analyze, diff, report, sync",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_awesome_fetch",
				mcp.WithDescription("Fetch and parse an awesome-list README into structured entries with categories"),
				mcp.WithString("repo", mcp.Description("GitHub repo (default: hesreallyhim/awesome-claude-code)")),
			), s.handleAwesomeFetch},
			{mcp.NewTool("ralphglasses_awesome_analyze",
				mcp.WithDescription("Deep-analyze repos: fetch READMEs, score value/complexity vs ralph capabilities"),
				mcp.WithString("repo", mcp.Description("GitHub repo (default: hesreallyhim/awesome-claude-code)")),
				mcp.WithNumber("max_workers", mcp.Description("Concurrent README fetches (default 5)")),
			), s.handleAwesomeAnalyze},
			{mcp.NewTool("ralphglasses_awesome_diff",
				mcp.WithDescription("Compare current awesome-list against previous fetch (new/removed entries)"),
				mcp.WithString("save_to", mcp.Required(), mcp.Description("Repo path where previous index is saved")),
				mcp.WithString("repo", mcp.Description("GitHub repo (default: hesreallyhim/awesome-claude-code)")),
			), s.handleAwesomeDiff},
			{mcp.NewTool("ralphglasses_awesome_report",
				mcp.WithDescription("Generate formatted report from saved analysis results"),
				mcp.WithString("save_to", mcp.Required(), mcp.Description("Repo path where analysis is saved")),
				mcp.WithString("format", mcp.Description("Output format: json or markdown (default: markdown)")),
			), s.handleAwesomeReport},
			{mcp.NewTool("ralphglasses_awesome_sync",
				mcp.WithDescription("Full pipeline: fetch awesome-list → diff → analyze new entries → report → save"),
				mcp.WithString("save_to", mcp.Required(), mcp.Description("Repo path to save results")),
				mcp.WithString("repo", mcp.Description("GitHub repo (default: hesreallyhim/awesome-claude-code)")),
				mcp.WithString("full_rescan", mcp.Description("Re-analyze all entries, not just new: true/false (default: false)")),
				mcp.WithNumber("max_workers", mcp.Description("Concurrent README fetches (default 5)")),
			), s.handleAwesomeSync},
		},
	}
}

func (s *Server) buildAdvancedGroup() ToolGroup {
	return ToolGroup{
		Name:        "advanced",
		Description: "Advanced: RC tools, events, HITL, autonomy, feedback, provider recommend, journals, workflows, tool benchmark",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_rc_status",
				mcp.WithDescription("Compact fleet overview for mobile: active sessions, costs, alerts in readable text"),
			), s.handleRCStatus},
			{mcp.NewTool("ralphglasses_rc_send",
				mcp.WithDescription("Send prompt to repo — auto-stops existing session, launches new. The 'input' tool for remote control."),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("prompt", mcp.Required(), mcp.Description("What to tell the agent")),
				mcp.WithString("provider", mcp.Description("claude (default), gemini, codex")),
				mcp.WithString("model", mcp.Description("Override model")),
				mcp.WithNumber("budget", mcp.Description("Max budget USD (default: 5)")),
				mcp.WithString("resume", mcp.Description("true to resume last session instead of fresh start")),
			), s.handleRCSend},
			{mcp.NewTool("ralphglasses_rc_read",
				mcp.WithDescription("Read recent output from most active session. Combines tail + status for mobile."),
				mcp.WithString("id", mcp.Description("Session ID (omit for most recently active)")),
				mcp.WithString("cursor", mcp.Description("Cursor from previous call — only new output")),
				mcp.WithNumber("lines", mcp.Description("Max lines (default 10, max 30)")),
			), s.handleRCRead},
			{mcp.NewTool("ralphglasses_rc_act",
				mcp.WithDescription("Quick fleet action: stop, stop_all, pause, resume, retry. Single tool for all control actions."),
				mcp.WithString("action", mcp.Required(), mcp.Description("Action: stop, stop_all, pause, resume, retry")),
				mcp.WithString("target", mcp.Description("Session ID or repo name (required except stop_all)")),
			), s.handleRCAct},
			{mcp.NewTool("ralphglasses_event_list",
				mcp.WithDescription("Query recent fleet events from the event bus"),
				mcp.WithString("type", mcp.Description("Filter by event type (e.g. session.started, cost.update)")),
				mcp.WithString("types", mcp.Description("Comma-separated event types to filter (OR). Alternative to single 'type' param")),
				mcp.WithString("repo", mcp.Description("Filter by repo name")),
				mcp.WithNumber("limit", mcp.Description("Max events to return (default 50)")),
				mcp.WithString("since", mcp.Description("ISO timestamp filter")),
				mcp.WithString("until", mcp.Description("ISO timestamp upper bound (exclusive)")),
				mcp.WithString("session_id", mcp.Description("Filter by session ID")),
				mcp.WithString("provider", mcp.Description("Filter by provider")),
				mcp.WithNumber("offset", mcp.Description("Skip first N results for pagination (default 0)")),
			), s.handleEventList},
			{mcp.NewTool("ralphglasses_event_poll",
				mcp.WithDescription("Poll for new fleet events since last check. Cursor-based for efficient mobile polling."),
				mcp.WithString("cursor", mcp.Description("Cursor from previous response (omit for recent)")),
				mcp.WithNumber("limit", mcp.Description("Max events (default 20, max 50)")),
				mcp.WithString("type", mcp.Description("Filter by event type (e.g. session.started, cost.update)")),
			), s.handleEventPoll},
			{mcp.NewTool("ralphglasses_hitl_score",
				mcp.WithDescription("Current human-in-the-loop score: manual interventions vs autonomous actions, with trend"),
				mcp.WithNumber("hours", mcp.Description("Time window in hours (default: 24)")),
			), s.handleHITLScore},
			{mcp.NewTool("ralphglasses_hitl_history",
				mcp.WithDescription("Recent HITL events: manual stops, auto-recoveries, config changes, etc."),
				mcp.WithNumber("hours", mcp.Description("Time window in hours (default: 24)")),
				mcp.WithNumber("limit", mcp.Description("Max events (default: 50)")),
			), s.handleHITLHistory},
			{mcp.NewTool("ralphglasses_autonomy_level",
				mcp.WithDescription("View or set the autonomy level (0=observe, 1=auto-recover, 2=auto-optimize, 3=full-autonomy)"),
				mcp.WithString("level", mcp.Description("New level: 0-3 or name (omit to view current)")),
			), s.handleAutonomyLevel},
			{mcp.NewTool("ralphglasses_autonomy_decisions",
				mcp.WithDescription("Recent autonomous decisions with rationale, inputs, and outcomes"),
				mcp.WithNumber("limit", mcp.Description("Max decisions (default: 20)")),
			), s.handleAutonomyDecisions},
			{mcp.NewTool("ralphglasses_autonomy_override",
				mcp.WithDescription("Override/reverse an autonomous decision and record human intervention"),
				mcp.WithString("decision_id", mcp.Required(), mcp.Description("Decision ID to override")),
				mcp.WithString("details", mcp.Description("Why this was overridden")),
			), s.handleAutonomyOverride},
			{mcp.NewTool("ralphglasses_feedback_profiles",
				mcp.WithDescription("View feedback profiles: per-task-type and per-provider performance data from journal analysis"),
				mcp.WithString("type", mcp.Description("Filter: prompt, provider, or omit for both")),
			), s.handleFeedbackProfiles},
			{mcp.NewTool("ralphglasses_provider_recommend",
				mcp.WithDescription("Recommend best provider + model + budget for a task based on feedback profiles and cost normalization"),
				mcp.WithString("task", mcp.Required(), mcp.Description("Task description (e.g. 'fix lint errors', 'add search feature')")),
			), s.handleProviderRecommend},
			{mcp.NewTool("ralphglasses_tool_benchmark",
				mcp.WithDescription("Per-tool performance benchmarks: latency percentiles, success rates, and regression detection"),
				mcp.WithString("tool", mcp.Description("Filter to a specific tool name")),
				mcp.WithString("compare", mcp.Description("Include regression analysis vs previous baseline: true/false (default: false)")),
				mcp.WithNumber("hours", mcp.Description("Time window in hours (default 24)")),
			), s.handleToolBenchmark},
			{mcp.NewTool("ralphglasses_journal_read",
				mcp.WithDescription("Read improvement journal entries for a repo with synthesized context"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("limit", mcp.Description("Max entries to return (default 10)")),
			), s.handleJournalRead},
			{mcp.NewTool("ralphglasses_journal_write",
				mcp.WithDescription("Manually write an improvement note to a repo's journal"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("worked", mcp.Description("Comma-separated items that worked")),
				mcp.WithString("failed", mcp.Description("Comma-separated items that failed")),
				mcp.WithString("suggest", mcp.Description("Comma-separated suggestions")),
				mcp.WithString("session_id", mcp.Description("Associated session ID (optional)")),
			), s.handleJournalWrite},
			{mcp.NewTool("ralphglasses_journal_prune",
				mcp.WithDescription("Compact improvement journal to prevent unbounded growth"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("keep", mcp.Description("Number of entries to keep (default 100)")),
				mcp.WithString("dry_run", mcp.Description("Preview only, don't modify: true/false (default: true)")),
			), s.handleJournalPrune},
			{mcp.NewTool("ralphglasses_workflow_define",
				mcp.WithDescription("Define a multi-step workflow as YAML"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("name", mcp.Required(), mcp.Description("Workflow name")),
				mcp.WithString("yaml", mcp.Required(), mcp.Description("Workflow YAML definition")),
			), s.handleWorkflowDefine},
			{mcp.NewTool("ralphglasses_workflow_run",
				mcp.WithDescription("Execute a defined workflow, launching sessions per step"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithString("name", mcp.Required(), mcp.Description("Workflow name")),
			), s.handleWorkflowRun},
			{mcp.NewTool("ralphglasses_bandit_status",
				mcp.WithDescription("View multi-armed bandit arm statistics for provider selection"),
			), s.handleBanditStatus},
			{mcp.NewTool("ralphglasses_confidence_calibration",
				mcp.WithDescription("View calibrated confidence model weights, training status, and feature importances"),
			), s.handleConfidenceCalibration},
			{mcp.NewTool("ralphglasses_circuit_reset",
				mcp.WithDescription("Reset circuit breaker state for a named service, re-enabling requests after failures. Use 'enhancer' for the LLM prompt enhancer circuit breaker, or a repo name for its file-based circuit breaker."),
				mcp.WithString("service", mcp.Required(), mcp.Description("Service/circuit to reset: 'enhancer' or a repo name")),
			), s.handleCircuitReset},
		},
	}
}

func (s *Server) buildEvalGroup() ToolGroup {
	return ToolGroup{
		Name:        "eval",
		Description: "Offline evaluation: counterfactual analysis, Bayesian A/B testing, changepoint detection",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_eval_counterfactual",
				mcp.WithDescription("Estimate outcomes under hypothetical policy changes using inverse propensity scoring on loop observations"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Observation window in hours (default: 168 = 7 days)")),
				mcp.WithString("policy", mcp.Required(), mcp.Description("Policy type: cascade_threshold or provider_routing")),
				mcp.WithNumber("threshold", mcp.Description("New cascade threshold for cascade_threshold policy (default: 0.6)")),
				mcp.WithString("task_type", mcp.Description("Task type for provider_routing policy")),
				mcp.WithString("provider", mcp.Description("Target provider for provider_routing policy")),
			), s.handleEvalCounterfactual},
			{mcp.NewTool("ralphglasses_eval_ab_test",
				mcp.WithDescription("Bayesian A/B test comparing providers or time periods using Beta-Bernoulli model"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Observation window in hours (default: 168)")),
				mcp.WithString("mode", mcp.Required(), mcp.Description("Comparison mode: providers or periods")),
				mcp.WithString("provider_a", mcp.Description("First provider (providers mode)")),
				mcp.WithString("provider_b", mcp.Description("Second provider (providers mode)")),
				mcp.WithNumber("split_hours_ago", mcp.Description("Hours ago to split time periods (periods mode)")),
			), s.handleEvalABTest},
			{mcp.NewTool("ralphglasses_eval_changepoints",
				mcp.WithDescription("Detect performance shifts using CUSUM changepoint detection on loop observations"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Observation window in hours (default: 168)")),
				mcp.WithString("metric", mcp.Description("Specific metric to analyze (completion_rate, cost, latency, confidence, difficulty). Omit for all.")),
			), s.handleEvalChangepoints},
			{mcp.NewTool("ralphglasses_anomaly_detect",
				mcp.WithDescription("Detect anomalies in metric streams using sliding-window z-score analysis"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Observation window in hours (default: 168)")),
				mcp.WithString("metric", mcp.Required(), mcp.Description("Metric to analyze (total_cost_usd, confidence, difficulty_score, etc)")),
			), s.handleAnomalyDetect},
		},
	}
}

func (s *Server) buildFleetHGroup() ToolGroup {
	return ToolGroup{
		Name:        "fleet_h",
		Description: "Fleet intelligence: blackboard coordination, A2A task delegation, cost forecasting",
		Tools: []ToolEntry{
			{mcp.NewTool("ralphglasses_blackboard_query",
				mcp.WithDescription("Query blackboard entries by namespace for fleet worker coordination. Requires fleet server mode (ralphglasses mcp --fleet)."),
				mcp.WithString("namespace", mcp.Required(), mcp.Description("Namespace to query")),
			), s.handleBlackboardQuery},
			{mcp.NewTool("ralphglasses_blackboard_put",
				mcp.WithDescription("Write an entry to the blackboard for fleet coordination. Requires fleet server mode (ralphglasses mcp --fleet)."),
				mcp.WithString("namespace", mcp.Required(), mcp.Description("Entry namespace")),
				mcp.WithString("key", mcp.Required(), mcp.Description("Entry key")),
				mcp.WithString("value", mcp.Required(), mcp.Description("JSON object value")),
				mcp.WithString("writer_id", mcp.Description("Writer identifier")),
				mcp.WithNumber("ttl_seconds", mcp.Description("Time-to-live in seconds (0 for no expiry)")),
			), s.handleBlackboardPut},
			{mcp.NewTool("ralphglasses_a2a_offers",
				mcp.WithDescription("List open agent-to-agent task delegation offers. Requires fleet server mode (ralphglasses mcp --fleet)."),
			), s.handleA2AOffers},
			{mcp.NewTool("ralphglasses_cost_forecast",
				mcp.WithDescription("Cost burn rate, anomaly detection, and budget exhaustion ETA. Requires fleet server mode (ralphglasses mcp --fleet)."),
				mcp.WithNumber("budget_remaining", mcp.Description("Remaining budget in USD (default: 0)")),
			), s.handleCostForecast},
		},
	}
}

func (s *Server) buildObservabilityGroup() ToolGroup {
	return ToolGroup{
		Name:        "observability",
		Description: "Observation queries, scratchpad automation, loop wait/poll, coverage, cost estimation, merge verification",
		Tools: []ToolEntry{
			// Observation query tools
			{mcp.NewTool("ralphglasses_observation_query",
				mcp.WithDescription("Filter and paginate loop observations from .ralph/logs/loop_observations.jsonl"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Hours of history to query (default 48)")),
				mcp.WithString("loop_id", mcp.Description("Filter by loop ID")),
				mcp.WithString("status", mcp.Description("Filter by status (pass, fail, error)")),
				mcp.WithString("provider", mcp.Description("Filter by provider")),
				mcp.WithNumber("limit", mcp.Description("Max results (default 50, max 500)")),
				mcp.WithString("since", mcp.Description("RFC3339 timestamp lower bound (overrides hours if set)")),
				mcp.WithString("until", mcp.Description("RFC3339 timestamp upper bound")),
			), s.handleObservationQuery},
			{mcp.NewTool("ralphglasses_observation_summary",
				mcp.WithDescription("Aggregate observation stats with p50/p95/p99 percentiles via SummarizeObservations"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name")),
				mcp.WithNumber("hours", mcp.Description("Hours of history (default 48)")),
				mcp.WithString("loop_id", mcp.Description("Filter by loop ID")),
				mcp.WithString("since", mcp.Description("RFC3339 timestamp lower bound (overrides hours if set)")),
				mcp.WithString("until", mcp.Description("RFC3339 timestamp upper bound")),
			), s.handleObservationSummary},

			// Scratchpad tools
			{mcp.NewTool("ralphglasses_scratchpad_read",
				mcp.WithDescription("Read a .ralph/{name}_scratchpad.md file"),
				mcp.WithString("name", mcp.Required(), mcp.Description("Scratchpad name (e.g. 'tool_improvement')")),
				mcp.WithString("repo", mcp.Description("Repo name (default: first discovered)")),
			), s.handleScratchpadRead},
			{mcp.NewTool("ralphglasses_scratchpad_append",
				mcp.WithDescription("Append a markdown note to a scratchpad file"),
				mcp.WithString("name", mcp.Required(), mcp.Description("Scratchpad name")),
				mcp.WithString("content", mcp.Required(), mcp.Description("Markdown content to append")),
				mcp.WithString("section", mcp.Description("Optional section header to add before content")),
				mcp.WithString("repo", mcp.Description("Repo name (default: first discovered)")),
			), s.handleScratchpadAppend},
			{mcp.NewTool("ralphglasses_scratchpad_list",
				mcp.WithDescription("List all scratchpad files in .ralph/"),
				mcp.WithString("repo", mcp.Description("Repo name (default: first discovered)")),
			), s.handleScratchpadList},
			{mcp.NewTool("ralphglasses_scratchpad_resolve",
				mcp.WithDescription("Mark a numbered scratchpad item as resolved"),
				mcp.WithString("name", mcp.Required(), mcp.Description("Scratchpad name")),
				mcp.WithNumber("item_number", mcp.Required(), mcp.Description("Item number to resolve")),
				mcp.WithString("resolution", mcp.Required(), mcp.Description("Resolution description")),
				mcp.WithString("repo", mcp.Description("Repo name (default: first discovered)")),
			), s.handleScratchpadResolve},

			// Loop wait/poll tools
			{mcp.NewTool("ralphglasses_loop_await",
				mcp.WithDescription("Block until a session or loop completes (replaces sleep anti-pattern)"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session or loop ID to wait for")),
				mcp.WithString("type", mcp.Required(), mcp.Description("'session' or 'loop'")),
				mcp.WithNumber("timeout_seconds", mcp.Description("Max wait time in seconds (default 300)")),
				mcp.WithNumber("poll_interval_seconds", mcp.Description("Poll interval in seconds (default 10, min 5)")),
			), s.handleLoopAwait},
			{mcp.NewTool("ralphglasses_loop_poll",
				mcp.WithDescription("Non-blocking single status check for a session or loop"),
				mcp.WithString("id", mcp.Required(), mcp.Description("Session or loop ID")),
				mcp.WithString("type", mcp.Required(), mcp.Description("'session' or 'loop'")),
			), s.handleLoopPoll},

			// Coverage report
			{mcp.NewTool("ralphglasses_coverage_report",
				mcp.WithDescription("Run go test -coverprofile and report per-package coverage vs threshold"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo name or absolute path")),
				mcp.WithString("packages", mcp.Description("Package pattern (default ./...)")),
				mcp.WithNumber("threshold", mcp.Description("Coverage threshold percentage (default 70)")),
			), s.handleCoverageReport},

			// Cost estimation
			{mcp.NewTool("ralphglasses_cost_estimate",
				mcp.WithDescription("Pre-launch cost estimate for a session or loop"),
				mcp.WithString("provider", mcp.Required(), mcp.Description("Provider: claude, gemini, or codex")),
				mcp.WithString("model", mcp.Description("Model name (uses provider default if omitted)")),
				mcp.WithNumber("prompt_tokens", mcp.Description("Prompt length in tokens (default 5000)")),
				mcp.WithNumber("turns", mcp.Description("Expected conversation turns (default 5)")),
				mcp.WithNumber("output_tokens_per_turn", mcp.Description("Output tokens per turn (default 2000)")),
				mcp.WithString("mode", mcp.Description("'session' or 'loop' (default session)")),
				mcp.WithNumber("iterations", mcp.Description("Loop iterations for mode=loop (default 3)")),
				mcp.WithString("repo", mcp.Description("Repo name for historical calibration")),
			), s.handleCostEstimate},

			// Merge verification
			{mcp.NewTool("ralphglasses_merge_verify",
				mcp.WithDescription("Run build+vet+test sequence to verify a merge"),
				mcp.WithString("repo", mcp.Required(), mcp.Description("Repo path (absolute)")),
				mcp.WithBoolean("fast", mcp.Description("Use -short flag for faster tests")),
				mcp.WithBoolean("coverage", mcp.Description("Include coverage profile")),
				mcp.WithString("packages", mcp.Description("Package pattern to test (default ./...)")),
				mcp.WithBoolean("race", mcp.Description("Enable -race detector (default true)")),
			), s.handleMergeVerify},
		},
	}
}
