package themekit

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ExportBat writes a bat/delta-compatible Catppuccin theme configuration.
// bat uses tmTheme (TextMate) format. Rather than generating the full XML,
// we configure bat to use the built-in Catppuccin theme and set up delta
// to match.
func ExportBat(p Palette) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}

	configDir := filepath.Join(home, ".config", "bat")
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		return "", fmt.Errorf("create bat config dir: %w", err)
	}

	// Map flavor to bat's built-in Catppuccin theme name
	batTheme := batThemeName(p.Name)

	configPath := filepath.Join(configDir, "config")

	// Read existing config, filter out theme lines
	var preserved []string
	if data, err := os.ReadFile(configPath); err == nil {
		for _, line := range strings.Split(string(data), "\n") {
			trimmed := strings.TrimSpace(line)
			if !strings.HasPrefix(trimmed, "--theme=") {
				preserved = append(preserved, line)
			}
		}
	}

	// Remove trailing empty lines
	for len(preserved) > 0 && strings.TrimSpace(preserved[len(preserved)-1]) == "" {
		preserved = preserved[:len(preserved)-1]
	}

	preserved = append(preserved, "")
	preserved = append(preserved, "# claudekit: Catppuccin theme")
	preserved = append(preserved, fmt.Sprintf("--theme=%s", batTheme))
	preserved = append(preserved, "")

	if err := os.WriteFile(configPath, []byte(strings.Join(preserved, "\n")), 0o644); err != nil {
		return "", fmt.Errorf("write bat config: %w", err)
	}

	return configPath, nil
}

// ExportDelta writes delta (git pager) configuration with Catppuccin colors.
func ExportDelta(p Palette) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}

	// Delta reads from .gitconfig [delta] section
	// We write a delta-specific config that can be included
	configDir := filepath.Join(home, ".config", "delta")
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		return "", fmt.Errorf("create delta config dir: %w", err)
	}

	hex := func(name string) string {
		return "#" + p.Get(name).Hex
	}

	var b strings.Builder
	b.WriteString("# " + p.Name + " delta theme (generated by claudekit)\n")
	b.WriteString("# Include in .gitconfig: [include] path = ~/.config/delta/catppuccin.gitconfig\n\n")
	b.WriteString("[delta]\n")
	b.WriteString(fmt.Sprintf("    syntax-theme = %s\n", batThemeName(p.Name)))
	b.WriteString(fmt.Sprintf("    minus-style = syntax %s\n", hex("red")))
	b.WriteString(fmt.Sprintf("    minus-emph-style = syntax bold %s\n", hex("maroon")))
	b.WriteString(fmt.Sprintf("    plus-style = syntax %s\n", hex("green")))
	b.WriteString(fmt.Sprintf("    plus-emph-style = syntax bold %s\n", hex("teal")))
	b.WriteString(fmt.Sprintf("    hunk-header-style = syntax bold %s\n", hex("blue")))
	b.WriteString(fmt.Sprintf("    line-numbers-minus-style = %s\n", hex("red")))
	b.WriteString(fmt.Sprintf("    line-numbers-plus-style = %s\n", hex("green")))
	b.WriteString(fmt.Sprintf("    line-numbers-zero-style = %s\n", hex("overlay0")))

	configPath := filepath.Join(configDir, "catppuccin.gitconfig")
	if err := os.WriteFile(configPath, []byte(b.String()), 0o644); err != nil {
		return "", fmt.Errorf("write delta config: %w", err)
	}

	return configPath, nil
}

func batThemeName(paletteName string) string {
	// bat bundles Catppuccin themes with these names
	switch {
	case strings.Contains(paletteName, "Latte"):
		return "Catppuccin Latte"
	case strings.Contains(paletteName, "Frap"):
		return "Catppuccin Frappe"
	case strings.Contains(paletteName, "Macchiato"):
		return "Catppuccin Macchiato"
	default:
		return "Catppuccin Mocha"
	}
}
