package themekit

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ExportGhostty writes a Catppuccin theme to the Ghostty themes directory.
func ExportGhostty(p Palette) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}

	themeDir := filepath.Join(home, ".config", "ghostty", "themes")
	if err := os.MkdirAll(themeDir, 0o755); err != nil {
		return "", fmt.Errorf("create ghostty themes dir: %w", err)
	}

	var b strings.Builder
	b.WriteString("# " + p.Name + " (generated by claudekit)\n\n")

	hex := func(name string) string {
		return "#" + p.Get(name).Hex
	}

	// Ghostty theme format
	lines := []string{
		"background = " + hex("base"),
		"foreground = " + hex("text"),
		"cursor-color = " + hex("rosewater"),
		"cursor-text = " + hex("base"),
		"selection-background = " + hex("surface2"),
		"selection-foreground = " + hex("text"),
		"",
		"# ANSI normal",
		"palette = 0=" + hex("surface1"),
		"palette = 1=" + hex("red"),
		"palette = 2=" + hex("green"),
		"palette = 3=" + hex("yellow"),
		"palette = 4=" + hex("blue"),
		"palette = 5=" + hex("pink"),
		"palette = 6=" + hex("teal"),
		"palette = 7=" + hex("subtext1"),
		"",
		"# ANSI bright",
		"palette = 8=" + hex("surface2"),
		"palette = 9=" + hex("red"),
		"palette = 10=" + hex("green"),
		"palette = 11=" + hex("yellow"),
		"palette = 12=" + hex("blue"),
		"palette = 13=" + hex("pink"),
		"palette = 14=" + hex("teal"),
		"palette = 15=" + hex("subtext0"),
	}

	for _, line := range lines {
		b.WriteString(line + "\n")
	}

	safeName := strings.ReplaceAll(strings.ToLower(p.Name), " ", "-")
	outPath := filepath.Join(themeDir, "claudekit-"+safeName)
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		return "", fmt.Errorf("write ghostty theme: %w", err)
	}

	return outPath, nil
}
