package themekit

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ExportStarship writes a Catppuccin-themed Starship prompt configuration
// to ~/.config/starship.toml. Existing non-claudekit config lines are preserved.
func ExportStarship(p Palette) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}

	configDir := filepath.Join(home, ".config")
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		return "", fmt.Errorf("create config dir: %w", err)
	}

	configPath := filepath.Join(configDir, "starship.toml")

	// Read existing config, strip claudekit-managed sections
	preserved := preserveNonClaudekit(configPath)

	// Generate claudekit Starship config
	generated := generateStarshipTOML(p)

	var b strings.Builder
	if len(preserved) > 0 {
		b.WriteString(preserved)
		if !strings.HasSuffix(preserved, "\n\n") {
			b.WriteString("\n")
		}
	}
	b.WriteString(generated)

	if err := os.WriteFile(configPath, []byte(b.String()), 0o644); err != nil {
		return "", fmt.Errorf("write starship config: %w", err)
	}

	return configPath, nil
}

// preserveNonClaudekit reads the existing starship.toml and returns content
// outside of claudekit-managed blocks (delimited by # claudekit:begin / # claudekit:end).
func preserveNonClaudekit(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}

	lines := strings.Split(string(data), "\n")
	var kept []string
	inBlock := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "# claudekit:begin" {
			inBlock = true
			continue
		}
		if trimmed == "# claudekit:end" {
			inBlock = false
			continue
		}
		if !inBlock {
			kept = append(kept, line)
		}
	}

	// Trim trailing empty lines
	for len(kept) > 0 && strings.TrimSpace(kept[len(kept)-1]) == "" {
		kept = kept[:len(kept)-1]
	}

	if len(kept) == 0 {
		return ""
	}
	return strings.Join(kept, "\n") + "\n"
}

// generateStarshipTOML produces the claudekit-managed Starship TOML block.
func generateStarshipTOML(p Palette) string {
	hex := func(name string) string {
		return "#" + p.Get(name).Hex
	}

	bold := func(name string) string {
		return "bold " + hex(name)
	}

	var b strings.Builder
	b.WriteString("# claudekit:begin\n")
	b.WriteString(fmt.Sprintf("# %s Starship theme (generated by claudekit)\n\n", p.Name))

	// Format string (prompt layout)
	b.WriteString("format = \"\"\"$directory$git_branch$git_status$golang$nodejs$python$rust$time$line_break$character\"\"\"\n\n")

	// Character module
	b.WriteString("[character]\n")
	b.WriteString(fmt.Sprintf("success_symbol = \"[❯](%s)\"\n", bold("green")))
	b.WriteString(fmt.Sprintf("error_symbol = \"[❯](%s)\"\n", bold("red")))
	b.WriteString("\n")

	// Directory module
	b.WriteString("[directory]\n")
	b.WriteString(fmt.Sprintf("style = \"%s\"\n", bold("blue")))
	b.WriteString("truncation_length = 3\n")
	b.WriteString(fmt.Sprintf("truncation_symbol = \"…/\"\n"))
	b.WriteString("\n")

	// Git branch
	b.WriteString("[git_branch]\n")
	b.WriteString("symbol = \"\ue725 \"\n")
	b.WriteString(fmt.Sprintf("style = \"%s\"\n", bold("mauve")))
	b.WriteString("\n")

	// Git status
	b.WriteString("[git_status]\n")
	b.WriteString(fmt.Sprintf("style = \"%s\"\n", bold("peach")))
	b.WriteString(fmt.Sprintf("ahead = \"⇡$${count}\"\n"))
	b.WriteString(fmt.Sprintf("behind = \"⇣$${count}\"\n"))
	b.WriteString(fmt.Sprintf("diverged = \"⇕⇡$${ahead_count}⇣$${behind_count}\"\n"))
	b.WriteString("\n")

	// Golang
	b.WriteString("[golang]\n")
	b.WriteString("symbol = \"\ue627 \"\n")
	b.WriteString(fmt.Sprintf("style = \"%s\"\n", bold("sapphire")))
	b.WriteString("\n")

	// Node.js
	b.WriteString("[nodejs]\n")
	b.WriteString("symbol = \"\ue718 \"\n")
	b.WriteString(fmt.Sprintf("style = \"%s\"\n", bold("green")))
	b.WriteString("\n")

	// Python
	b.WriteString("[python]\n")
	b.WriteString("symbol = \"\ue73c \"\n")
	b.WriteString(fmt.Sprintf("style = \"%s\"\n", bold("yellow")))
	b.WriteString("\n")

	// Rust
	b.WriteString("[rust]\n")
	b.WriteString("symbol = \"\ue7a8 \"\n")
	b.WriteString(fmt.Sprintf("style = \"%s\"\n", bold("peach")))
	b.WriteString("\n")

	// Time
	b.WriteString("[time]\n")
	b.WriteString("disabled = false\n")
	b.WriteString(fmt.Sprintf("style = \"%s\"\n", hex("subtext0")))
	b.WriteString("format = \"[$time]($style) \"\n")
	b.WriteString("time_format = \"%H:%M\"\n")

	b.WriteString("# claudekit:end\n")

	return b.String()
}
