package themekit

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// SyncConfig controls which external tools receive theme exports.
type SyncConfig struct {
	Alacritty bool
	Kitty     bool
	Tmux      bool
	Starship  bool
	Bat       bool
}

// ExportResult captures the outcome of exporting a theme to a single tool.
type ExportResult struct {
	Tool    string
	Path    string
	Content string
	Applied bool
	Error   error
}

// ExportAll generates and writes config snippets for every enabled tool in cfg.
// It always attempts all enabled tools, collecting results even on individual failures.
func ExportAll(palette Palette, cfg SyncConfig) ([]ExportResult, error) {
	type exporter struct {
		name string
		fn   func(Palette) (string, string, error) // returns (path, content, err)
	}

	var targets []exporter
	if cfg.Alacritty {
		targets = append(targets, exporter{"alacritty", exportAlacritty})
	}
	if cfg.Kitty {
		targets = append(targets, exporter{"kitty", exportKitty})
	}
	if cfg.Tmux {
		targets = append(targets, exporter{"tmux", exportTmux})
	}
	if cfg.Starship {
		targets = append(targets, exporter{"starship", func(p Palette) (string, string, error) {
			path, err := ExportStarship(p)
			if err != nil {
				return "", "", err
			}
			data, err := os.ReadFile(path)
			if err != nil {
				return path, "", err
			}
			return path, string(data), nil
		}})
	}
	if cfg.Bat {
		targets = append(targets, exporter{"bat", func(p Palette) (string, string, error) {
			path, err := ExportBat(p)
			if err != nil {
				return "", "", err
			}
			data, err := os.ReadFile(path)
			if err != nil {
				return path, "", err
			}
			return path, string(data), nil
		}})
	}

	results := make([]ExportResult, 0, len(targets))
	var firstErr error

	for _, t := range targets {
		path, content, err := t.fn(palette)
		r := ExportResult{
			Tool:    t.name,
			Path:    path,
			Content: content,
			Applied: err == nil,
			Error:   err,
		}
		results = append(results, r)
		if err != nil && firstErr == nil {
			firstErr = fmt.Errorf("export %s: %w", t.name, err)
		}
	}

	return results, firstErr
}

// exportAlacritty generates an Alacritty TOML color theme and writes it to
// ~/.config/alacritty/catppuccin.toml.
func exportAlacritty(p Palette) (string, string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", "", err
	}

	configDir := filepath.Join(home, ".config", "alacritty")
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		return "", "", fmt.Errorf("create alacritty config dir: %w", err)
	}

	content := generateAlacrittyTOML(p)
	outPath := filepath.Join(configDir, "catppuccin.toml")

	if err := os.WriteFile(outPath, []byte(content), 0o644); err != nil {
		return "", "", fmt.Errorf("write alacritty theme: %w", err)
	}

	return outPath, content, nil
}

func generateAlacrittyTOML(p Palette) string {
	hex := func(name string) string {
		return "\"#" + p.Get(name).Hex + "\""
	}

	var b strings.Builder
	b.WriteString(fmt.Sprintf("# %s Alacritty theme (generated by ralphglasses)\n\n", p.Name))

	b.WriteString("[colors.primary]\n")
	b.WriteString("background = " + hex("base") + "\n")
	b.WriteString("foreground = " + hex("text") + "\n")
	b.WriteString("dim_foreground = " + hex("subtext1") + "\n")
	b.WriteString("bright_foreground = " + hex("text") + "\n")
	b.WriteString("\n")

	b.WriteString("[colors.cursor]\n")
	b.WriteString("text = " + hex("base") + "\n")
	b.WriteString("cursor = " + hex("rosewater") + "\n")
	b.WriteString("\n")

	b.WriteString("[colors.vi_mode_cursor]\n")
	b.WriteString("text = " + hex("base") + "\n")
	b.WriteString("cursor = " + hex("lavender") + "\n")
	b.WriteString("\n")

	b.WriteString("[colors.search.matches]\n")
	b.WriteString("foreground = " + hex("base") + "\n")
	b.WriteString("background = " + hex("subtext0") + "\n")
	b.WriteString("\n")

	b.WriteString("[colors.search.focused_match]\n")
	b.WriteString("foreground = " + hex("base") + "\n")
	b.WriteString("background = " + hex("green") + "\n")
	b.WriteString("\n")

	b.WriteString("[colors.hints.start]\n")
	b.WriteString("foreground = " + hex("base") + "\n")
	b.WriteString("background = " + hex("yellow") + "\n")
	b.WriteString("\n")

	b.WriteString("[colors.hints.end]\n")
	b.WriteString("foreground = " + hex("base") + "\n")
	b.WriteString("background = " + hex("subtext0") + "\n")
	b.WriteString("\n")

	b.WriteString("[colors.selection]\n")
	b.WriteString("text = " + hex("base") + "\n")
	b.WriteString("background = " + hex("surface2") + "\n")
	b.WriteString("\n")

	b.WriteString("[colors.normal]\n")
	b.WriteString("black = " + hex("surface1") + "\n")
	b.WriteString("red = " + hex("red") + "\n")
	b.WriteString("green = " + hex("green") + "\n")
	b.WriteString("yellow = " + hex("yellow") + "\n")
	b.WriteString("blue = " + hex("blue") + "\n")
	b.WriteString("magenta = " + hex("pink") + "\n")
	b.WriteString("cyan = " + hex("teal") + "\n")
	b.WriteString("white = " + hex("subtext1") + "\n")
	b.WriteString("\n")

	b.WriteString("[colors.bright]\n")
	b.WriteString("black = " + hex("surface2") + "\n")
	b.WriteString("red = " + hex("red") + "\n")
	b.WriteString("green = " + hex("green") + "\n")
	b.WriteString("yellow = " + hex("yellow") + "\n")
	b.WriteString("blue = " + hex("blue") + "\n")
	b.WriteString("magenta = " + hex("pink") + "\n")
	b.WriteString("cyan = " + hex("teal") + "\n")
	b.WriteString("white = " + hex("subtext0") + "\n")

	return b.String()
}

// exportKitty generates a Kitty terminal color theme and writes it to
// ~/.config/kitty/catppuccin.conf.
func exportKitty(p Palette) (string, string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", "", err
	}

	configDir := filepath.Join(home, ".config", "kitty")
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		return "", "", fmt.Errorf("create kitty config dir: %w", err)
	}

	content := generateKittyConf(p)
	outPath := filepath.Join(configDir, "catppuccin.conf")

	if err := os.WriteFile(outPath, []byte(content), 0o644); err != nil {
		return "", "", fmt.Errorf("write kitty theme: %w", err)
	}

	return outPath, content, nil
}

func generateKittyConf(p Palette) string {
	hex := func(name string) string {
		return "#" + p.Get(name).Hex
	}

	var b strings.Builder
	b.WriteString(fmt.Sprintf("# %s Kitty theme (generated by ralphglasses)\n", p.Name))
	b.WriteString("# Include in kitty.conf: include catppuccin.conf\n\n")

	b.WriteString("# Basic colors\n")
	b.WriteString("foreground " + hex("text") + "\n")
	b.WriteString("background " + hex("base") + "\n")
	b.WriteString("selection_foreground " + hex("base") + "\n")
	b.WriteString("selection_background " + hex("surface2") + "\n")
	b.WriteString("\n")

	b.WriteString("# Cursor\n")
	b.WriteString("cursor " + hex("rosewater") + "\n")
	b.WriteString("cursor_text_color " + hex("base") + "\n")
	b.WriteString("\n")

	b.WriteString("# URL\n")
	b.WriteString("url_color " + hex("sapphire") + "\n")
	b.WriteString("\n")

	b.WriteString("# Active/inactive window borders\n")
	b.WriteString("active_border_color " + hex("lavender") + "\n")
	b.WriteString("inactive_border_color " + hex("overlay0") + "\n")
	b.WriteString("bell_border_color " + hex("yellow") + "\n")
	b.WriteString("\n")

	b.WriteString("# Tab bar\n")
	b.WriteString("active_tab_foreground " + hex("crust") + "\n")
	b.WriteString("active_tab_background " + hex("mauve") + "\n")
	b.WriteString("inactive_tab_foreground " + hex("text") + "\n")
	b.WriteString("inactive_tab_background " + hex("mantle") + "\n")
	b.WriteString("tab_bar_background " + hex("crust") + "\n")
	b.WriteString("\n")

	b.WriteString("# Marks\n")
	b.WriteString("mark1_foreground " + hex("base") + "\n")
	b.WriteString("mark1_background " + hex("lavender") + "\n")
	b.WriteString("mark2_foreground " + hex("base") + "\n")
	b.WriteString("mark2_background " + hex("mauve") + "\n")
	b.WriteString("mark3_foreground " + hex("base") + "\n")
	b.WriteString("mark3_background " + hex("sapphire") + "\n")
	b.WriteString("\n")

	b.WriteString("# ANSI normal\n")
	b.WriteString("color0 " + hex("surface1") + "\n")
	b.WriteString("color1 " + hex("red") + "\n")
	b.WriteString("color2 " + hex("green") + "\n")
	b.WriteString("color3 " + hex("yellow") + "\n")
	b.WriteString("color4 " + hex("blue") + "\n")
	b.WriteString("color5 " + hex("pink") + "\n")
	b.WriteString("color6 " + hex("teal") + "\n")
	b.WriteString("color7 " + hex("subtext1") + "\n")
	b.WriteString("\n")

	b.WriteString("# ANSI bright\n")
	b.WriteString("color8 " + hex("surface2") + "\n")
	b.WriteString("color9 " + hex("red") + "\n")
	b.WriteString("color10 " + hex("green") + "\n")
	b.WriteString("color11 " + hex("yellow") + "\n")
	b.WriteString("color12 " + hex("blue") + "\n")
	b.WriteString("color13 " + hex("pink") + "\n")
	b.WriteString("color14 " + hex("teal") + "\n")
	b.WriteString("color15 " + hex("subtext0") + "\n")

	return b.String()
}

// exportTmux generates a tmux color theme and writes it to
// ~/.config/tmux/catppuccin.conf.
func exportTmux(p Palette) (string, string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", "", err
	}

	configDir := filepath.Join(home, ".config", "tmux")
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		return "", "", fmt.Errorf("create tmux config dir: %w", err)
	}

	content := generateTmuxConf(p)
	outPath := filepath.Join(configDir, "catppuccin.conf")

	if err := os.WriteFile(outPath, []byte(content), 0o644); err != nil {
		return "", "", fmt.Errorf("write tmux theme: %w", err)
	}

	return outPath, content, nil
}

func generateTmuxConf(p Palette) string {
	hex := func(name string) string {
		return "#" + p.Get(name).Hex
	}

	var b strings.Builder
	b.WriteString(fmt.Sprintf("# %s tmux theme (generated by ralphglasses)\n", p.Name))
	b.WriteString("# Source in tmux.conf: source-file ~/.config/tmux/catppuccin.conf\n\n")

	// Status bar
	b.WriteString("# Status bar\n")
	b.WriteString(fmt.Sprintf("set -g status-style \"bg=%s,fg=%s\"\n", hex("mantle"), hex("text")))
	b.WriteString(fmt.Sprintf("set -g status-left-style \"bg=%s,fg=%s,bold\"\n", hex("blue"), hex("crust")))
	b.WriteString(fmt.Sprintf("set -g status-right-style \"bg=%s,fg=%s\"\n", hex("surface0"), hex("text")))
	b.WriteString("\n")

	// Window status
	b.WriteString("# Window status\n")
	b.WriteString(fmt.Sprintf("set -g window-status-style \"bg=%s,fg=%s\"\n", hex("mantle"), hex("text")))
	b.WriteString(fmt.Sprintf("set -g window-status-current-style \"bg=%s,fg=%s,bold\"\n", hex("surface0"), hex("text")))
	b.WriteString(fmt.Sprintf("set -g window-status-activity-style \"bg=%s,fg=%s\"\n", hex("mantle"), hex("yellow")))
	b.WriteString("\n")

	// Pane borders
	b.WriteString("# Pane borders\n")
	b.WriteString(fmt.Sprintf("set -g pane-border-style \"fg=%s\"\n", hex("surface1")))
	b.WriteString(fmt.Sprintf("set -g pane-active-border-style \"fg=%s\"\n", hex("lavender")))
	b.WriteString("\n")

	// Messages
	b.WriteString("# Messages\n")
	b.WriteString(fmt.Sprintf("set -g message-style \"bg=%s,fg=%s\"\n", hex("surface0"), hex("text")))
	b.WriteString(fmt.Sprintf("set -g message-command-style \"bg=%s,fg=%s\"\n", hex("surface0"), hex("peach")))
	b.WriteString("\n")

	// Mode (copy mode, etc.)
	b.WriteString("# Mode\n")
	b.WriteString(fmt.Sprintf("set -g mode-style \"bg=%s,fg=%s\"\n", hex("surface0"), hex("text")))
	b.WriteString("\n")

	// Clock
	b.WriteString("# Clock\n")
	b.WriteString(fmt.Sprintf("set -g clock-mode-colour \"%s\"\n", hex("blue")))

	return b.String()
}
