package themekit

import (
	"fmt"
	"os"
	"path/filepath"
)

// ExportWezTerm writes a Catppuccin color theme as a Lua table for WezTerm.
// User includes: config.colors = require("claudekit-colors") in their wezterm.lua
func ExportWezTerm(p Palette) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}

	configDir := filepath.Join(home, ".config", "wezterm")
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		return "", fmt.Errorf("create wezterm config dir: %w", err)
	}

	hex := func(name string) string {
		return "#" + p.Get(name).Hex
	}

	content := fmt.Sprintf(`-- %s (generated by claudekit)
return {
  foreground = "%s",
  background = "%s",
  cursor_bg = "%s",
  cursor_fg = "%s",
  selection_bg = "%s",
  selection_fg = "%s",
  ansi = {"%s", "%s", "%s", "%s", "%s", "%s", "%s", "%s"},
  brights = {"%s", "%s", "%s", "%s", "%s", "%s", "%s", "%s"},
}
`,
		p.Name,
		hex("text"), hex("base"),
		hex("rosewater"), hex("base"),
		hex("surface2"), hex("text"),
		// ansi: black, red, green, yellow, blue, magenta, cyan, white
		hex("surface1"), hex("red"), hex("green"), hex("yellow"),
		hex("blue"), hex("pink"), hex("teal"), hex("subtext1"),
		// brights
		hex("surface2"), hex("red"), hex("green"), hex("yellow"),
		hex("blue"), hex("pink"), hex("teal"), hex("subtext0"),
	)

	outPath := filepath.Join(configDir, "claudekit-colors.lua")
	if err := os.WriteFile(outPath, []byte(content), 0o644); err != nil {
		return "", fmt.Errorf("write wezterm theme: %w", err)
	}

	return outPath, nil
}
