package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/hairglasses-studio/ralphglasses/internal/mcpserver"
)

const (
	generatedMarker             = "GENERATED BY tools/genskillsurface; DO NOT EDIT"
	maxAntigravityMarkdownChars = 12000
)

type generatedFile struct {
	RelPath string
	Content []byte
	Mode    os.FileMode
}

type extensionManifestEntry struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
}

type extensionManifest struct {
	Name    string                   `json:"name"`
	Version string                   `json:"version"`
	Files   []extensionManifestEntry `json:"files"`
}

func generateAntigravitySurfaces(repoRoot string) error {
	files, err := buildAntigravityFiles(repoRoot)
	if err != nil {
		return err
	}
	if err := pruneGeneratedAntigravityFiles(repoRoot, files); err != nil {
		return err
	}
	for _, file := range files {
		target := filepath.Join(repoRoot, file.RelPath)
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return fmt.Errorf("create %s: %w", filepath.Dir(target), err)
		}
		mode := file.Mode
		if mode == 0 {
			mode = 0o644
		}
		if err := os.WriteFile(target, file.Content, mode); err != nil {
			return fmt.Errorf("write %s: %w", target, err)
		}
	}
	return nil
}

func generatedAntigravityFiles(repoRoot string) ([]string, error) {
	files, err := buildAntigravityFiles(repoRoot)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(files))
	for _, file := range files {
		out = append(out, file.RelPath)
	}
	return out, nil
}

func buildAntigravityFiles(repoRoot string) ([]generatedFile, error) {
	workflows := mcpserver.Workflows()
	skills := skillCatalogByName(mcpserver.Skills())
	files := make([]generatedFile, 0, 32)

	rootAgentsPath := filepath.Join(repoRoot, "AGENTS.md")
	rootAgents, err := os.ReadFile(rootAgentsPath)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", rootAgentsPath, err)
	}

	ruleContent, err := renderAntigravityRule(repoRoot)
	if err != nil {
		return nil, err
	}
	if err := validateMarkdownLimit(filepath.Join(".agents", "rules", "ralphglasses.md"), ruleContent); err != nil {
		return nil, err
	}
	files = append(files, generatedFile{
		RelPath: filepath.Join(".agents", "rules", "ralphglasses.md"),
		Content: []byte(ruleContent),
		Mode:    0o644,
	})

	commandFiles := make([]generatedFile, 0, len(workflows)*2)
	for _, wf := range workflows {
		workflowContent, err := renderWorkflowMarkdown(wf, skills)
		if err != nil {
			return nil, err
		}
		if err := validateMarkdownLimit(filepath.Join(".agents", "workflows", wf.Name+".md"), workflowContent); err != nil {
			return nil, err
		}
		files = append(files, generatedFile{
			RelPath: filepath.Join(".agents", "workflows", wf.Name+".md"),
			Content: []byte(workflowContent),
			Mode:    0o644,
		})

		commandContent := renderWorkflowCommand(wf)
		commandFiles = append(commandFiles,
			generatedFile{
				RelPath: filepath.Join(".gemini", "commands", "ralph", wf.Name+".toml"),
				Content: []byte(commandContent),
				Mode:    0o644,
			},
			generatedFile{
				RelPath: filepath.Join(".gemini", "extensions", "ralphglasses-workspace", "commands", "ralph", wf.Name+".toml"),
				Content: []byte(commandContent),
				Mode:    0o644,
			},
		)
	}
	files = append(files, commandFiles...)

	extensionRoot := filepath.Join(".gemini", "extensions", "ralphglasses-workspace")
	files = append(files,
		generatedFile{
			RelPath: filepath.Join(extensionRoot, "AGENTS.md"),
			Content: append([]byte("# "+generatedMarker+"\n\n"), rootAgents...),
			Mode:    0o644,
		},
		generatedFile{
			RelPath: filepath.Join(extensionRoot, "gemini-extension.json"),
			Content: mustJSON(map[string]any{
				"name":            "ralphglasses-workspace",
				"version":         "1.0.0",
				"description":     "Repo-native Ralphglasses workflows, MCP surfaces, and operator commands for Gemini and Antigravity.",
				"contextFileName": "AGENTS.md",
				"mcpServers": map[string]any{
					"ralphglasses": map[string]any{
						"command": "bash",
						"args": []string{
							"${extensionPath}${/}scripts${/}run-mcp-extension.sh",
						},
						"cwd": "${extensionPath}",
					},
				},
			}),
			Mode: 0o644,
		},
		generatedFile{
			RelPath: filepath.Join(extensionRoot, "scripts", "run-mcp-extension.sh"),
			Content: []byte(renderScript(`#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
extension_root="$(cd "${script_dir}/.." && pwd)"
repo_root="$(cd "${extension_root}/../../.." && pwd)"

cd "${repo_root}"
exec bash "${repo_root}/scripts/dev/run-mcp.sh" --scan-path "~/hairglasses-studio"
`)),
			Mode: 0o755,
		},
		generatedFile{
			RelPath: filepath.Join(extensionRoot, "scripts", "setup.sh"),
			Content: []byte(renderScript(`#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
extension_root="$(cd "${script_dir}/.." && pwd)"

echo "Validate the Ralphglasses Antigravity extension bundle before linking:"
bash "${script_dir}/validate.sh"
echo
echo "Link it into Gemini or Antigravity with:"
echo "  gemini extensions link \"${extension_root}\""
`)),
			Mode: 0o755,
		},
		generatedFile{
			RelPath: filepath.Join(extensionRoot, "scripts", "validate.sh"),
			Content: []byte(renderScript(`#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
extension_root="$(cd "${script_dir}/.." && pwd)"
repo_root="$(cd "${extension_root}/../../.." && pwd)"

required=(
  "${repo_root}/AGENTS.md"
  "${repo_root}/.mcp.json"
  "${repo_root}/.agents/rules/ralphglasses.md"
  "${repo_root}/.agents/workflows/discover-and-load.md"
  "${extension_root}/gemini-extension.json"
)

for path in "${required[@]}"; do
  [[ -e "${path}" ]] || { echo "missing: ${path}" >&2; exit 1; }
done

echo "ralphglasses Antigravity extension bundle looks healthy"
`)),
			Mode: 0o755,
		},
		generatedFile{
			RelPath: filepath.Join(extensionRoot, "scripts", "cleanup.sh"),
			Content: []byte(renderScript(`#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
extension_root="$(cd "${script_dir}/.." && pwd)"
repo_root="$(cd "${extension_root}/../../.." && pwd)"

find "${repo_root}/.gemini/commands" -maxdepth 1 -type f -name 'jit-*.toml' -delete 2>/dev/null || true
find "${repo_root}/.codex/agents" -maxdepth 1 -type f -name 'jit-*.toml' -delete 2>/dev/null || true

echo "cleaned stale JIT agent surfaces"
`)),
			Mode: 0o755,
		},
	)

	manifest := extensionManifest{Name: "ralphglasses-workspace", Version: "1.0.0"}
	for _, file := range files {
		if !strings.HasPrefix(file.RelPath, extensionRoot+string(filepath.Separator)) {
			continue
		}
		sum := sha256.Sum256(file.Content)
		manifest.Files = append(manifest.Files, extensionManifestEntry{
			Path:   strings.TrimPrefix(file.RelPath, extensionRoot+string(filepath.Separator)),
			SHA256: hex.EncodeToString(sum[:]),
		})
	}
	sort.Slice(manifest.Files, func(i, j int) bool { return manifest.Files[i].Path < manifest.Files[j].Path })
	files = append(files, generatedFile{
		RelPath: filepath.Join(extensionRoot, "content-manifest.json"),
		Content: mustJSON(manifest),
		Mode:    0o644,
	})

	return files, nil
}

func renderWorkflowMarkdown(wf mcpserver.WorkflowDef, skills map[string]mcpserver.SkillCatalogDef) (string, error) {
	var b strings.Builder
	b.WriteString("<!-- " + generatedMarker + " -->\n")
	b.WriteString("# " + wf.Name + "\n\n")
	b.WriteString(wf.Description + "\n\n")
	b.WriteString("## Steps\n\n")
	steps := workflowSteps(wf, skills)
	for i, step := range steps {
		b.WriteString(fmt.Sprintf("%d. %s\n", i+1, step))
	}
	b.WriteString("\n## References\n\n")
	if len(wf.Skills) > 0 {
		b.WriteString("- Skills: " + strings.Join(skillReferenceLines(wf.Skills, skills), ", ") + "\n")
	}
	if len(wf.Resources) > 0 {
		b.WriteString("- Resources: " + strings.Join(wf.Resources, ", ") + "\n")
	}
	if len(wf.Prompts) > 0 {
		b.WriteString("- Prompts: " + strings.Join(wf.Prompts, ", ") + "\n")
	}
	if len(wf.ToolGroups) > 0 {
		b.WriteString("- Tool groups: " + strings.Join(wf.ToolGroups, ", ") + "\n")
	}
	if len(wf.KeyTools) > 0 {
		b.WriteString("- Key tools: " + strings.Join(wf.KeyTools, ", ") + "\n")
	}
	return b.String(), nil
}

func renderWorkflowCommand(wf mcpserver.WorkflowDef) string {
	var b strings.Builder
	b.WriteString("# " + generatedMarker + "\n")
	b.WriteString(fmt.Sprintf("description = %q\n", "Run the "+wf.Name+" workflow"))
	b.WriteString("prompt = \"\"\"\n")
	b.WriteString("Follow the Ralphglasses workflow `" + wf.Name + "` from `.agents/workflows/" + wf.Name + ".md`.\n\n")
	b.WriteString("Requirements:\n")
	b.WriteString("1. Read `AGENTS.md` and `.agents/rules/ralphglasses.md` before mutating the repo.\n")
	b.WriteString("2. Use the workflow references and repo-native skills instead of inventing parallel flows.\n")
	b.WriteString("3. Keep the response concise, source-backed, and aligned with the MCP contract.\n\n")
	b.WriteString("Workflow summary:\n")
	for _, step := range workflowSteps(wf, nil) {
		b.WriteString("- " + step + "\n")
	}
	b.WriteString("\"\"\"\n")
	return b.String()
}

func renderAntigravityRule(repoRoot string) (string, error) {
	sections := []struct {
		file  string
		title string
	}{
		{file: "session.md", title: "Session"},
		{file: "mcp.md", title: "MCP"},
		{file: "tui.md", title: "TUI"},
		{file: "loop.md", title: "Loop"},
		{file: "cost.md", title: "Cost"},
	}

	var b strings.Builder
	b.WriteString("<!-- " + generatedMarker + " -->\n")
	b.WriteString("# Ralphglasses Antigravity Rules\n\n")
	b.WriteString("Use `AGENTS.md` as the canonical repo instruction file. Use `.agents/workflows/` for reusable operator flows, `.agents/skills/` for canonical skills, and `.mcp.json` for repo-local MCP registration.\n\n")
	for _, section := range sections {
		content, err := loadClaudeRuleSection(repoRoot, section.file)
		if err != nil {
			return "", err
		}
		b.WriteString("## " + section.title + "\n\n")
		b.WriteString(content)
		if !strings.HasSuffix(content, "\n") {
			b.WriteByte('\n')
		}
		b.WriteByte('\n')
	}
	return b.String(), nil
}

func loadClaudeRuleSection(repoRoot, fileName string) (string, error) {
	path := filepath.Join(repoRoot, ".claude", "rules", fileName)
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read %s: %w", path, err)
	}
	content := string(data)
	if strings.HasPrefix(content, "---\n") {
		parts := strings.SplitN(content, "\n---\n", 2)
		if len(parts) == 2 {
			content = parts[1]
		}
	}
	return strings.TrimSpace(content) + "\n", nil
}

func workflowSteps(wf mcpserver.WorkflowDef, skills map[string]mcpserver.SkillCatalogDef) []string {
	steps := []string{
		"Start from the repo-native references before using mutating tools.",
	}
	if len(wf.Resources) > 0 {
		steps = append(steps, "Read the relevant resources first: "+strings.Join(wf.Resources, ", ")+".")
	}
	if len(wf.Skills) > 0 {
		steps = append(steps, "Route the task through the matching skills: "+strings.Join(skillReferenceLines(wf.Skills, skills), ", ")+".")
	}
	if len(wf.ToolGroups) > 0 {
		steps = append(steps, "Load only the required tool groups: "+strings.Join(wf.ToolGroups, ", ")+".")
	}
	if len(wf.KeyTools) > 0 {
		steps = append(steps, "Use the key tools as the primary execution path: "+strings.Join(wf.KeyTools, ", ")+".")
	}
	if len(wf.Prompts) > 0 {
		steps = append(steps, "When structured prompting helps, use the matching prompts: "+strings.Join(wf.Prompts, ", ")+".")
	}
	return steps
}

func skillCatalogByName(defs []mcpserver.SkillCatalogDef) map[string]mcpserver.SkillCatalogDef {
	out := make(map[string]mcpserver.SkillCatalogDef, len(defs))
	for _, def := range defs {
		out[def.Name] = def
	}
	return out
}

func skillReferenceLines(names []string, skills map[string]mcpserver.SkillCatalogDef) []string {
	out := make([]string, 0, len(names))
	for _, name := range names {
		if skill, ok := skills[name]; ok && skill.CanonicalPath != "" {
			out = append(out, name+" ("+skill.CanonicalPath+")")
			continue
		}
		out = append(out, name)
	}
	return out
}

func validateMarkdownLimit(path, content string) error {
	if len(content) > maxAntigravityMarkdownChars {
		return fmt.Errorf("%s exceeds %d characters", path, maxAntigravityMarkdownChars)
	}
	return nil
}

func pruneGeneratedAntigravityFiles(repoRoot string, files []generatedFile) error {
	ownedDirs := []string{
		filepath.Join(repoRoot, ".agents", "workflows"),
		filepath.Join(repoRoot, ".gemini", "commands", "ralph"),
		filepath.Join(repoRoot, ".gemini", "extensions", "ralphglasses-workspace", "commands", "ralph"),
	}
	keep := make(map[string]struct{}, len(files))
	for _, file := range files {
		keep[filepath.Clean(filepath.Join(repoRoot, file.RelPath))] = struct{}{}
	}
	for _, dir := range ownedDirs {
		entries, err := os.ReadDir(dir)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return fmt.Errorf("read %s: %w", dir, err)
		}
		for _, entry := range entries {
			if entry.IsDir() {
				continue
			}
			path := filepath.Join(dir, entry.Name())
			if _, ok := keep[path]; ok {
				continue
			}
			data, err := os.ReadFile(path)
			if err != nil {
				return fmt.Errorf("read %s: %w", path, err)
			}
			if !strings.Contains(string(data), generatedMarker) {
				continue
			}
			if err := os.Remove(path); err != nil {
				return fmt.Errorf("remove stale generated file %s: %w", path, err)
			}
		}
	}
	return nil
}

func mustJSON(v any) []byte {
	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		panic(err)
	}
	return append(data, '\n')
}

func renderScript(content string) string {
	return "# " + generatedMarker + "\n" + content
}
