package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var (
	initForce   bool
	initMinimal bool
)

var initCmd = &cobra.Command{
	Use:   "init [directory]",
	Short: "Generate a default .ralphrc configuration file",
	Long: `Create a .ralphrc configuration file in the specified directory (or current
directory if none given). The generated file contains documented configuration
keys with sensible defaults.

Use --minimal to generate a bare-minimum config with only required keys.
Use --force to overwrite an existing .ralphrc file.`,
	Example: `  # Initialize in the current directory
  ralphglasses init

  # Initialize in a specific project directory
  ralphglasses init ~/projects/myrepo

  # Overwrite existing .ralphrc
  ralphglasses init --force

  # Minimal config (only required keys)
  ralphglasses init --minimal`,
	Args: cobra.MaximumNArgs(1),
	RunE: runInit,
}

func init() {
	initCmd.Flags().BoolVar(&initForce, "force", false,
		"Overwrite existing .ralphrc file")
	initCmd.Flags().BoolVar(&initMinimal, "minimal", false,
		"Generate minimal config with only required keys")
	rootCmd.AddCommand(initCmd)
}

func runInit(cmd *cobra.Command, args []string) error {
	dir := "."
	if len(args) > 0 {
		dir = args[0]
	}

	rcPath := filepath.Join(dir, ".ralphrc")

	if !initForce {
		if _, err := os.Stat(rcPath); err == nil {
			return fmt.Errorf(".ralphrc already exists at %s (use --force to overwrite)", rcPath)
		}
	}

	var content string
	if initMinimal {
		content = minimalRalphRC()
	} else {
		content = fullRalphRC()
	}

	if err := os.WriteFile(rcPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write .ralphrc: %w", err)
	}

	fmt.Printf("Created %s\n", rcPath)
	return nil
}

func minimalRalphRC() string {
	return `# .ralphrc — minimal ralph loop configuration
# See: ralphglasses init (without --minimal) for all options

PROJECT_NAME=myproject
PROVIDER=claude
MAX_CALLS_PER_HOUR=60
`
}

func fullRalphRC() string {
	return `# .ralphrc — ralph loop configuration
# Generated by: ralphglasses init
# Docs: https://github.com/hairglasses-studio/ralphglasses

# ── Required ──────────────────────────────────────────────────────────
# Project name (used in logs, TUI display, and fleet identification)
PROJECT_NAME=myproject

# ── Provider ──────────────────────────────────────────────────────────
# LLM provider: claude, gemini, or codex
PROVIDER=claude

# ── Rate Limiting ─────────────────────────────────────────────────────
# Maximum API calls per hour (prevents runaway loops)
MAX_CALLS_PER_HOUR=60

# Timeout in minutes for each Claude session
# CLAUDE_TIMEOUT_MINUTES=30

# ── Budget ────────────────────────────────────────────────────────────
# Budget cap in USD per loop iteration
# BUDGET_USD=5.0

# ── Circuit Breaker ───────────────────────────────────────────────────
# Number of consecutive failures before opening the circuit
# CB_FAILURE_THRESHOLD=5

# Number of successes in half-open state to close the circuit
# CB_SUCCESS_THRESHOLD=3

# Max calls allowed in half-open state
# CB_HALF_OPEN_MAX_CALLS=3

# ── Loop Behavior ─────────────────────────────────────────────────────
# Task prompt for the ralph loop
# TASK_PROMPT=Review code and suggest improvements

# Auto-approve loop steps (no human-in-the-loop)
# AUTO_APPROVE=false

# ── Notifications ─────────────────────────────────────────────────────
# Enable desktop notifications for loop events
# NOTIFY=false

# ── Self-Improvement ──────────────────────────────────────────────────
# Enable self-improvement pipeline
# SELF_IMPROVE=false

# Cost observation tracking
# COST_TRACKING=true
`
}
