// Package envkit provides environment bootstrap utilities for Claude Code development.
package envkit

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// MiseInfo describes the current mise installation and active tool versions.
type MiseInfo struct {
	Installed bool              `json:"installed"`
	Version   string            `json:"version"`
	Tools     map[string]string `json:"tools"` // name → version
}

// MiseOpts configures mise installation behavior.
type MiseOpts struct {
	DryRun bool              `json:"dry_run,omitempty"`
	Tools  map[string]string `json:"tools,omitempty"` // name → version
}

// MiseResult describes the outcome of a mise install operation.
type MiseResult struct {
	Installed  bool   `json:"installed"`
	ConfigPath string `json:"config_path"`
	Output     string `json:"output"`
}

// DefaultMiseTools returns the recommended tool versions for Claude Code development.
func DefaultMiseTools() map[string]string {
	return map[string]string{
		"go":     "latest",
		"node":   "lts",
		"python": "latest",
	}
}

// MiseStatus checks if mise is installed and returns current tool versions.
func MiseStatus(ctx context.Context) (*MiseInfo, error) {
	info := &MiseInfo{
		Tools: make(map[string]string),
	}

	misePath, err := exec.LookPath("mise")
	if err != nil {
		return info, nil // not installed, no error
	}
	info.Installed = true

	// Get version
	out, err := exec.CommandContext(ctx, misePath, "--version").Output()
	if err == nil {
		info.Version = strings.TrimSpace(string(out))
	}

	// Get active tools via mise ls --json
	out, err = exec.CommandContext(ctx, misePath, "ls", "--json").Output()
	if err != nil {
		return info, nil // installed but can't list tools
	}

	// mise ls --json returns map[toolName][]{"version": "x.y.z", ...}
	var toolMap map[string][]map[string]any
	if err := json.Unmarshal(out, &toolMap); err != nil {
		return info, nil
	}

	for name, versions := range toolMap {
		if len(versions) > 0 {
			if v, ok := versions[0]["version"].(string); ok {
				info.Tools[name] = v
			}
		}
	}

	return info, nil
}

// MiseInstall ensures mise is installed and configures recommended tools.
func MiseInstall(ctx context.Context, opts MiseOpts) (*MiseResult, error) {
	result := &MiseResult{}

	tools := opts.Tools
	if len(tools) == 0 {
		tools = DefaultMiseTools()
	}

	// Check if already installed
	misePath, err := exec.LookPath("mise")
	if err != nil {
		if opts.DryRun {
			result.Output = "would install mise via curl"
			return result, nil
		}

		// Try brew first, then curl
		brewPath, brewErr := exec.LookPath("brew")
		if brewErr == nil {
			out, err := exec.CommandContext(ctx, brewPath, "install", "mise").CombinedOutput()
			if err != nil {
				return nil, fmt.Errorf("brew install mise: %s", string(out))
			}
			result.Output = string(out)
		} else {
			// Fall back to curl installer
			cmd := exec.CommandContext(ctx, "bash", "-c", "curl -fsSL https://mise.jdx.dev/install.sh | bash")
			out, err := cmd.CombinedOutput()
			if err != nil {
				return nil, fmt.Errorf("curl install mise: %s", string(out))
			}
			result.Output = string(out)
		}

		// Verify installation
		misePath, err = exec.LookPath("mise")
		if err != nil {
			return nil, fmt.Errorf("mise not found after installation")
		}
		result.Installed = true
	}

	// Write config
	cwd, err := os.Getwd()
	if err != nil {
		cwd = "."
	}

	if opts.DryRun {
		result.Output += "\nwould write .mise.toml"
		return result, nil
	}

	configPath, err := GenerateMiseConfig(cwd, tools)
	if err != nil {
		return nil, err
	}
	result.ConfigPath = configPath

	// Run mise install
	out, err := exec.CommandContext(ctx, misePath, "install").CombinedOutput()
	if err != nil {
		result.Output += "\nmise install: " + string(out)
	} else {
		result.Output += string(out)
	}

	return result, nil
}

// GenerateMiseConfig writes a .mise.toml with the specified tool versions.
func GenerateMiseConfig(dir string, tools map[string]string) (string, error) {
	if len(tools) == 0 {
		tools = DefaultMiseTools()
	}

	var b strings.Builder
	b.WriteString("# Generated by claudekit\n")
	b.WriteString("[tools]\n")

	for name, version := range tools {
		b.WriteString(fmt.Sprintf("%s = %q\n", name, version))
	}

	configPath := filepath.Join(dir, ".mise.toml")
	if err := os.WriteFile(configPath, []byte(b.String()), 0o644); err != nil {
		return "", fmt.Errorf("write .mise.toml: %w", err)
	}

	return configPath, nil
}
