package envkit

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)


func TestMiseStatus(t *testing.T) {
	ctx := context.Background()
	info, err := MiseStatus(ctx)
	if err != nil {
		t.Fatalf("MiseStatus should not error even if mise is not installed: %v", err)
	}
	if info == nil {
		t.Fatal("MiseStatus returned nil")
	}
	if info.Tools == nil {
		t.Error("Tools map should be initialized, not nil")
	}
}

func TestGenerateMiseConfig(t *testing.T) {
	dir := t.TempDir()
	tools := map[string]string{
		"go":   "1.23",
		"node": "lts",
	}

	path, err := GenerateMiseConfig(dir, tools)
	if err != nil {
		t.Fatalf("GenerateMiseConfig: %v", err)
	}

	if filepath.Base(path) != ".mise.toml" {
		t.Errorf("expected .mise.toml, got %s", filepath.Base(path))
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read config: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "[tools]") {
		t.Error("config should contain [tools] section")
	}
	if !strings.Contains(content, "go") {
		t.Error("config should contain go tool")
	}
	if !strings.Contains(content, "node") {
		t.Error("config should contain node tool")
	}
}

func TestGenerateMiseConfigDefaults(t *testing.T) {
	dir := t.TempDir()

	path, err := GenerateMiseConfig(dir, nil)
	if err != nil {
		t.Fatalf("GenerateMiseConfig with nil tools: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read config: %v", err)
	}

	content := string(data)
	for _, tool := range []string{"go", "node", "python"} {
		if !strings.Contains(content, tool) {
			t.Errorf("default config should contain %s", tool)
		}
	}
}

func TestDefaultMiseTools(t *testing.T) {
	tools := DefaultMiseTools()
	if len(tools) == 0 {
		t.Fatal("DefaultMiseTools should return non-empty map")
	}
	if _, ok := tools["go"]; !ok {
		t.Error("should include go")
	}
	if _, ok := tools["node"]; !ok {
		t.Error("should include node")
	}
	if _, ok := tools["python"]; !ok {
		t.Error("should include python")
	}
}

func TestMiseStatusNotInstalled(t *testing.T) {
	// Set PATH to empty so mise is not found
	t.Setenv("PATH", t.TempDir())
	ctx := context.Background()
	info, err := MiseStatus(ctx)
	if err != nil {
		t.Fatalf("MiseStatus should not error when mise is not installed: %v", err)
	}
	if info.Installed {
		t.Error("expected Installed=false when mise is not in PATH")
	}
	if info.Version != "" {
		t.Errorf("expected empty Version, got %q", info.Version)
	}
	if info.Tools == nil {
		t.Error("Tools map should be initialized, not nil")
	}
}

func TestMiseInstallDryRun(t *testing.T) {
	// Set PATH to empty so mise is not found
	t.Setenv("PATH", t.TempDir())
	ctx := context.Background()
	result, err := MiseInstall(ctx, MiseOpts{DryRun: true})
	if err != nil {
		t.Fatalf("MiseInstall dry-run should not error: %v", err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
	if !strings.Contains(result.Output, "would install") {
		t.Errorf("dry-run output should mention 'would install', got %q", result.Output)
	}
}

func TestMiseInstallDryRunWithCustomTools(t *testing.T) {
	t.Setenv("PATH", t.TempDir())
	ctx := context.Background()
	tools := map[string]string{"go": "1.23", "rust": "latest"}
	result, err := MiseInstall(ctx, MiseOpts{DryRun: true, Tools: tools})
	if err != nil {
		t.Fatalf("MiseInstall dry-run with custom tools: %v", err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
	if !strings.Contains(result.Output, "would install") {
		t.Errorf("dry-run output should mention 'would install', got %q", result.Output)
	}
}

func TestGenerateMiseConfigFormat(t *testing.T) {
	dir := t.TempDir()
	tools := map[string]string{
		"go":     "1.23",
		"node":   "lts",
		"python": "3.12",
	}

	path, err := GenerateMiseConfig(dir, tools)
	if err != nil {
		t.Fatalf("GenerateMiseConfig: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read config: %v", err)
	}

	content := string(data)

	// Verify header comment
	if !strings.HasPrefix(content, "# Generated by claudekit") {
		t.Error("config should start with generated-by comment")
	}

	// Verify [tools] section
	if !strings.Contains(content, "[tools]") {
		t.Error("config should contain [tools] section")
	}

	// Verify each tool is present with quoted version
	for name, version := range tools {
		expected := name + " = \"" + version + "\""
		if !strings.Contains(content, expected) {
			t.Errorf("config should contain %q, got:\n%s", expected, content)
		}
	}
}

func TestGenerateMiseConfigEmptyMap(t *testing.T) {
	dir := t.TempDir()
	// Empty map should use defaults
	path, err := GenerateMiseConfig(dir, map[string]string{})
	if err != nil {
		t.Fatalf("GenerateMiseConfig with empty map: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read config: %v", err)
	}

	content := string(data)
	// With empty map, defaults are used
	for _, tool := range []string{"go", "node", "python"} {
		if !strings.Contains(content, tool) {
			t.Errorf("default config should contain %s", tool)
		}
	}
}

func TestGenerateMiseConfigInvalidDir(t *testing.T) {
	_, err := GenerateMiseConfig("/nonexistent/path/that/does/not/exist", map[string]string{"go": "1.23"})
	if err == nil {
		t.Error("expected error writing to nonexistent directory")
	}
}

func TestMiseInfoInitialization(t *testing.T) {
	info := &MiseInfo{
		Tools: make(map[string]string),
	}
	if info.Installed {
		t.Error("default should be not installed")
	}
	if info.Version != "" {
		t.Error("default version should be empty")
	}
	if info.Tools == nil {
		t.Error("Tools should not be nil")
	}
}

func TestMiseOptsDefaults(t *testing.T) {
	opts := MiseOpts{}
	if opts.DryRun {
		t.Error("default DryRun should be false")
	}
	if opts.Tools != nil {
		t.Error("default Tools should be nil")
	}
}

func TestMiseStatusFieldsWhenNotInstalled(t *testing.T) {
	t.Setenv("PATH", t.TempDir())
	ctx := context.Background()
	info, err := MiseStatus(ctx)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if info.Installed {
		t.Error("should not be installed")
	}
	if info.Version != "" {
		t.Errorf("version should be empty, got %q", info.Version)
	}
	if len(info.Tools) != 0 {
		t.Errorf("tools should be empty, got %v", info.Tools)
	}
}

func TestMiseInstallNotInstalledNotDryRun(t *testing.T) {
	// Set PATH to empty dir so neither mise nor brew are found
	emptyDir := t.TempDir()
	t.Setenv("PATH", emptyDir)
	ctx := context.Background()

	// This will fail because neither brew nor curl is available in the empty PATH
	_, err := MiseInstall(ctx, MiseOpts{DryRun: false})
	if err == nil {
		// If it somehow succeeds (unlikely with empty PATH), that's fine too
		t.Log("MiseInstall succeeded unexpectedly with empty PATH")
	}
	// The important thing is we hit the code path, error or not
}

func TestMiseResultFields(t *testing.T) {
	result := &MiseResult{
		Installed:  true,
		ConfigPath: "/tmp/test/.mise.toml",
		Output:     "installed successfully",
	}
	if !result.Installed {
		t.Error("expected Installed=true")
	}
	if result.ConfigPath != "/tmp/test/.mise.toml" {
		t.Errorf("unexpected ConfigPath: %s", result.ConfigPath)
	}
	if result.Output != "installed successfully" {
		t.Errorf("unexpected Output: %s", result.Output)
	}
}

func TestGenerateMiseConfigOverwrite(t *testing.T) {
	dir := t.TempDir()

	// Write initial config
	_, err := GenerateMiseConfig(dir, map[string]string{"go": "1.22"})
	if err != nil {
		t.Fatalf("first GenerateMiseConfig: %v", err)
	}

	// Overwrite with new config
	path, err := GenerateMiseConfig(dir, map[string]string{"go": "1.23", "rust": "latest"})
	if err != nil {
		t.Fatalf("second GenerateMiseConfig: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read config: %v", err)
	}

	content := string(data)
	if strings.Contains(content, "1.22") {
		t.Error("old version should have been overwritten")
	}
	if !strings.Contains(content, "1.23") {
		t.Error("new go version should be present")
	}
	if !strings.Contains(content, "rust") {
		t.Error("rust tool should be present")
	}
}

// createFakeMise creates a fake "mise" script in a temp dir and returns the dir
// to prepend to PATH. The script responds to --version and ls --json.
func createFakeMise(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	script := filepath.Join(dir, "mise")
	content := `#!/bin/sh
case "$1" in
  --version)
    echo "2024.1.0 macos-arm64 (fake)"
    ;;
  ls)
    echo '{"go":[{"version":"1.23.0"}],"node":[{"version":"22.0.0"}]}'
    ;;
  install)
    echo "installed (fake)"
    ;;
  *)
    echo "unknown command: $*" >&2
    exit 1
    ;;
esac
`
	if err := os.WriteFile(script, []byte(content), 0o755); err != nil {
		t.Fatal(err)
	}
	return dir
}

func TestMiseStatusInstalled(t *testing.T) {
	fakeDir := createFakeMise(t)
	t.Setenv("PATH", fakeDir)
	ctx := context.Background()
	info, err := MiseStatus(ctx)
	if err != nil {
		t.Fatalf("MiseStatus: %v", err)
	}
	if !info.Installed {
		t.Error("expected Installed=true with fake mise in PATH")
	}
	if info.Version == "" {
		t.Error("expected non-empty version")
	}
	if !strings.Contains(info.Version, "2024.1.0") {
		t.Errorf("expected version containing '2024.1.0', got %q", info.Version)
	}
	if len(info.Tools) == 0 {
		t.Error("expected non-empty tools map")
	}
	if v, ok := info.Tools["go"]; !ok || v != "1.23.0" {
		t.Errorf("expected go=1.23.0, got %v", info.Tools)
	}
	if v, ok := info.Tools["node"]; !ok || v != "22.0.0" {
		t.Errorf("expected node=22.0.0, got %v", info.Tools)
	}
}

func TestMiseStatusInstalledBadJSON(t *testing.T) {
	// Create a fake mise that returns invalid JSON for ls
	dir := t.TempDir()
	script := filepath.Join(dir, "mise")
	content := `#!/bin/sh
case "$1" in
  --version) echo "1.0.0" ;;
  ls) echo "not-json" ;;
  *) exit 1 ;;
esac
`
	if err := os.WriteFile(script, []byte(content), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", dir)
	ctx := context.Background()
	info, err := MiseStatus(ctx)
	if err != nil {
		t.Fatalf("MiseStatus should not error on bad JSON: %v", err)
	}
	if !info.Installed {
		t.Error("expected Installed=true")
	}
	// Tools should be empty since JSON parsing failed
	if len(info.Tools) != 0 {
		t.Errorf("expected empty tools on bad JSON, got %v", info.Tools)
	}
}

func TestMiseStatusInstalledLsError(t *testing.T) {
	// Create a fake mise that errors on ls
	dir := t.TempDir()
	script := filepath.Join(dir, "mise")
	content := `#!/bin/sh
case "$1" in
  --version) echo "1.0.0" ;;
  ls) exit 1 ;;
  *) exit 1 ;;
esac
`
	if err := os.WriteFile(script, []byte(content), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", dir)
	ctx := context.Background()
	info, err := MiseStatus(ctx)
	if err != nil {
		t.Fatalf("MiseStatus should not error on ls failure: %v", err)
	}
	if !info.Installed {
		t.Error("expected Installed=true")
	}
	if len(info.Tools) != 0 {
		t.Errorf("expected empty tools on ls error, got %v", info.Tools)
	}
}

func TestMiseInstallWithFakeMise(t *testing.T) {
	fakeDir := createFakeMise(t)
	t.Setenv("PATH", fakeDir)
	workDir := t.TempDir()
	// Change to work dir so GenerateMiseConfig writes there
	origDir, _ := os.Getwd()
	if err := os.Chdir(workDir); err != nil {
		t.Fatal(err)
	}
	defer os.Chdir(origDir)

	ctx := context.Background()
	result, err := MiseInstall(ctx, MiseOpts{
		Tools: map[string]string{"go": "1.23"},
	})
	if err != nil {
		t.Fatalf("MiseInstall with fake mise: %v", err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
	if result.ConfigPath == "" {
		t.Error("expected non-empty ConfigPath")
	}
	// Verify config was written
	if _, err := os.Stat(result.ConfigPath); err != nil {
		t.Errorf("config file should exist: %v", err)
	}
}

func TestMiseInstallDryRunDefaultTools(t *testing.T) {
	t.Setenv("PATH", t.TempDir())
	ctx := context.Background()
	// Use nil tools to trigger default tools path; mise not in PATH so dry-run returns early
	result, err := MiseInstall(ctx, MiseOpts{DryRun: true, Tools: nil})
	if err != nil {
		t.Fatalf("MiseInstall dry-run default tools: %v", err)
	}
	if !strings.Contains(result.Output, "would install") {
		t.Errorf("dry-run output should mention 'would install', got %q", result.Output)
	}
}
